### ISSUE TITLE
Combine install and install_tree?

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#10209]
In https://github.com/spack/spack/pull/10152/files#r244341437, @healther suggested combining `copy` and `copy_tree` (and similarly `install` and `install_tree`) into a single `copy` (and `install`) method that knows what to do when it encounters either a single file or a directory structure.

### Rationale

This change would simplify the API for copying/installing files and directories.

### Description

The simplest way of implementing this change would be add a check in `copy` to see if `src` is a file or a directory. Aside from that, we would simply be combining the logic of `copy` and `copy_tree` into a single method.

### Additional information

The incentive to keep things the way they are, and probably the reason they were designed this way in the first place, is that this is how other libraries do things. For example:

- Python's `shutil` module has separate [copy](https://docs.python.org/3/library/shutil.html#shutil.copy) and [copytree](https://docs.python.org/3/library/shutil.html#shutil.copytree) methods
- Python's `distutils` package has separate [file_util.copy_file](https://docs.python.org/3.7/distutils/apiref.html#distutils.file_util.copy_file) and [dir_util.copy_tree](https://docs.python.org/3.7/distutils/apiref.html#distutils.dir_util.copy_tree) methods.

**Comment by michaelkuhn** [comment]
I actually fell into the trap of trying to use `copy_tree` for a source file. :smile:

From a usability point of view, having a single `copy`/`install` method would be easier. However, since `install` and `install_tree` are mainly used in packages, it might make sense to keep them separate so we notice if something that should be a directory suddenly ends up being a file (and vice versa).

**Comment by adamjstewart** [comment]
This discussion is dead, so I'm going to close this.
