### ISSUE TITLE
Lua load all dependencies

### ISSUE THREAD

**Issue by mforde84** [spack/spack#10367]
I have some previous experience manually generating lua files for a lmod library. Generally speaking, we would explicitly load any shared libraries and headers used for compilation upon a package load. It appears that the module files spack generates doesn't do this, so it's possible to load a package dependent on one version of say ncurses and then load a separate version of ncurses to the headers and library paths.  Eg.,

```
[root@gosset:~]# module list

Currently Loaded Modules:
  1) gcc/7.4.0   2) samtools/1.9



[root@gosset:~]# ldd `which samtools`
        linux-vdso.so.1 =>  (0x00007ffdb8aac000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002acdb2858000)
        libz.so.1 => /mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/zlib-1.2.11-25pskdmfdd52x3ewomarucg3eu6mswte/lib/libz.so.1 (0x00002acdb2a74000)
        libm.so.6 => /lib64/libm.so.6 (0x00002acdb2c8c000)
        libbz2.so.1.0 => /mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/bzip2-1.0.6-y4qayy3nlojfq3ctw6wbfeorrq7xdk26/lib/libbz2.so.1.0 (0x00002acdb2f8e000)
        liblzma.so.5 => /mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/xz-5.2.4-vewnijktsjco3mbf2ycv6irlvlur46uq/lib/liblzma.so.5 (0x00002acdb319e000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00002acdb33c5000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00002acdb362e000)
        libncursesw.so.6 => /mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/ncurses-6.1-svwt4yh6tdtt7qtfuefht5d2bpll3f2p/lib/libncursesw.so.6 (0x00002acdb3a8f000)
        libc.so.6 => /lib64/libc.so.6 (0x00002acdb3d0a000)
        /lib64/ld-linux-x86-64.so.2 (0x000055bb83fc7000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00002acdb40d7000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00002acdb430a000)
        libssl3.so => /lib64/libssl3.so (0x00002acdb4535000)
        libsmime3.so => /lib64/libsmime3.so (0x00002acdb4781000)
        libnss3.so => /lib64/libnss3.so (0x00002acdb49a8000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00002acdb4cd3000)
        libplds4.so => /lib64/libplds4.so (0x00002acdb4f00000)
        libplc4.so => /lib64/libplc4.so (0x00002acdb5104000)
        libnspr4.so => /lib64/libnspr4.so (0x00002acdb530a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002acdb5548000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00002acdb574c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00002acdb599a000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00002acdb5c82000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00002acdb5eb5000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00002acdb60ba000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00002acdb62c9000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00002acdb651e000)
        librt.so.1 => /lib64/librt.so.1 (0x00002acdb6790000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00002acdb6999000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00002acdb6ba7000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00002acdb6dab000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00002acdb6fc5000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00002acdb71e2000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00002acdb740a000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00002acdb7641000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00002acdb78a3000)
[root@gosset:~]# module load ncurses/6.0
[root@gosset:~]# module list

Currently Loaded Modules:
  1) gcc/7.4.0   2) samtools/1.9   3) ncurses/6.0



[root@gosset:~]# echo $LD_LIBRARY_PATH
/mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/ncurses-6.0-lxirmoeyz63ywzsiodd6zzzh6uoi2g4f/lib:/mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/samtools-1.9-m547dlsaia3x3co62zqhgnqqln2w5aj7/lib:/mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.4.0-bved7bzpjss3w3d3qe4mur5qc25nfll6/lib64:/mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.4.0-bved7bzpjss3w3d3qe4mur5qc25nfll6/lib:/usr/lib/oracle/12.2/client64/lib::
```

In this example samtools/1.9 was compiled with ncurses/6.1 as confirmed by the library linking. However I can load a different version of ncurses/6.0 and it won't link against samtools, but will show up in my lib path. Do I have to worry about this type of behavior? I presume this is the bit about package concretization?

Is there a way for lua files to explicitly load all dependencies? Or is this truly unnecessary to ensure appropriate linking with libraries used for compilation?

M

**Comment by hartzell** [comment]
You should read the modules tutorial.  In particular, the [bit here about autoloading dependencies](https://spack.readthedocs.io/en/latest/tutorial_modules.html#autoload-dependencies) is particularly relevant to your question about loading prerequisites.

The bits about [filtering unwanted variables](https://spack.readthedocs.io/en/latest/tutorial_modules.html#filter-unwanted-modifications-to-the-environment) and [adding custom variables](https://spack.readthedocs.io/en/latest/tutorial_modules.html#add-custom-environment-modifications) are also relevant.

It's *really*, *really* worth plodding your way (sorry @alalazo) through the tutorial and experiencing each of the changes for yourself.  It's *incredibly* flexible once you understand how it works.

**Remember that a package that lives up to Spack's high standards (not all do...) is completely determined at build time (concretization time?)**.

All library dependencies are linked explicitly to their particular shared libraries (via RPATH or ...).  There should not be anything you can set at run time that will change their behavior.  Things like Perl, Python, R, etc... that expect to discover things at run time via some specific environment variable( e.g. PERL5LIB and PYTHONPATH) are less robust.  Spack's introduced the concept of [extensions to address some of this](https://spack.readthedocs.io/en/latest/tutorial_modules.html#add-custom-environment-modifications) but it's still a bit of a crap shoot.

>  It appears that the module files spack generates doesn't do this, so it's possible to load a package dependent on one version of say ncurses and then load a separate version of ncurses to the headers and library paths.

Your `samtools` build was concretized and built against one version of ncurses, using RPATH to ensure that that version would be used at run time.  Loading a different `ncurses` module into your environment doesn't change that.  Another way to say it is that `samtools` has a `['build', 'link']` dependency on `ncurses` (the default...).  There's nothing you can do at run-time to change that.  Contrast that with `autofact`, which needs a bunch of stuff placed into its environment at run-time to work (so it has things like `depends_on('perl-bio-perl', type='run')`).  For `autofact`, the module file needs to stuff the correct bits into the environment.

> Generally speaking, we would explicitly load any shared libraries and headers used for compilation upon a package load.

That's not so clear. [It can lead to some craziness](https://github.com/spack/spack/issues/10307#issuecomment-453790774), like `yum` and `rpm` no longer working on CentOS 7.


Generally, the modules that Spack generates try to set things up so that you can *use* their artifacts (e.g. `emacs`) **and** build things against them (e.g. build out-of-tree R libraries that depend on a Spack-based R and various Spack-based libraries libraries like `libpng` and BLAS stuff).

But, potential craziness....

I started a discussion about it a year or two back in [Setting LD_LIBRARY_PATH to be "helpful" considered harmful](https://github.com/spack/spack/issues/3955).  Similar issues recently resurfaced when I was helping @odoublewen build R libraries out-of-tree, that's ongoing here in [How do folks build software outside of Spack that uses Spack artifacts?](https://github.com/spack/spack/issues/10307).

**Comment by mforde84** [comment]
Cool, thanks for the clarifications. Sorry, I don't mean to make you guys answer questions that are already documented, I just occasionally have difficultly finding the relevant info in the docs. The tutorials have been helpful, though a lot of times I'm just looking for a quick reference guide honestly. So thanks for putting up with me. :D

**Comment by hartzell** [comment]
@mforde84 -- You're completely welcome.

I obsessively point out the relevant docs because then the Issue becomes something that other Googler's (Duck Duck Go'ers) can benefit from.  If you ask the question, others will too....

Good descriptions of things that are missing from the docs would make good issues.  Even better PR's.... ;)  There's a lot that's useful though, it's hard to hit "just the important stuff".

**Comment by goxberry** [comment]
@hartzell I'd argue that on macOS, the current spack behavior with `DYLD_LIBRARY_PATH` (the analogue to `LD_LIBRARY_PATH`) doesn't work; cf. https://github.com/spack/spack/pull/9221, with a minimum working example and lots of explanations.

**Comment by mforde84** [comment]
Cant you just pretend to the env variable? If you load something then that takes precedence. While leaving other stuff alone,  like yum. Unless you start compiling what should be default system space libraries into the lmod space, eg. Like glibc

**Comment by hartzell** [comment]
@goxberry -- eeek (and thanks).  I usually don't set `LD_LIBRARY_PATH` in my lmod modulefiles, it causes the issues I linked to above.  I think that Spack's using RPATH instead of depending on `LD_LIBRARY_PATH` is a great thing and have argued that we shouldn't set it.

A quick skim of #9221 sounds complicated and spooky.  I'll take a look at it when I'm fresher...

**Comment by goxberry** [comment]
For what it's worth, I basically maintain a fork of spack at this point, because neither the CMake rpath settings nor the dynamic loading mechanism seem to work correctly on some edge cases without #9221 (which I seem to need to build any project that uses OpenBLAS and CMake) and #9249 (which I seem to need to get `googletest` to build, though arguably, this package should be vendored into projects instead of installed through a package manager).
