### ISSUE TITLE
Show Concretized Environment?

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10598]
@scheibelp @tgamblin 
I've created a Spack Environment, used `spack -e ... add`, then `spack -e ... concretize -f`.  Now BEFORE I use `spack - ... install`, I would like to print out and inspect the fully concretized environment.  (Basically, repeat the output of `spack -e ... concretize` without actually doing anything).

Is there a command to do this?  Logically, `spack -e ... spec` with no additional arguments should do it.

**Comment by skwde** [comment]
@citibeth Is there already a solution to this?

Apparently it seems that

```sh
spack -e <env name / path> spec --install-status
```

does the trick.

**Comment by citibeth** [comment]
I have no idea

**Comment by scheibelp** [comment]
@skwde it looks like you answered your question in the same comment

The mechanism I'm familiar with to do this is `spack find -c` (`-c` has been added since this issue was raised, and `spack find --help` expands it to `--show-concretized`).

Because we now have a means to resolve this, I'm closing the issue.

**Comment by skwde** [comment]
@scheibelp

Yes, I made the comment and shortly after I discovered what I mentioned in above post. I didn't clearly mark it as edit.
In any case,  thanks for the additional solution.
