### ISSUE TITLE
Installing a package with a new compiler causes directory to be created with the wrong group ownership 

### ISSUE THREAD

**Issue by frankwillmore** [spack/spack#11240]
Installing a package with a new compiler causes directory to be created with the wrong group ownership. 

### Steps to reproduce the issue

```
ecptestb@thetalogin1:/lus/theta-fs0/software/spack/spack-dev/opt/spack/cray-cnl8-mic_knl> ll
drwxrwxr-x 6 spack    software 4096 Apr 19 16:47 gcc-8.2.0
ecptestb@thetalogin1:/lus/theta-fs0/software/spack/spack-dev/opt/spack/cray-cnl8-mic_knl> spack install spack-dummy-package %intel@18.0.0.128 
==> mpich@3.1 : has external module in cray-mpich
...
==> Successfully installed spack-dummy-package
  Fetch: 0.25s.  Build: 2.25s.  Total: 2.50s.
[+] /lus/theta-fs0/software/spack/spack-dev/opt/spack/cray-cnl8-mic_knl/intel-18.0.0.128/spack-dummy-package-refactor-yebephikrhqwmc36r2xtrrt7uobwllyx
ecptestb@thetalogin1:/lus/theta-fs0/software/spack/spack-dev/opt/spack/cray-cnl8-mic_knl> ll
drwxrwxr-x 6 spack    software       4096 Apr 19 16:47 gcc-8.2.0
drwxrwxr-x 3 ecptestb **ecp-testbed-01** 4096 Apr 19 20:56 intel-18.0.0.128
ecptestb@thetalogin1:/lus/theta-fs0/software/spack/spack-dev/opt/spack/cray-cnl8-mic_knl> ll intel-18.0.0.128/
total 4
drwxrwsr-x 4 ecptestb software 4096 Apr 19 20:56 spack-dummy-package-refactor-yebephikrhqwmc36r2xtrrt7uobwllyx
```

The package installed and has correct group (software) ownership within the subdirectory, but the parent intel-18.0.0.128 directory is created with the wrong group ownership (user's default group). 

The packages.py file declares the group and permission settings which are handled correctly for the final installation directory, just not the intermediate. 
```
packages:
  all:
    permissions:
      write: group
      group: software
```

### Information on your system

Cray XC-40 theta at ALCF

**Comment by albestro** [comment]
I'm addressing the same problem with a shared multi-user instance of spack.

I gave a quick look at the code, trying to follow the code.

Starting point is in this snippet, where it checks for the existance of the folder, and in case it triggers the folder creation with `create_install_directory`
https://github.com/spack/spack/blob/d3be42fccaabbdc71c03da0886214b31a29921e5/lib/spack/spack/package.py#L1604-L1618

Then this code snippet follows, where a call to `mkdirp` creates the folder.

https://github.com/spack/spack/blob/d3be42fccaabbdc71c03da0886214b31a29921e5/lib/spack/spack/directory_layout.py#L267-L274

**I think that the problem lies here**: `mkdirp` creates both the destination folder, with the right permissions, and also all the intermediate parent directories that does not exist, without caring about permissions. **So the package folder gets permission set, while all intermediate folders (compiler one, but also architecture) not**.

IMHO `mkdirp` does the right thing and permissions has to be set on the compiler folder by `PackageBase::do_install` or by the `create_install_directory` (that at the moment seems to be used just by packages).

I don't know exactly how deep the package folder can be (e.g. arch_dir/compiler_dir/package_dir, but I think that it is ok to think that permissions set in `packages.yaml` should be set on all folders in the path that are under the prefix `$SPACK_ROOT/opt/spack`
