### ISSUE TITLE
spack configure should accept --test option

### ISSUE THREAD

**Issue by jjwilke** [spack/spack#11277]
Certain packages need to configure differently if tests are enabled (i.e. Trilinos).
spack configure (I think) does not accept the `--test=root` option. 

I believe `self.run_tests` is the approved way of enabling tests rather than having a `+test` variant?

**Comment by adamjstewart** [comment]
@alalazo can you take a look at this? I think `spack build` and possibly stages earlier than `configure` may need a `--test` flag if they download additional test dependencies.

**Comment by scheibelp** [comment]
> I believe self.run_tests is the approved way of enabling tests rather than having a +test variant?

If building tests changes the package, then a `+test` variant may be suitable. Generally it is assumed that building test dependencies and running tests doesn't change the installed bits and so using `self.run_tests` is ideal.

**Comment by naromero77** [comment]
I would also be interested in such an option. For a large package, there may be different sets of tests that you would want for validating that the install is legit. Our tests suites provide various levels of coverage traded off with length to run the tests. For example, in QMCPACK we have unit, deterministic, short, and everything. Unit tests are the minimum bar for an install, deterministic is highly recommended, short is practically speaking the best coverage if you are willing to wait an hour. everything almost never succeeds and takes several hours. It is mostly for developers, because it includes some unstable tests.

This is labeled as build-error, but it should be a feature request.

**Comment by adamjstewart** [comment]
`spack configure` is now deprecated. The requested feature is now available through:
```console
$ spack install --test=root --until=configure foo
```
