### ISSUE TITLE
spack checksum not properly handling list_url

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#11680]
I just noticed that `spack checksum` doesn't work for certain packages like `poppler` that have a `list_url`.

### Steps to reproduce the issue

```console
$ spack checksum poppler
==> Found 76 versions of poppler:
  
  0.77.0  https://poppler.freedesktop.org/releases.html/poppler-0.77.0.tar.xz
  0.76.1  https://poppler.freedesktop.org/releases.html/poppler-0.76.1.tar.xz
  0.76.0  https://poppler.freedesktop.org/releases.html/poppler-0.76.0.tar.xz
  0.75.0  https://poppler.freedesktop.org/releases.html/poppler-0.75.0.tar.xz
  0.74.0  https://poppler.freedesktop.org/releases.html/poppler-0.74.0.tar.xz
  0.73.0  https://poppler.freedesktop.org/releases.html/poppler-0.73.0.tar.xz
  0.72.0  https://poppler.freedesktop.org/releases.html/poppler-0.72.0.tar.xz
  0.71.0  https://poppler.freedesktop.org/releases.html/poppler-0.71.0.tar.xz
  0.70.1  https://poppler.freedesktop.org/releases.html/poppler-0.70.1.tar.xz
  ...
  0.23.0  https://poppler.freedesktop.org/releases.html/poppler-0.23.0.tar.xz

==> How many would you like to checksum? (default is 1, q to abort) 
```

### Error Message

```console
==> Downloading...
==> Fetching https://poppler.freedesktop.org/releases.html/poppler-0.77.0.tar.xz
##O=#    #                                                                                                                                                   
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://poppler.freedesktop.org/releases.html/poppler-0.77.0.tar.xz failed.
==> Something failed on https://poppler.freedesktop.org/releases.html/poppler-0.77.0.tar.xz, skipping.
    (All fetchers failed for spack-stage-77z28pzw)
==> Error: Could not fetch any versions for poppler
```

The issue is that although https://poppler.freedesktop.org/releases.html lists the available tarballs for `poppler`, it is not the root where these tarballs can be found. The actual tarballs are available at https://poppler.freedesktop.org/poppler-0.77.0.tar.xz

**Comment by adamjstewart** [comment]
It looks like this bug only affects `list_url` that end with `.html`. This bug was introduced in #8429. PR incoming.

**Comment by birnbera** [comment]
I'm seeing a problem for CRAN packages related to this issue. For some reason, CRAN maintains two separate download links for source tarballs: one for the newest release and another for older releases. For example, the latest `devtools` is `2.3.2`, which can be accessed from the url `https://cran.r-project.org/src/contrib/devtools_2.3.2.tar.gz`. However, for versions `2.3.1` and earlier, you have to look in `https://cran.r-project.org/src/contrib/Archive/devtools/devtools_<version>.tar.gz`. Whenever `2.3.3` gets released `2.3.2` will be moved to the archive and only the latest version will be available at the url `https://cran.r-project.org/src/contrib/devtools_<version>.tar.gz`. CRAN does not keep a copy of the latest release under the archive url.

This way of organizing releases prevents `spack checksum` from being able to add new versions since it tries to use the `url` class variable to construct the path to the new version, which won't be valid for any versions but the most recent. For example:

```console
$ spack checksum r-devtools 2.3.1
==> Found 1 version of r-devtools:
  
  2.3.1  https://cloud.r-project.org/src/contrib/devtools_2.3.1.tar.gz

==> Something failed on https://cloud.r-project.org/src/contrib/devtools_2.3.1.tar.gz, skipping.  (All fetchers failed)
==> Error: Could not fetch any versions for r-devtools
```

This fails since `2.3.1` is not the latest version. Curiously, however, asking `spack` to list the available versions does work because it consults `list_url` to find all available versions:

```console
$ spack checksum r-devtools
==> Found 43 versions of r-devtools:
  
  2.3.2   https://cloud.r-project.org/src/contrib/devtools_2.3.2.tar.gz
  2.3.1   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.3.1.tar.gz
  2.3.0   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.3.0.tar.gz
  2.2.2   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.2.2.tar.gz
  2.2.1   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.2.1.tar.gz
  2.2.0   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.2.0.tar.gz
  2.1.0   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.1.0.tar.gz
  2.0.2   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.0.2.tar.gz
  2.0.1   https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.0.1.tar.gz
  ...
  0.1     https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_0.1.tar.gz

==> How many would you like to checksum? (default is 1, q to abort)
```

This issue doesn't seem to have to do with the trailing slash discussed in the linked PR.

**Comment by adamjstewart** [comment]
@glennpj thoughts on this? We could change `spack checksum` to scrape before downloading, although it will be much slower.

**Comment by glennpj** [comment]
Sorry for the late reply. I have not looked at the code recently but I seem to remember that `fetch` and `checksum` were separate code paths. As far as I can tell, `fetch` handles this properly. Could `checksum` do the same as `fetch`, which I guess is trying `list_url` if `url` fails. Since `checksum` works when a specific version is not specified, it may be just telling it to do the same thing when a version is specified. Currently, it seems like it is only trying `url`.

**Comment by glennpj** [comment]
This would not be unique to CRAN packages, although they probably make up the bulk of packages that use `list_url`.

**Comment by alalazo** [comment]
Still present in 

* **Spack:** 0.21.0.dev0 (bd2f78ae9a0a27a72e4476c08e2587262e8d8efd)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo


```console
(tmp.K0Ij4frlrp) culpo@nivola:/tmp/encoding$ spack checksum r-devtools 2.3.1
==> Found 1 version of r-devtools:
  
  2.3.1  https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.3.1.tar.gz

==> Something failed on https://cloud.r-project.org/src/contrib/Archive/devtools/devtools_2.3.1.tar.gz, skipping.  (All fetchers failed for spack-stage-o19o9rj1)
==> Error: Could not fetch any versions for r-devtools
```

**Comment by adamjstewart** [comment]
@tldahlgren has worked on fixing bugs like this before.

**Comment by adamjstewart** [comment]
Pretty sure @haampie fixed this recently.
