### ISSUE TITLE
filesystem views don't currently work with activated extensions

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#11698]
It would be nice if filesystem views worked with activated python extensions. Currently this error results from trying to create a view when an extensions is activated:

==> Error: Globally activated extensions cannot be used in conjunction with filesystem views. Please deactivate the following specs: 

One example where we need this is with the STAT package. It requires the py-xdot extension for Python.

**Comment by scheibelp** [comment]
It turns out that STAT includes a script which calls python and is configured to explicitly refer to the install prefix of the Spack-installed python. The filesystem view logic generally arranges for `PythonPackage` Packages to automatically relocate their scripts to use the Python instance that is relocated to the view, but since STAT is not a `PythonPackage` this does not occur. It then fails to run because a required dependency (`py-xdot`) is not available in the Spack install prefix of Python.

I can look into this more on 6/17

**Comment by becker33** [comment]
If you put py-xdot in the view, it should behave as if activated when using that view.

**Comment by lee218llnl** [comment]
I tried adding py-xdot to my singleton_packages and it still doesn't show up in my python environment. I don't see it in my  projection either:

    - combinatorial_packages: [netcdf^mpi, fftw^mpi, petsc^mpi, mpip^mpi] 
    - singleton_packages: [emacs, cmake, stat^boost@1.69.0^mvapich2@2.3.1, valgrind,
        git, git-lfs, cuda, spindle, netcdf-fortran, py-xdot]

  view:
    default:
      exclude: [^openmpi] 
      root: /usr/workspace/lee218/delete/usr/tce2
      projections: {}
      select: ['%gcc@4.9.3]

[lee218@rzwiz2:delete]$ ls usr/tce2/packages/
cmake  emacs  gcc  git-lfs  mvapich2  netcdf-fortran  petsc   spindle  valgrind
cuda   fftw   git  mpip     netcdf    openmpi         python  stat

**Comment by tgamblin** [comment]
@becker33: is this one resolved with the various view fixes in 0.13.0?

**Comment by becker33** [comment]
No, I don't believe so.

**Comment by scheibelp** [comment]
This can most-likely be resolved by adding a special implementation of `add_files_to_view` to the `stat` package. I'll be able to submit a PR for that next week (2/19)

**Comment by tgamblin** [comment]
Closing as activation is deprecated and will be removed in 0.19 in favor of #29336.
