### ISSUE TITLE
spack versions and spack checksum only using list_url

### ISSUE THREAD

**Issue by glennpj** [spack/spack#12020]
I noticed that when looking for updates to R CRAN packages, which have a `url` and a `list_url` setting, that `spack versions/checksum` will only use the `list_url`. The expected, or preferred, behavior is to use both the parent directory of the file in the `url` *and* `list_url`.

### Steps to reproduce the issue

```console
$ spack versions r-broom
==> Safe versions (already checksummed):
  0.5.1  0.4.2
==> Remote versions (not yet checksummed):
  0.5.0  0.4.5  0.4.4  0.4.3  0.4.1  0.4.0  0.3.7  0.3.6  0.3.5  0.3.4
...
```
The current version on CRAN is actually 0.5.2 but that does not show up. That version would be in the parent directory of the file in `url` and not where `list_url` points to.

Both the parent directory of the file in `url` and `list_url` should be used. Alternatively, allow `list_url` to have multiple entries. 

A workaround for R CRAN packages would be to make the root of `list_url` higher up to catch everything but that will mean more spidering.

**Comment by adamjstewart** [comment]
So the issue here is that Spack is trying to be too smart. `spack.cmd.versions` calls `spack.package.fetch_remote_versions`, which calls `spack.util.web.find_versions_of_archive`, which calls `spack.url.find_list_url` on the package's `url` attribute. Normally, this function simply returns the `dirname` of the URL, as you would expect. However, since Spack knows that this URL belongs to CRAN, it instead returns the Archive URL.

The simplest fix would be to return both the Archive URL _and_ the `dirname` of the URL. I'll have to make sure this change doesn't break anything else.
