### ISSUE TITLE
spack creates app directory with permissions of 777

### ISSUE THREAD

**Issue by glennpj** [spack/spack#12102]
A fresh clone of spack is creating the install directory with permissions of 777. This began with commit 3a026f14123e8a010e0c969bb38dfdde2738226f, #11995. These are bad permissions, particularly when deploying a stack on a system.

With the following config:

```yaml
config:
  build_stage: /dev/shm
  misc_cache: $spack/var/spack/cache
  install_tree: $spack/../apps
```
an installation will create directories as follows:
```console
$ ls -l ../apps/                                                                        
total 0
drwxrwxrwx 3 gpjohnsn its-rs-user 31 Jul 23 15:12 linux-centos7-x86_64
$ ls -l ../apps/linux-centos7-x86_64/
total 0
drwxrwxrwx 3 gpjohnsn its-rs-user 66 Jul 23 15:12 gcc-4.8.5
```

The expected behavior is:
```console
$ ls -l ../apps/                                                                            
total 0
drwxr-xr-x 3 gpjohnsn its-rs-user 31 Jul 23 15:11 linux-centos7-x86_64
$ ls -l ../apps/                                                                            
total 0
drwxr-xr-x 3 gpjohnsn its-rs-user 31 Jul 23 15:11 linux-centos7-x86_64/gcc-4.8.5
```

**Comment by alalazo** [comment]
It seems this change was deliberate and documented in code:

https://github.com/spack/spack/blob/3a026f14123e8a010e0c969bb38dfdde2738226f/lib/spack/spack/directory_layout.py#L258-L269

On the other hand I don't see why 777 should be the only viable solution to #11240

@albestro ?

**Comment by glennpj** [comment]
As a system administrator, I do not want everyone to be able to write to those directories. I would want to control the group ownership of the parent directory, as well as the intermediate directories, so that only members of a "spack" group could write to them.

Also, the 777 permissions would allow everyone on the system the ability to remove package directories.

```console
$ rm -rf /some/path/linux-centos7-x86_64/gcc-4.8.5
```

would succeed for everyone.

**Comment by albestro** [comment]
I understand your concerns, the decision was taken thinking of using the `install_tree` directory as a chokepoint, but maybe something better can be done.

In fact, what I do is to completely restrict access for `install_tree` to `others`, but this make me think:
- since `others` does not have neither `r-x` access to the `install_tree`, there should be no reason to set `rwx` for them on nested folders;
- completely restricting access to the `install_tree` for `others`, means that they are not able to install packages, but also that they cannot use installed packages (in general, I think it is interesting to have this option!)

In order to model the problem, I think that we can identify:
- Spack users: generally, who can manage packages;
- Passive users: they can not manage packages, but they can use them (accordingly to specific package restrictions);
- Restricted users: users that cannot use packages at all (e.g. they cannot even list them);

And what has to be considered is:
- Spack users must have `rwx` access to `install_tree` and `intermediate folders` in order to be able to install packages, otherwise we fall into the problem of not being able to install packages because `intermediate folders` belong to the user who created them;
- Passive users should not have write permissions on `install_tree` and `intermediate folders`, but they should have `r-x` permissions in order to be able to list packages directories;
- Then at package level there is the final access control: packages can have their specific permissions (this can be controlled from the configuration in `packages.yaml`), but their default permissions should respect the categorization of users above.

I'm thinking that setting permissions for `install_tree` and `intermediate folders` is case-specific; one of the target of the PR was to try not adding a configuration for this (@becker33), but I think that it may be the case.

In fact, at this point it seems that there is no general permissions that can be used to address all cases. In a group-instance I may want to have `other` as "passive users", but same concepts can be applied in a single-user instance where also group members have to be "passive users".

Looking forward to hear your thoughts.

**Comment by becker33** [comment]
@glennpj @albestro @alalazo 

What do you think of setting the intermediate directories to the same permissions as `config:install_tree`? I think that should be easily doable with the functionality that @albestro put in place.

I think in most cases, the `install_tree` folder should provide the necessary chokepoint to avoid the problems that @glennpj was discussing, but I don't think we considered the case where `install_tree` does not yet exist when implementing #11995.

**Comment by glennpj** [comment]
I think there needs to be an expectation that the `install_tree` ownership and permissions need to be managed outside of spack, even if spack creates the directory, unless there are configure options. If spack creates `install_tree` then the current default of 755 is fairly sane. I assume that those permissions are set explicitly and not dependent on the umask value. That is not an ideal value for a group of people who will install spack packages but that is easily changed.

I do like the idea of having the intermediate directories use the same permissions as `install_tree` if it exists. I would also add that it would be nice if the group ownership of an existing `install_tree` were used as well. Again, if spack creates that directory it will not know the desired group ownership so it would be up to the admin/user to change that at some point. Ideally, one will know where spack packages will be installed and set up `install_tree` ownership and permissions before deploying.

**Comment by becker33** [comment]
Re group ownership: We should probably only respect the group ownership of `install_tree` for the intermediate directories if the group ownership differs from the user ownership, because if someone (intentionally) has a world writable Spack we could have a shared Spack instance with install tree group ownership tied to an individual, so other users wouldn't have permissions to match the group ownership if they were creating the intermediate directories.

I think we should probably add a configuration option for `install_tree` permissions (`readable`, `writable`, `group` with defaults `world`, `group`, `None` respectively. 

Alternatively, the `install_tree` permissions could be the `all` permissions for packages. The more I think about it the more that makes sense, but it does have the possible downside that it would not be possible to user package-specific configurations to make a more permissive package than the `all` package defaults.

We could then apply the `install_tree` permissions to both `install_tree` and all intermediate directories.

**Comment by albestro** [comment]
I agree with you about having intermediate directories with `install_tree` permissions, it sounds ok: 

- it acts as chokepoint allowing to install packages to everyone whose access to `install_tree` is granted,
- and at the same time, in case a particular package has its specific permissions, by not restricting permission for intermediate folders it will allow any spack user to install other packages for the same arch/compiler configuration.

Moreover, as @becker33 is proposing, the configuration section for `install_tree` can be avoided using the `package:all` one, which IMHO is pretty much the same thing conceptually. I think that sysadmins have full control of the `install_tree` with this solution, not requiring them to change permissions by hand.

**Comment by fgava90** [comment]
Quite an old one, but i'm seeying the same behaviour for environments paths.
The environment folder is created with `pathlib.Path().mkdir()` which by default uses `mode=0o777`, anything inside inherits the same permissions.
Files are symlinked/hardlinked/copied from the install_tree which have the correct permissions, but this doesn't stop users from adding stuff into environments (a user running `pip install` will add stuff into a python environment for example).
It would be great if environments would also respect the `packages:all:permissions` config, or if they could be given a custom config
