### ISSUE TITLE
spack syntax help

### ISSUE THREAD

**Issue by balay** [spack/spack#12286]
I need help with spack syntax.

I'd like to do something like the following in 'class Xsdk(Package):' This way - I don't multiply lines of code for each conditional.

Is it possible to have such conditional (on a variant declared in the same class )- and if so - what would be the appropriate syntax?

Thanks,
```
-    depends_on('petsc@develop+trilinos+mpi+hypre+superlu-dist+metis+hdf5~mumps+double~int64',
+    petsc_trilinos='+trilinos' if '+trilinos' in self.spec else '~trilinos'
+    depends_on('petsc@develop+mpi+hypre+superlu-dist+metis+hdf5~mumps+double~int64'+petsc_trilinos,
                when='@develop')
```
The above code gives:
```
[balay@pj01 spack]$ spack spec xsdk
Input spec
--------------------------------
xsdk

Concretized
--------------------------------
==> Error: name 'self' is not defined
[balay@pj01 spack]$ 

```

**Comment by davydden** [comment]
@balay I am not associated with the university anymore and unfortunately have very limited amount of time to dedicate to open source projects these days ;-(

**Comment by mwkrentel** [comment]
@balay I'm not sure of exactly how you want to generalize the example
above, so this may or may not be useful.  But here are two
suggestions.

First, as you've discovered, the following attempt is not allowed in
the top-level code in the package class.  This is because the spec
isn't known at that time.  (You can use `self.spec` in an `install()`
or other method that knows self.)

```
petsc_trilinos='+trilinos' if '+trilinos' in self.spec else '~trilinos'
```

But you can refer to the spec inside `when()`.

```
depends_on('petsc@develop+... +trilinos', when='@develop +trilinos')
depends_on('petsc@develop+... ~trilinos', when='@develop ~trilinos')
```

Better still, you can write the depends in pieces.

```
depends_on('petsc +trilinos', when='+trilinos')
depends_on('petsc ~trilinos', when='~trilinos')
depends_on('petsc@develop+...', when='@develop')
depends_on('petsc@3.10.3+...',  when='@0.4.0')
...
```

By writing the depends in pieces like this, spack is required to
satisfy all the requirements that match `when()`.  This is legal as
long as it's possible to simultaneously satisfy all the requirements
that match.

This may be a better way to replace the `petsc_trilinos` variable
above.  Experiment!

**Comment by balay** [comment]
@mwkrentel Thanks! this works. (the second suggestion)
