### ISSUE TITLE
qt build fails during spack install py-pyqt4

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#12488]
Spack fails to build qt during a "spack install py-pyqt4" attempt. This was brought up in https://github.com/spack/spack/pull/12479. Note that I incorrectly said in that PR that it was py-pyqt5 I was trying to build, but in fact it is py-pyqt4 that fails for me. The build log is attached.

[spack-build-out.txt](https://github.com/spack/spack/files/3522345/spack-build-out.txt)

@Sinan81 it sounds like you know how to fix this.

**Comment by Sinan81** [comment]
I've been a bit busy this week, will definitely look into this early next as it is also related to a PR that I'm working on (#12338)

**Comment by Sinan81** [comment]
The apparent cause of this problem is that in pyqt4, qt dependency is indicated to be built with phonon variant:
```
...
depends_on(qt@4: +phonon+dbus)
...
```
Note however that in py-pyqt5, the only required variant is opengl:
```
...
depends_on(qt@4: +opengl)
```
If I understand correctly, [phonon provides audio and video playback support](https://www.riverbankcomputing.com/static/Docs/PyQt4/phonon-module.html#details): if those aren't needed, then one can eliminate this option, and qt4 & py-pyqt4 will build just fine.

**Comment by Sinan81** [comment]
Just to be clear, qt@5.11.3 builds just fine with +phonon variant.

**Comment by Sinan81** [comment]
Looking at "spack-build-out.txt", there are two sets of fatal errors are:
ones associated with +sql variant
```
$ grep 'fatal error' junk
db2.cpp:42:10: fatal error: sqlcli.h: No such file or directory
ibase.cpp:42:10: fatal error: ibase.h: No such file or directory
oci.cpp:42:10: fatal error: oci.h: No such file or directory
sqlite2.cpp:42:10: fatal error: sqlite.h: No such file or directory
```
and the one associated with phonon-backend "gstreamer"
```
gstreamer.cpp:42:10: fatal error: gst/gst.h: No such file or directory
```
The fatal errors associated with `+sql` variant is very strange because this variant is enabled regardless `+phonon` or not and qt builds just fine in that case. Somehow it seems enabling phonon variant is causing an interference.

**Comment by Sinan81** [comment]
Above PR fixes this problem, by disabling phonon backend gstreamer.

Another solution to this problem could be to pass '-continue' option to configure so that it wouldn't stop at the step where it is checking gstreamer plugins.

**Comment by lee218llnl** [comment]
#12579 has been merged. Thanks.
