### ISSUE TITLE
Unable to `spack load` packages in Spack Docker container

### ISSUE THREAD

**Issue by RemiLehe** [spack/spack#12636]
I recently downloaded and booted into one of the Spack Docker container (`spack/ubuntu-xenial`), but was then unable to execute `spack load` commands.

### Steps to reproduce the issue

```console
$ docker run -it spack/ubuntu-xenial
$ spack install tar ; spack load tar
...
```

### Error Message

```
Lmod Warning: MODULEPATH is undefined


Lmod has detected the following error: 
The following module(s) are unknown: "tar-1.31-gcc-5.4.0-jmhypcl"

   Please check the spelling or version number. Also try "module spider ..."
```

### Information on your system

This was tried on ubuntu 16.04, with Docker version 18.03.0-ce, build 0520e24.

**Comment by opadron** [comment]
Ok, so while looking into this issue, I started reworking how the various shell scripts in the docker images work on startup, to both address this issue as well as to provide downstream images that might want to build spack packages a cleaner way to handle starting up and shutting down the ssh server for MPI applications.  To be clear, I still think that work is worthwhile.

However, after doing much of the above heavy-lifting, I realized that this issue might not even be related to the docker image's scripts.

```
 $ docker run --rm -v "$( readlink -e ./spack_root2 ):/spack_root2" -it spack/centos7
```
```
 $ spack install zlib
 $ spack load zlib
```
```
...
Lmod has detected the following error:  The following module(s) are unknown:
"zlib-1.2.11-gcc-4.8.5-64vg6e4"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "zlib-1.2.11-gcc-4.8.5-64vg6e4"

Also make sure that all modulefiles written in TCL start with the string #%Module
```

Ok, so far so good.

```
 $ cp -r /opt/spack /spack_root2
 $ exit
```
```
 $ docker run --rm -v "$( readlink -e ./spack_root2/spack ):/opt/spack" -it spack/centos7
```

Now, I'm starting up an identical environment, except zlib is already installed.

```
 $ spack load zlib # works fine
 $ spack find
```
```
==> 1 installed package
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
zlib@1.2.11
```

It looks like when sourcing `$SPACK_ROOT/share/spack/setup-env.sh` with no packages installed, spack does not append any entries to `MODULEPATH`.  But when you install a package, and thus create the `linux-centos7-x86_64 / gcc@4.8.5` group, there is *still* no new entry added, and I think it should be.

**Comment by opadron** [comment]
Just in case it's not clear from my above findings:

I don't think this is-, or should be considered-, an issue with the docker images; but an oversight in spack that users run into when starting from a completely fresh installation.  It's just that running a new container is a pretty common way to create the circumstances needed to observe this issue.

**Comment by ax3l** [comment]
Ok, so this is a general spack issue and we could work-around it by installing some small package in the docker images by default, e.g. `tar`.

**Comment by opadron** [comment]
Depending on how much we want to reuse Spack packages (as opposed to OS-specific packages), it might make sense to take such a change to it's logical conclusion and bootstrap everything Spack needs, only installing what's absolutely necessary from the OS.

**Comment by ax3l** [comment]
Yes, good idea. Just `build-essential ca-certificates coreutils curl git python unzip` and `spack bootstrap` :)

**Comment by ax3l** [comment]
@opadron any chance we can get this fixed?

**Comment by ax3l** [comment]
@adamjstewart mentioned that `spack load` might potentially work soon without having to install `environment-modules`, if I understood correctly.

**Comment by adamjstewart** [comment]
> @adamjstewart mentioned that spack load might potentially work soon without having to install environment-modules, if I understood correctly.

@becker33 is working on this!

**Comment by opadron** [comment]
I've been hacking away at the docker containers and have learned more about the problem.

When installing a package using `spack install`

 1. The package being installed has some `target` (e.g.: `linux-centos7-x86_64`)
 1. The package being installed has some compiler spec (e.g.: `gcc@4.8.5`)
 1. The above two features are combined to identify a unique group of modulefiles (e.g.: `linux-centos7-x86_64 / gcc@4.8.5`).
 1. There is some module root under which Spack is configured to put generated modulefiles.  Directories within this root are created for each unique modulefile group.
 1. If the package being installed using `spack install` is the first such package whose generated modulefile belongs to a particular modulefile group under a given module root, then you will run into this issue.
 1. In the above case, Spack will create a new directory under which it will place a generated modulefile, but will not do anything further to add this new directory to the `MODULEPATH`.  So, for the current shell session, `spack load xyz` would fail for any `xyz` with a modulefile group that was created as a side effect of a `spack install` executed in the same shell session.  A similar, though less disruptive, issue arrises when `spack uninstall`-ing the last packages in a particular modulefile group, where its corresponding entry in `MODULEPATH` should be removed, but is not.
 1. Once `setup-env.sh` is sourced anew, Spack reevaluates `MODULEPATH`, and the problem goes away, until another modulefile group is created/emptied.

I think the best way to address this issue is to factor out the shell logic that evaluates `MODULEPATH` and rerun that logic after every Spack command that alters the set of installed packages:

 - `install`
 - `uninstall`
 - `buildcache install`

...are some of the commands I can recall off the top of my head, but there are surely others.

If reevaluating `MODULEPATH` isn't too expensive, perhaps it can be done after *every* Spack command?

**Comment by alalazo** [comment]
This is not an issue anymore since #14062 has been merged:
```console
$ docker run -it --rm spack/ubuntu-xenial
[ ... ]
[ubuntu] ~: spack install tar
==> 1561: Installing libiconv
==> Fetching https://ftpmirror.gnu.org/libiconv/libiconv-1.16.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/root/spack-stage/spack-stage-libiconv-1.16-2lu3ocrr3xhmxxowxsuglfwtzhhjcwnr/libiconv-1.16.tar.gz
==> Created stage in /tmp/root/spack-stage/spack-stage-libiconv-1.16-2lu3ocrr3xhmxxowxsuglfwtzhhjcwnr
==> No patches needed for libiconv
==> 1561: libiconv: Building libiconv [AutotoolsPackage]
==> 1561: libiconv: Executing phase: 'autoreconf'
==> 1561: libiconv: Executing phase: 'configure'
==> 1561: libiconv: Executing phase: 'build'
==> 1561: libiconv: Executing phase: 'install'
==> 1561: libiconv: Successfully installed libiconv
  Fetch: 5.08s.  Build: 28.92s.  Total: 33.99s.
[+] /opt/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/libiconv-1.16-2lu3ocrr3xhmxxowxsuglfwtzhhjcwnr
==> 1561: Installing tar
==> Fetching https://ftpmirror.gnu.org/tar/tar-1.32.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/root/spack-stage/spack-stage-tar-1.32-2v3uqlvm2h76wdene2wp7ctticzrgm3z/tar-1.32.tar.gz
==> Created stage in /tmp/root/spack-stage/spack-stage-tar-1.32-2v3uqlvm2h76wdene2wp7ctticzrgm3z
==> No patches needed for tar
==> 1561: tar: Building tar [AutotoolsPackage]
==> 1561: tar: Executing phase: 'autoreconf'
==> 1561: tar: Executing phase: 'configure'
==> 1561: tar: Executing phase: 'build'
==> 1561: tar: Executing phase: 'install'
==> 1561: tar: Successfully installed tar
  Fetch: 3.72s.  Build: 59.71s.  Total: 1m 3.43s.
[+] /opt/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-5.4.0/tar-1.32-2v3uqlvm2h76wdene2wp7ctticzrgm3z
[ubuntu] ~: spack load tar
```
Closing the issue, but feel free to reopen if anything is still missing.
