### ISSUE TITLE
Packages use non-portable option "rpath="

### ISSUE THREAD

**Issue by jppelteret** [spack/spack#1272]
With reference to [this post](https://groups.google.com/forum/#!topic/spack/ApYlJKYAPJU), the following packages (`grep -Ril "rpath=" .`) use the string `rpath=%s` to adjust their configuration:
- ./builtin/packages/metis/package.py
- ./builtin/packages/py-numpy/package.py
- ./builtin/packages/py-pyside/package.py
- ./builtin/packages/py-shiboken/package.py

Unfortunately this is not portable as it doesn't work on OSX which expects `rpath %s`.

**Comment by tgamblin** [comment]
Since #4692, the compiler wrappers actually parse `rpath` arguments out of compile lines and substitute them with compiler-specific (and likely more portable) `-Wl,-rpath,...`  and `-rpath ...`.  So this should not be an issue -- if Spack sees `-rpath=`,  it actually replaces it with a version with spaces, even if it comes from the build.
