### ISSUE TITLE
`spack create` should put downloaded packages into cache

### ISSUE THREAD

**Issue by eschnett** [spack/spack#1283]
`spack create` downloads package tarballs to calculate their checksums. These packages should be put into the cache.

**Comment by tgamblin** [comment]
@scheibelp: can you look at this one?

**Comment by scheibelp** [comment]
will do (I should get a chance to look at this later today)

**Comment by scheibelp** [comment]
I should have a PR before Wednesday on this

This occurs now because the cache expects package details which are not necessarily known during the lifetime of stages that are created as part of downloading archive files to create checksums; specifically this is an issue for packages that are being created as their name is not known when the archives are downloaded. i.e. checksum.get_checksums does not (yet) have easy access to details it requires to store resources in the cache.

**Comment by scheibelp** [comment]
A PR for this is delayed pending resolution of https://github.com/LLNL/spack/issues/1308 (a bug related to caching). This should not be delayed more than a few days.

**Comment by tgamblin** [comment]
Can't find the PR where this was fixed, but it's fixed in `develop`.  `spack fetch <spec>` results in `spec`'s downloads being cached.
