### ISSUE TITLE
better way to add unit tests to packages that implement virtual packages

### ISSUE THREAD

**Issue by davydden** [spack/spack#1296]
as per comment https://github.com/LLNL/spack/pull/1243#issuecomment-233552475 , figure out a better way to add Blas/Lapack tests to packages which would require less amount of code in `package.py` and avoid duplication. 

One way i see is to introduce a dummy package `test-blas.py` and `test-lapack.py` which would `depends_on('blas')` and `depends_on('lapack')`. We would then be able to build them against any package which implements blas/lapack and test if the interface is working and correct.

Even better would be to have tests as a part of virtual package declaration somehow and then make them run by `spack test atlas/openblas/mkl` etc. So there will be one place where tests are defined and every package which implements a virtual package need to pass the test.

**Comment by davydden** [comment]
or have tests as a part of virtual package declaration somehow and them make them run by `spack test atlas/openblas/mkl` etc.

**Comment by alalazo** [comment]
At the moment this issue seems to be advocating for a way to:
1. Specify an API for a virtual package
2. Check that the API is implemented if a package `provides` the virtual

While this makes absolute sense, it might be more work than it is worth in practice. I'll be closing this as stale, but feel free to reopen if you want to continue the discussion.
