### ISSUE TITLE
Add microarchitecture specific flags for Intel compilers

### ISSUE THREAD

**Issue by alalazo** [spack/spack#13103]
As a user I want to have microarchitecture specific flags injected for Intel compilers so that I would compile by default code that is optimized for the target of the installation.

### Rationale

We already support this feature for GCC since #3206 and need to extend the capability to other compilers as well

### Description
What needs to be done is carefully reviewing docs and man pages, and encode in [this file](https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/cpu/microarchitectures.json) the information found.

### Additional information
A non exhaustive list of pages we might want to consult:

- [Intel C++ compiler Reference](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference)
- [Intel Fortran compiler Reference](https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference)
- auto-dispatch PR #11697

**Comment by glennpj** [comment]
Prior to #3206 I created the `auto_dispatch` variant, mostly to handle building fat binaries. If targets are implemented in the same way for Intel compilers as for GCC, one problem is that the "generic", ie., x86_64 target also injects compiler flags.
```
"x86_64": {
      "from": null,
      "vendor": "generic",
      "features": [],
      "compilers": {
        "gcc": [
          {
            "versions": "4.2.0:",
            "name": "x86-64",
            "flags": "-march={name} -mtune=generic"
          },
          {
            "versions": "4.0:4.1.2",
            "name": "x86-64",
            "flags": "-march={name} -mtune={name}"
          }
        ]
      }
    },
```
That would introduce potential conflicts with the `cpu_arch` variant. Would it be possible to have a setting that would turn off the target code so that no flags are automatically injected? Better yet, having the `cpu_arch` functionality taken over by the target code would be really nice. I think that would still require an extra option of whether to build fat binaries or not when using compilers such as Intel and PGI.

When I build something with GCC it is generally not performance critical so using `target=x86_64` is okay. For performance critical code I use the Intel compiler and build fat binaries so that they will run optimally on all of our node types.

**Comment by alalazo** [comment]
For reference @glennpj PR with `auto_dispatch` is #11697

**Comment by tgamblin** [comment]
@glennpj: 
> Would it be possible to have a setting that would turn off the target code so that no flags are automatically injected?

One of the goals with #3206 is to ensure that we *know* where we can run any particular Spack install.  We want to be able to distribute nearly anything we build as a binary, and specific targets was intended both to make it easier for folks to see/specify what arch to build for *and* to make it possible to determine where a binary package could be run.

If we turn off the target code (even in "generic" mode) and the build injects some flags, then we don't really know that anymore -- it's like doing `-march=native`.

> Better yet, having the cpu_arch functionality taken over by the target code would be really nice. I think that would still require an extra option of whether to build fat binaries or not when using compilers such as Intel and PGI.

I think this would be nice too.  It would be useful for a number of cases, though different compilers can be prickly about how they handle it, so it would be an extension to the `llnl.util.cpu` stuff we implemented.

> When I build something with GCC it is generally not performance critical so using target=x86_64 is okay. For performance critical code I use the Intel compiler and build fat binaries so that they will run optimally on all of our node types.

Our current recommendation is to build with the lowest common denominator, but I agree fat binaries would be better.  We've also run into situations where we want fat binaries for, e.g., cross-compiled builds -- they're handy because they actually run in the build environment.

is it just fat binary support that you need, or is there something else?

**Comment by glennpj** [comment]
@tgamblin I said target=x86_64 because I have a stack of software built prior to the target code landing. For gcc, yes, using the lowest common denominator is what I will do going forward. For Intel, we use fat binaries and that works well for the most part.

**Comment by glennpj** [comment]
@tgamblin After thinking about this a bit, it might make sense to remove the auto-dispatch variant, as it could cause confusion. Let me know if you agree and I will create a PR to do that.
