### ISSUE TITLE
Proposal: Spec Aliases to Handle Changing Hashes

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1338]
@adamjstewart @tgamblin @fgeorgatos @becker33 @eschnett @mwilliammyers @davydden @alalazo 

This is an alternate approach to many of the ideas suggested in #1325.  Those ideas are mainly focused on trying to avoid unnecessary rebuilds: seen as useful not just to conserve CPU cycles, but more importantly to avoid changing hashes.  While they may be useful, the ideas in #1325 are unlikely to really solve the problem because:
1. Too many cases where Spack can't guess what to do (i.e. what to do when a new variant is added).
2. Too many ways for a hash to change: addition of a variant, change way down in the DAG, etc.  Too hard for Spack to divine what to do in each case. 

The alternative presented here is to bury hashes under another layer of indirection, so the end user does not need to be aware (or care) when they change.  This approach requires the sysadmin to be a little more mindful in how they install software; but the benefit is it allows good control over when and how end-user visible package names change or don't change.  An added benefit is it eliminates hashes from end-user view.

So here goes...

Suppose I'm a supercomputer admin, and my job is to install/maintain a set of packages for users.  For each package that users want, I have a `spack install` command that installs it.  For example:

```
spack install zlib
spack install netcdf@4.1.1~hdf5
spack install ibmisc@0.1.2+python+netcdf ^netcdf-cxx4 ^netcdf+mpi ^eigen~suitesparse ^py-numpy+lapack ^openblas ^python@3:
```

Spack fully concretizes these specs, of course.  But _what the user typed_ (what I call the _user spec_ here) is important, since it gives clues about what the user does or does not care about.

My installation site will provide a function mapping the tuple (user spec, concretized spec) to a string.  This function is entirely arbitrary, for a given site.  For sites that want to install just one of every package@version, the function might strip out everything except a version number.  For things like `zlib` that have ultra-stable APIs where the user spec didn't specify a version, it might even strip out the version number.  For sites that need to install 24 different versions of OpenMPI for different compiler/architecture combos, the function would have to include details on the dependencies.  We  call this the _spec mapping function_ (SMF).

By running the SMF on each user spec above, we get a bunch of _short specs_, each mapping to the fully concretized spec (and also a hash code for that spec).  For example:

```
[Short Spec] --> [User Spec] --> [Concretized Spec] --> [hash]
-----------------------------------------------------------------
netcdf@4.1.1 --> netcdf@4.1.1~hdf5 --> netcdf@41.1......^...^..^... --> [hash1]
zlib --> zlib --> zlib@1.2.8 --> [hash2]
ibmisc@0.1.2 --> ibmisc@0.1.2+python+netcdf ^netcdf-cxx4 ^netcdf+mpi ^eigen~suitesparse ^py-numpy+lapack ^openblas ^python@3: --> ibmisc@0.1.2...^...^..^.. --> [hash3]
```

Note that changes in Spack can cause _both_ the hash _and_ the concretized spec to change.  They can also require that the user spec for a desired install must also change, in some cases.  In that rare case, I can maintain my spec mapping function, possibly with the aid of a lookup dict, to ensure that short specs never change.

The proposal is then to make a directory of symlinks named after short specs, which would link into the main Spack installation directories for the hashes associated with each short spec.  When Spack changes, I would do the following to ensure consistency in my short specs:
1. Review my user specs, make sure they don't require modification.
2. If any user specs do require modification, make sure that the SMF() of those specs remains constant.  If needed, modify my SMF to make it so (for example, by adding ad-hoc lookup-based exceptions to some general SMF rule).
3. Re-run `spack install` on all my short specs, creating a new directory of short spec symlinks.
4. When (3) is complete, replace the old short spec symlinks with the new one.  Or keep them all side-by-side for exact repeatability for end users.

This approach does not address potential issues of "unnecessary" Spack rebuilds.  A new Spack could still come with a new version of `zlib` and trigger a rebuild of everything. The assumption here is that CPU time is (relatively) cheap, and that keeping things consistent for end users is the most important.

The benefits of allowing Spack to rebuild when it wants are _repeatability_ and _correctness_:
1. The meaning of a user spec depends entirely on the spec itself and the version of Spack interpreting that spec; and NOTHING on whatever Spack happened to install in the past.
2. It allows multiple projects with conflicting requirements to better co-exist within one Spack tree (since project B won't get confused by project A's already-installed dependencies).
3. It ensure that software is always up-to-date, and that Spack doesn't "guess wrong" when it might decide that something doesn't need to be rebuilt after all --- avoiding a whole rats nest of virtual vs. actual version numbers we've proposed in the past.
4. It efficiently removes versions of packages that have been removed from Spack due to security concerns.  (No more need for warnings on OpenSSL versions).

@adamjstewart would this proposal help the issues you brought up in #1325?

**Comment by mwilliammyers** [comment]
@citibeth I like where you are going with this. Could this also be incorporated into the environment modules system? If I am understanding you correctly you are effectively taking the provides mechanism a little further and applying it to the concretization process. 

> The assumption here is that CPU time is (relatively) cheap, and that keeping things consistent for end users is the most important.

While I 100% agree as you say, *repeatability* and *correctness* are extremely important, I think (at least for me) #1325 is not about wasting CPU cycles but rather about maintainability. I don't care about the wasted CPU cycles or even the wall time it takes for it to build, because as you say, spack is automated. I care that I end up with a rat's nest of 500+ installed packages that becomes hard to maintain. At the end of the day I care most about my time and my user's time. If *repeatability* and *correctness*  are the the things that save my time the most then that is what we should focus on. If maintainability is the thing that saves us the most time then we should focus on. Personally I think both are worth focusing on. 

I would be happy if I could apply what you are saying here to environment modules (ie. the paths in the modulefiles point to your idea of symlinks instead of the hashed paths) so I don't end up with 500+ modules, one for each installed hash path (short of painstakingly maintaining a blacklist or whitelist of packages in my `modules.yaml`).

**Comment by citibeth** [comment]
> Could this also be incorporated into the environment modules system?

Yes, the idea is that environment module aliases would also be created, along the same line as the package directory aliases.  You would be able to load env modules by those aliases.

At the last telcon, we also discussed useful ways to tell Spack which of the 500+ installed packages you're interested in; and it can delete the rest.

**Comment by adamjstewart** [comment]
> what the user typed (what I call the user spec here) is important, since it gives clues about what the user does or does not care about.

I very much agree with this, but I think our opinions on implementation differ. In my idea, if I install `hdf`, I don't care what version of `zlib` is installed. If I install `hdf ^zlib@1.2.3`, then I do care, and Spack should rebuild `zlib` if `1.2.3` isn't already installed.

> My installation site will provide a function mapping the tuple (user spec, concretized spec) to a string. This function is entirely arbitrary, for a given site. For sites that want to install just one of every package@version, the function might strip out everything except a version number. For things like zlib that have ultra-stable APIs where the user spec didn't specify a version, it might even strip out the version number. For sites that need to install 24 different versions of OpenMPI for different compiler/architecture combos, the function would have to include details on the dependencies. We call this the spec mapping function (SMF).

I kind of understand where you're going with this? Are you proposing something like what currently exists for modules support, or something even more complex? When I first started using Spack, I was annoyed because I couldn't do this myself. For example, we used to install things with the following format:
```
/soft/$package/$version/$compiler-$compilerver/$mpi-$mpiver
```
But when I switched to Spack, I couldn't get that level of complexity. It's annoying to not be able to figure out what is installed by the installation directory, and when you have 24 versions of NetCDF compiled with each compiler, MPI, and IB fabric, you can only determine what is installed with `spack find`. Now that we plan on switching to modules, and now that I fully understand the modules support, I'm less concerned about this, but it is an interesting idea. It would be neat if we could use the exact same syntax (and even the same config option) to setup installation directories and module file directories.

The only thing I'm afraid of is that it might end up being a lot of work to explicitly declare exactly what you do and don't care about. And if you forget, hashes will again become necessary. This is why I would rather Spack just use whatever is already installed, unless explicitly told otherwise.

> While I 100% agree as you say, repeatability and correctness are extremely important, I think (at least for me) #1325 is not about wasting CPU cycles but rather about maintainability. I don't care about the wasted CPU cycles or even the wall time it takes for it to build, because as you say, spack is automated. I care that I end up with a rat's nest of 500+ installed packages that becomes hard to maintain. At the end of the day I care most about my time and my user's time.

Couldn't have said it better myself.

Overall, it's an interesting proposal. It doesn't solve everything I brought up in #1325, but it does solve some things I didn't bring up. #1325 was admittedly a bit radical, and provided more complaints than solutions. I'll be interested to see what other solutions people come up with.

**Comment by alalazo** [comment]
> Now that we plan on switching to modules, and now that I fully understand the modules support, I'm less concerned about this, but it is an interesting idea. It would be neat if we could use the exact same syntax (and even the same config option) to setup installation directories and module file directories.

I think we should really keep an eye on @scheibelp work for that. See #2168

**Comment by tgamblin** [comment]
> It would be neat if we could use the exact same syntax (and even the same config option) to setup installation directories and module file directories.

@adamjstewart: this is the idea!

**Comment by alalazo** [comment]
I think some of the points raised in the discussion above have been developed while working on other features (e.g. Spack environments are another layer on top of the store etc.). Other implementation details instead are now outdated. I'm closing this issue as it seems to have served its purposes, but feel free to open new ones if you think there are parts that have not been addressed and are still worth discussing.
