### ISSUE TITLE
spack arch return nephalem

### ISSUE THREAD

**Issue by nopech** [spack/spack#13440]
When I run "spack arch" it returns nephalem and not the expected x86_64 i'm used to. It used to return x86_64 but at some point it changed. This is on a Samsung notebook with a Intel I7 CPU. I have Ubuntu Mate 19.04 installed. Also tried Ubuntu Mate 18.04 with the same result.

When I ignore the fact that it's not x86_64 and continue to install packages such as cmake, the compilation will fail.
This all used to work. I even reinstalled the OS but the issue still exists.

I followed this page to install spack and packages:
https://spack.readthedocs.io/en/latest/getting_started.html

**Comment by tgamblin** [comment]
This is expected since #3206 was merged.  To better optimize for specific microarchitectures, and to let us eventually distribute optimized binaries, the default target in Spack is detected from `/proc/cpuinfo` and we add march/mcpu flags in the compiler wrappers.

If you don't want this (and you want generic x86_64 binaries), you can do this in `packages.yaml` or in an environment:

```yaml
packages:
    all:
        target: [x86_64]
```

That will make everything generic `x86_64`.
