### ISSUE TITLE
Spack ability to install or dev-build by git reference instead of version

### ISSUE THREAD

**Issue by mc-allen** [spack/spack#13528]
Provide the ability to specify a git reference in place of version for install, dev-build, build-env.

### Rationale

Particularly for cases of local development using spack dev-build, it is a heavy maintenance burden to have to include all possible branches and tags as spack versions. Many projects don't just use develop or master - git flow style development with feature branches is common. To solve this, the ability to specify a git reference in place of version would be great, for packages that have git sources.

Without this ability, only manually transcribed branches can be developed against, and branches with characters like "/" are not supported.

### Description

Something like spack dev-build my-package@git-ref:feature/foo. I don't know how else you deconflict with other arbitrary version names.

**Comment by tgamblin** [comment]
This is possible for raw git commits since v0.17 and for any git ref since v0.19.  See the release notes:
* https://github.com/spack/spack/releases/tag/v0.17.0
* https://github.com/spack/spack/releases/tag/v0.19.0

and the docs:
* https://spack.readthedocs.io/en/latest/basic_usage.html#version-specifier
