### ISSUE TITLE
How to prevent transitive dependencies from being added to include path?

### ISSUE THREAD

**Issue by bcdarwin** [spack/spack#1380]
I'm trying to build a package which depends on `octave`, which depends on `ncurses` (via `readline`).  However, including the `ncurses` header files apparently breaks compilation of my package ... what's the nicest way that these headers shouldn't be propagated?  (I'm thinking of something like Nix's `nativeBuildInputs, buildInputs, propagatedBuildInputs`).

**Comment by citibeth** [comment]
It all depends on the build system for the package you're using, and how it interacts with Spack.  In my experience with CMake, transitive dependencies are only included if you ask for them.

**Comment by tgamblin** [comment]
@citibeth: The compiler wrappers actually add `-I` and `-L` arguments for the transitive dependency DAG.  So, `ncurses` headers are included in case any of `readline`'s headers include them.

@bcdarwin: I'm curious why this is breaking.  What headers from `ncurses` are conflicting with your project's headers?  In a system install scenario, where both `ncurses` and `readline` headers are in, e.g., `/usr/include`, would you not get the same issue?

**Comment by bcdarwin** [comment]
The project I'm trying to compile declares a `menu.h`, but a file of the same name is also present in `ncurses`, although the `IFNDEF` macros they define are different, so at some point both are imported (likely one through another inclusion), causing an error as some symbols are now declared twice.

I'm not exactly sure yet why this is happening.  The overall project is `cmake`-based, and one of the subprojects is `autotools`-based, while the one conflicting with `ncurses` also uses `cmake`.  But I guess the reason this issue doesn't occur when compiling outside of Spack involves Spack's compiler wrappers adding their paths relatively late.

**Comment by tgamblin** [comment]
Currently the compiler wrapper puts its `-I` and `-L` parameters before those of the application but I suspect that's not really what we want to do.  If we put Spack's dependencies' includes and such *after* any supplied by the build system on the compile line (or if we moved the app's includes to be ahead of Spack's), we could avoid this.  Same for library paths.

@eschnett: this is actually how the compiler wrapper worked before some of your changes -- do you see any problems with adding the more specialized `-I` and `-L` handling back in so that a build's includes take precedence over its dependencies?

**Comment by eschnett** [comment]
@tgamblin Define "before" if a build script mixes `-I` options and source files. What we probably want is to put Spack's options just before the first source (or object) file.

What about setting environment variables instead? There are `C_INCLUDE_PATH` and friends, and `LIBRARY_PATH`. I assume all relevant compilers honour these? These paths are searched after all `-I` and `-L` options.

The libraries themselves can continue to be added at the very end.

**Comment by tgamblin** [comment]
@eschnett: I *believe* there are actually compilers (XL) that don't honor `LIBRARY_PATH` and `C_INCLUDE_PATH`, `CPATH`, etc.  The other issue with these is that CMake will misconstrue anything in `LIBRARY_PATH` as implicit compiler link path, and will screw up the `RPATH`s as a result.  I don't really trust these variables to be handled correctly by build systems. 

I like the idea of inserting before the first source file.  I am not sure I can come up with a reliable way to parse that out.  I guess we could process args until the first non `-I`/`-L`/other flag, and put Spack's `-I` and `-L` args just before.  Do you see issues with that?

**Comment by adamjstewart** [comment]
> I like the idea of inserting before the first source file. I am not sure I can come up with a reliable way to parse that out. I guess we could process args until the first non `-I`/`-L`/other flag, and put Spack's `-I` and `-L` args just before. Do you see issues with that?

How much would that parsing slow the build process down? The compiler wrappers get called a lot of times...

**Comment by tgamblin** [comment]
If it just looks at args, not much.  The original `cc` wrapper parsed out the `-I` and `-L` args and it was no problem, but there were ordering issues.  @eschnett's version just puts them first.  If the parser has to check whether a file exists to see if it's really a source file, it could be expensive because FS access is slow.

**Comment by eschnett** [comment]
Parsing is made non-trivial because certain flags can take arguments that need to be skipped. I used to know which these are. (Maybe `ILRlo`? There are probably a few more.) Then we insert our flags just before the first non-flag argument, as you suggest.

@adamjstewart If parsing slows us down then we can convert the Bash script to a C program. A quick run-time test tells us whether `cc` is usable for compiling (it will be most of the time), and if not, we fall back to the Bash script.

**Comment by adamjstewart** [comment]
> @adamjstewart If parsing slows us down then we can convert the Bash script to a C program. A quick run-time test tells us whether cc is usable for compiling (it will be most of the time), and if not, we fall back to the Bash script.

That would actually be kinda cool. I would be interested to see how much faster it runs, but I'm not super concerned. I'll let you guys handle this one however you want. Maybe it will even solve the problems I was having with NAG.

**Comment by xjrc** [comment]
I just wanted to note that a solution to this problem could help to solve a couple of recent problems with the `qt` package (see #1041 [(comment)](https://github.com/LLNL/spack/pull/1041#issuecomment-238363551) and #1455 [(comment)](https://github.com/LLNL/spack/pull/1455#issuecomment-239507716) for details).

**Comment by adamjstewart** [comment]
And #1517

**Comment by alalazo** [comment]
> I'm trying to build a package which depends on octave, which depends on ncurses (via readline). However, including the ncurses header files apparently breaks compilation of my package ... what's the nicest way that these headers shouldn't be propagated?

@tgamblin It's a bit that I would like to ask this : wouldn't it be logically more correct if the compiler wrapper enforced `-I` and `-L` only for direct dependencies ? What were the reasons to include all the transitive dependencies ?

**Comment by adamjstewart** [comment]
@alalazo I imagine that if you switched it to only direct dependencies, a lot of packages would break just because the installation instructions or package developers didn't realize that the dependency of the dependency was actually a direct dependency. But that could work.

**Comment by eschnett** [comment]
If package A depends on B, and B was installed in such a way to depend on C, then A implicitly depends on C: In many cases, B's installed header files will include header files from C. It is unreasonable to expect package A to always know about these details of package B.

For example, HDF5 can be installed with MPI support, and if so, HDF5's header files will include MPI header files. Should each package that uses HDF5 have to check whether HDF5 was installed `+mpi`, and if so, declare a dependency on `mpi` as well? Isn't this transitive dependency management exactly the problem that Spack is supposed to solve?

**Comment by alalazo** [comment]
> If package A depends on B, and B was installed in such a way to depend on C, then A implicitly depends on C: In many cases, B's installed header files will include header files from C. It is unreasonable to expect package A to always know about these details of package B.

I think that's where we disagree. In a case like this I would consider the dependency as explicit (i.e. direct, build-time dependency). After all you need an header in YOUR application / library at least for macro expansion and inclusion during the pre-processing phase.

> Should each package that uses HDF5 have to check whether HDF5 was installed +mpi, and if so, declare a dependency on mpi as well?

`mpi` is a very particular topic here. Usually it is handled via compiler wrappers so that you don't really need to know about the direct dependency on a library (in the same way you don't need to know about `-lstdc++` when you compile with `g++`).

> Isn't this transitive dependency management exactly the problem that Spack is supposed to solve?

Why not just *dependency management* ? The fact that the compiler wrappers within Spack add dependencies transitively it's for me just an implementation detail I was asking information about.

**Comment by eschnett** [comment]
@alalazo Okay, so you didn't like my HDF5 / MPI example. But the same problem exists for other packages, not just MPI. For example, a package might be using Boost constructs in its header files.

If you want to make this an explicit dependency, then what should happen if A doesn't declare its dependency on B? Build failures (with error messages that are difficult to interpret) are not a good error mode. For example, B might create a pkgconfig file declaring the header files and libraries that it uses, and will thus expect its users (i.e. package A) to automatically use the right include and library paths, so that package C is used automatically. A doesn't have to actively declare anything, it just picks up B's dependencies. That mode of operation is fairly standard.

**Comment by alalazo** [comment]
> Okay, so you didn't like my HDF5 / MPI example. But the same problem exists for other packages, not just MPI. For example, a package might be using Boost constructs in its header files.

Then if whatever uses the package needs to declare explicitly  `-I<prefix-to-boost>/include` (e.g. using `CPPFLAGS` or such) to compile then it *depends explicitly* on Boost. If the situation is like that I think it is logically more correct to have an edge in the DAG representing the explicit need of the `-I<something>`. Right now this is not necessary because everything is transitively included.

> ... That mode of operation is fairly standard. 

In this case A *doesn't explicitly depend* on C, because B took care to pass the information through some means (may be it a pkg-config file or a CMake exported target with public interfaces). And unfortunately, at least in my experience, that mode of operation is not as standard as it should be.

**Comment by eschnett** [comment]
@alalazo I'm saying that Spack should take care of this. In this scenario, we agree that A depends on C. It's an error to try and build A ignoring this dependency. So we can either
- require A's package maintainer to describe this explicitly
- have Spack deduce this dependency automatically

If this is described in A's package, then there are two error modes -- maybe B doesn't actually depend on C, but A erroneously thinks so; that would be a shame, as C is needlessly installed. Or A is unaware of B's dependency on C, leading to a build-time error. Furthermore, Spack has all the information it needs to prevent this problem -- it just needs to look at B's package description. So why should A's package maintainer need to second-guess B? This should really happen automatically.

**Comment by citibeth** [comment]
I think both sides here have valid points.  Why don't we allow the Spack package to declare whether it wants transitive dependencies?  Internally, Spack can make this happen in one of a few ways:

1. Include two compiler wrappers with Spack --- one that provides transitive dependencies and one that does not.

2. Have Spack generate a compiler wrapper (using templating) for each staging area it creates.  It can then customize those wrappers to respect the declared wishes of the package.

3. Have just one set of compiler wrappers, but use env vars to pass parameters from Spack to the wrappers.

The only question remaining is whether Spack should provide transitive dependencies by default.  For the sake of cleanliness, I think it probably should not.  But that change would require that we add the "I want transitive dependencies" added to all existing packages in the repo.  Not the end of the world, this would be easier than the `flake8` stuff.

**Comment by eschnett** [comment]
Isn't this what the different dependency types are about? If package C is a run-time (is that the right name?) dependency of B, then it needs to be included with B's include paths etc. If C is only a build-time dependency, then it shouldn't be included. Whether we're including C's libraries, C's library paths, or C's include paths when another package is using B are all different sides of the same coin. I don't think we need a new mechanism.

**Comment by tgamblin** [comment]
This was fixed by #4692.  The compiler wrappers now put package  include paths *before* dependency paths. 

RE: some of the other points here, ignoring transitive dependencies will likely cause *many* packages to behave incorrectly and bring in system headers when they shouldn't,  so we're unlikely to do that.
