### ISSUE TITLE
Lua Modules install path does not contain the correct arch

### ISSUE THREAD

**Issue by victorusu** [spack/spack#14098]
When using LMod backend, the install path of the modules does not contain the architecture of the machine, while it does for the TMod.

```
$ ml av

------------------------------------ /opt/apps/spack/share/spack/lmod/linux-ubuntu18.04-x86_64/Core ------------------------------------
   gcc/4.9.4    gcc/5.5.0    gcc/6.5.0    gcc/7.4.0    gcc/8.3.0    gcc/9.2.0 (D)

------------------------------------ /opt/apps/spack/share/spack/modules/linux-ubuntu18.04-skylake -------------------------------------
   gcc-7.4.0/gcc/4.9.4    gcc-7.4.0/gcc/5.5.0    gcc-7.4.0/gcc/6.5.0    gcc-7.4.0/gcc/7.4.0    gcc-7.4.0/gcc/8.3.0    gcc-7.4.0/gcc/9.2.0 (D)
```

Just to emphasize: the installation path for lua modules is
`/opt/apps/spack/share/spack/lmod/linux-ubuntu18.04-x86_64/Core`, while the `tcl` modules is `/opt/apps/spack/share/spack/modules/linux-ubuntu18.04-skylake`.

### Steps to reproduce the issue
```
spack module lmod refresh -y --delete-tree
spack module tcl refresh -y --delete-tree
```
You need to module use the `lmod` module path. The `tcl` one, at least for me, is added automatically by `. $SPACK_ROOT/share/spack/setup-env.sh`.

**Comment by alalazo** [comment]
Hi @victorusu This works as expected, see https://github.com/spack/spack/pull/13121. Is it causing any issue for you?

**Comment by victorusu** [comment]
@alalazo, I would not say it is causing issues, but on a hybrid system that use LMod, would be nice to `module use` the appropriate LMod folder based on the architecture of choice. Currently it is possible to do that using `tcl` modules, but I am not aware of a mechanism to do it for the `lua` modules. Is there anyway to get the folder similar to `lmod/linux-ubuntu18.04-skylake/` by setting an environment variable?

**Comment by alalazo** [comment]
@victorusu Since it is not causing issues I'll relabel this as a question. Also, to reply to:

> I would not say it is causing issues, but on a hybrid system that use LMod, would be nice to module use the appropriate LMod folder based on the architecture of choice.

`lmod` is different from `tcl` in that it generates a hierarchical layout of module files. Taking into account every case in which the users can mix and match software depending on the nodes they land on and the layout of files they have in mind for their site is a daunting task. 

The decision made in #13121 was to be backward compatible with what Spack was doing before #3206 for `lmod`: so basically we are flattening every target in its `target.family`. In this scenario you have two possibilities:

1. Either you use `suffixes` to add microarchitecture information to the modules
2. Or you generate modules for different architectures in different folders, for instance by using Spack environments

If you think about it, you'll be forced to using suffixes anyhow since if you generate module files for `foo@X.Y target=skylake` and `foo@X.Y target=haswell` they'll both be imported as `foo/X.Y` in the current module view with the default naming scheme and you have no way of selecting among them.

**Comment by victorusu** [comment]
@alalazo, I was not aware of the #13121 and #3206 issues... Thanks!

**Comment by behrmann** [comment]
@alalazo I recently ran into this issue as well, since I want to serve a small fleet of desktops with different microarchitectures from a single spack installation on a NFS share (and `MODULEPATH` set automatically to the directory for the right microarchitecture and only allowing choosing modules from there, i.e. making that the top-level of the hierarchy). Since all microarchitectures are folded into their family, it becomes a bit more difficult to hide modules for packages built for other microarchitecture targets from each other. Would the spack team be open to making this folding configurable or am I off for planning to serve different microarchitectures from the same spack installation, when I don't intend to share packages between them?
