### ISSUE TITLE
spack gc: remove packages not used by an environment

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#14695]
I would like `spack gc` to have the additional functionality that would allow it to uninstall all packages that are not currently activated by some environment.

### Rationale

I use Spack as a replacement for Homebrew. I would like functionality similar to `brew cleanup` that would allow me to uninstall all old versions of software that are no longer used by my environment. 

### Description

Preferably, this wouldn't include build dependencies needed to install my environment, since I will need to reinstall the environment from time-to-time ~~, and since Spack currently automatically installs build dependencies even when they aren't needed (#7695)~~.

In the meantime, @becker33 came up with the following script that could likely be adapted to work for `spack gc`:
```python
#!/usr/bin/env spack-python
from spack.cmd.uninstall import dependent_environments
import spack.store
installed = spack.store.db.query()
for spec in installed:
    if not dependent_environments([spec]):
        spec.package.do_uninstall()
```

@alalazo

**Comment by sethrj** [comment]
Yes please!

**Comment by sethrj** [comment]
Worth noting: the above script will delete build-only dependencies when run on the current spack develop (i.e. autotools will go away unless your environment requires it).

Here's a tweak to the above script that makes its operation a little clearer by "inlining" and simplifying the `dependent_environments` command.
```
#!/usr/bin/env spack-python

import spack.environment as ev
from spack.package import PackageStillNeededError
import spack.store

installed = {spec.dag_hash(): spec for spec in spack.store.db.query()}

envhashes = set()
for eh in ev.all_environments():
    envhashes.update(eh.all_hashes())

unwanted = set(installed) - envhashes
for hash in unwanted:
    spec = installed[hash]
    try:
        spec.package.do_uninstall()
    except PackageStillNeededError as e:
        print(e)
```

**Comment by glennpj** [comment]
Would this only catch environments that are listed under $spack/var/spack/environments, not environments in directories outside of the $spack tree?

**Comment by alalazo** [comment]
@adamjstewart Currently `spack gc` is context sensitive, meaning it behaves differently depending on whether or not an environment is active. If we add this functionality should it distinguish between these two contexts?

**Comment by adamjstewart** [comment]
Yes, I think it makes sense to keep it context sensitive. I'm fine with keeping the current behavior intact and simply adding an extra flag that does what I need. I'm also fine with adding a new command that does exactly what I need, or replacing the current behavior of `spack gc`. Basically, I just want a way to replicate `brew cleanup` with Spack Environments.

**Comment by alalazo** [comment]
@adamjstewart I'm trying to figure out a way to keep the functionality we have in `spack gc` and add the one you need in a way that is not surprising to users and that can take into account @glennpj comment (i.e. have a way to manually add other environments if they are not managed by Spack). 

If we go this way (my first thought too):

> I'm fine with keeping the current behavior intact and simply adding an extra flag that does what I need.

that extra flag will behave the same both within an environment and outside of it, so suddenly you have an option that turns a context sensitive command into something that is not. Something like that might be confusing, because it requires you to think:

1. If you are in an environment or not
2. Which options are you passing to the command

to reason about the resulting outcome, while I think it's enough to reason only about one of the two points above.

One possibility that comes to my mind would be to trigger the different behaviors by setting an option:
```console
$ spack gc --mode=[store,all,active] 
```
where:
-  `store` is the current behavior outside of an environment
- `active` is the current behavior when an environment is active
- `all` is the behavior you request here

An additional option to take into account anonymous environments can be added to work on @glennpj observation:
```console
$ spack gc --mode=all -e </path/to/env1> -e </path/to/env1>
```
Does that seem a reasonable design for the cli? Would you change anything (or is anything not clear)? 

Also: if we really want to be 100% backward compatible we can change the default value for the `mode` option from `store` to `active` when an environment is active.

**Comment by adamjstewart** [comment]
Hmm, I'm still thinking about this. The way I see it, `spack gc` is a command to "garbage collect packages" or "remove no longer needed installations". There are many different ways to define "no longer needed":

1. Build dependencies (not needed after build is finished)
2. Out-of-date software (older versions where a newer version is also installed)
3. Inactive software (installations not present in an environment)
4. Leftover software (unexplicitly installed software whose dependents were uninstalled)

In a lot of ways, this command is similar to `spack clean`, so why not use a similar CLI? For example:
```console
$ spack gc --old
$ spack gc --build --inactive
$ spack gc --all  # equivalent to -boil
```
This could still be made environment-aware. When not in an environment:
* `--old`, `--build`, and `--leftover` apply to all packages
* `--inactive` removes any installation that is not present in any environment

When in an environment:
* `--old`, `--build`, and `--leftover` apply only to packages in the environment
* `--inactive` removes any installation not present in the current environment

That last one might be problematic, so we might want to change that (or even disallow that option). How do you feel about this?

**Comment by becker33** [comment]
@adamjstewart I think that in the last case (in an environment) the `--inactive` flag should still respect other environments known to Spack.

**Comment by sethrj** [comment]
I didn't know this hadn't been merged... any updates on this? 'Twould be useful.

**Comment by adamjstewart** [comment]
Has anyone gotten a chance to work on this yet?

**Comment by alecbcs** [comment]
I'd also like to jump into this conversation and say that I'd find this feature immensely helpful. At the moment I'm upgrading my brew like environment by running the following verbose set of commands. It'd be nice to simplify this a bit and respect specs in other known environments.

```console
$ spack mark -ai
$ spack env activate myenv
$ spack concretize --fresh --force
$ spack install
$ spack env deactivate
$ spack gc
```

**Comment by tgamblin** [comment]
Ok folks try out #41731 and see if you like it.
