### ISSUE TITLE
Metis doesn't compile with external intel compiler (OpenMP pragma error)

### ISSUE THREAD

**Issue by jayghoshter** [spack/spack#14785]
I have a setup with an external intel compiler that was added to spack. Metis is not building with it. 

The error says "Unrecognized openmp pragma". Build log is attached below.
[build-metis-intel.txt](https://github.com/spack/spack/files/4165457/build-metis-intel.txt)

---

### Steps to reproduce the issue

```console
$ spack install metis build_type=RelWithDebInfo int64=True gdb=True %intel
```

### Platform and user environment

```commandline
$ uname -a 
Linux 3.10.0-1062.7.1.el7.x86_64 #1 SMP Mon Dec 2 17:33:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

OS: CentOS 7
``` 
### Additional information

```console
Input spec
--------------------------------
 -   metis%intel+gdb+int64

Concretized
--------------------------------
 -   metis@5.1.0%intel@19.0.3.199 build_type=Release +gdb+int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 ~real64+shared arch=linux-centos7-haswell
[+]      ^cmake@3.15.5%intel@19.0.3.199~doc+ncurses+openssl+ownlibs patches=3387faf4a71efe81c0fa17410b270ca7d352081ac88d2322df3da9bb6a6a3f2d ~qt arch=linux-centos7-haswell    
[+]          ^ncurses@6.1%intel@19.0.3.199~symlinks~termlib arch=linux-centos7-haswell
[+]              ^pkgconf@1.6.3%intel@19.0.3.199 arch=linux-centos7-haswell
[+]          ^openssl@1.1.1d%intel@19.0.3.199+systemcerts arch=linux-centos7-haswell
[+]              ^perl@5.30.0%intel@19.0.3.199+cpanm+shared+threads arch=linux-centos7-haswell                                                                                 
[+]                  ^gdbm@1.18.1%intel@19.0.3.199 arch=linux-centos7-haswell
[+]                      ^readline@8.0%intel@19.0.3.199 arch=linux-centos7-haswell
[+]              ^zlib@1.2.11%intel@19.0.3.199+optimize+pic+shared arch=linux-centos7-haswell                                                                                  

```

**Comment by payerle** [comment]
I am seeing similar on
* **Spack:** 0.14.2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-ivybridge

using intel-parallel-studio@2020.1 (externally installed, but I do not think that matters).

Issue seems to be that icc generates warnings on \#pragma omp lines when not invoked with the proper OpenMP flag, and based on other flags warnings are promoted to errors.  But as this is metis, not mt-metis, we should not be using OpenMP flags.

The pull request above adds a compilation flag to ignore pragma omp warnings/errors (it looks like since %intel@14 these were at least separated from other diagnostics, see e.g. 
https://community.intel.com/t5/Intel-C-Compiler/ICC-should-not-generate-warning-about-quot-pragma-omp-quot-when/td-p/810081?profile.language=pt).

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/19049 now merged so I'll close this as fixed. Feel free to reopen if the problem resurfaces.
