### ISSUE TITLE
Additional containerize spec file customization

### ISSUE THREAD

**Issue by samcmill** [spack/spack#14802]
The [containerize feature](https://github.com/spack/spack/pull/14202) should allow more customization of the container spec file.

### Rationale

Consider the use case of an application container to be run multi-node over InfiniBand.  The MPI library needs to be built with fabric support.  E.g.,

```
spack:
  specs:
  - gromacs@2019.4 build_type=Release
  - openmpi@3.1.4 fabrics=verbs
  - fftw precision=float
  packages:
    all:
      target: [broadwell]

  container:
    format: docker

    base:
      image: "ubuntu:16.04"
      spack: develop

    strip: true

    os_packages:
    - libgomp1
```

This container build will fail because the IB verbs packages are not present in the container base image.

### Description

The set of base images is highly restricted, so the option of using a custom base image with the IB libraries already included is not allowed.

The `os_packages` section applies only to the runtime stage of the spec, not the build stage.  Regardless, the packages are installed after spack, not before as would be necessary in this case.

The `extra_instructions` `build` section is executed after spack, so it's also not an option.

Based on the failed approaches, there are 3, not mutually exclusive, potential containerize enhancements.

1. Remove the base image restriction.  Perhaps display a warning if a custom base image is selected, but don't disallow it outright.

2. Extend the `os_packages` section to include `build` and `runtime` sections.  E.g.,
```
  os_packages:
    build: libibverbs-dev
    runtime: libibverbs
```

The behavior should also be changed to install the packages before spack, not after.

3. Add a new `extra_instructions` section that is inserted prior to spack, e.g., `prebuild` or `setup`.
```
  extra_instructions:
    prebuild: RUN apt-get update -y && apt-get install libibverbs-dev 
```

My suggestion would be 2 to address this particular use case, but 3 would be a more general, if less user friendly, solution.

**Comment by hartzell** [comment]
> The set of base images is highly restricted, so the option of using a custom base image with the IB libraries already included is not allowed.

Are there reasons other than the fact that these base images have been built such that they

> [...] take care of all the repetitive tasks that are necessary to setup Spack within a container [...]

to restrict the base image?

I don't see those tasks discussed/summarized anywhere other than the Dockerfiles that are used to create the official base images ([e.g. Ubuntu 18.04](https://github.com/spack/spack/blob/develop/share/spack/docker/ubuntu-1804.dockerfile)).  

Could we loosen the restriction by improving the docs?

**Comment by alalazo** [comment]
@hartzell The main reason right now is to ensure by design consistency between the build stage and the final stage (we use our prebuilt images on Dockerhub for the build stage and a matching base OS for the final stage). Suggestions 2. and 3. above are fast to implement and won't break this consistency. Suggestion 1. will probably require some care but it's also something we are thinking of to e.g. allow people to specify a commit hash as a version for Spack.

I'm curious if you have any particular use case in mind that will benefit from other generalizations.

**Comment by samcmill** [comment]
A related use case is CUDA.  For instance, building a GPU aware GROMACS:

```
spack:
  specs:
  - gromacs@2019.4 build_type=Release 
  - cuda@10.1.243
  - fftw precision=float
```

This will pull in the entire CUDA toolkit and it gets copied into the final stage of the container.  The resulting Docker container is 4.3 GB.

The [Nvidia provided CUDA base images](https://hub.docker.com/r/nvidia/cuda/) address this problem by providing devel and runtime/base variants for the build and final stage, respectively.

Implementing suggestion 1 could potentially address this if Spack was also configured to use the "system" CUDA from the base image rather than installing its own, but 2 and 3 would not.

**Comment by hartzell** [comment]
@alalazo -- I'm playing catch-up and may well have missed a lot.  With that (and my general Spack enthusiasm) in mind.....

I write and recombine bits of software to solve problems.

Software that makes minimal demands on its environment and that's loosely coupled is easier to remix (technically, socially, politically) than software that has to own the playing field.

"You have to use our image" is a big red flag for me.  Why?  What's in there?  Why should we trust you?  How am I going to make it work in <insert screwed up local situation here>?  [How much more time will I have to spend at Layer 9][evi]?

I can't see any opportunity for arcane magic between the build and final stages (looking at the generated Dockerfile at the bottom of the [Containers documentation][containers-doc]).  Clearly the final image needs to be able to run the binaries the builder built, but there's nothing (magical or otherwise) in the resulting image beyond the final base, what's copied in from the builder and what the user has requested be yum installed.

Wouldn't it be enough to ensure that the final image's *platform* matched the one that the builder used?

Some concrete problematicals:

- A few jobs ago, we didn't trust Docker Hub's promise that a particular image had been built from a particular Dockerfile; we built our own (from trusted OS base images) and stored them locally.

- It don't see a way to fix the version of the base image that I'm using to the one that was used in e.g. an FDA Validation process (even though the community has moved on to a newer build of CentOS 7).

[containers-doc]: https://spack.readthedocs.io/en/latest/containers.html
[evi]: https://www.flickr.com/photos/philwolff/96987427

**Comment by hartzell** [comment]
I'm not sure if this is a problem for people's use cases and/or is worthy of a separate issue, but the Dockerfiles that Spack's producing are not deterministic; the image that I build today is unlikely to be the image that I build a month from now.

I see two issues:

1. Calling yum update in the Dockerfiles.

2. There's no way to pin the particular image used (see above) and tags, (e.g. `centos:7`) can move.

**Comment by alalazo** [comment]
@hartzell 

> "You have to use our image" is a big red flag for me. Why? What's in there? Why should we trust you? How am I going to make it work in ? How much more time will I have to spend at Layer 9

I understand your concerns and there's work on-going to loosen the restriction. That said "you have to use our image **at build-time**" (the run-time is one of the supported OS images, see [here](https://spack.readthedocs.io/en/latest/containers.html#id1)) and Spack images are built on Docker Hub so the Dockerfile is public and available for anybody to inspect.

> I can't see any opportunity for arcane magic between the build and final stages (looking at the generated Dockerfile at the bottom of the Containers documentation)

Why there should be "arcane magic" or what do you mean by that? Multi-stage builds are just convenient to get rid of all the system build dependencies that are not needed at run-time - including Spack itself in this case.

> Wouldn't it be enough to ensure that the final image's platform matched the one that the builder used?

If by "platform" you mean the base OS, then yes. Right now we enforce this match - so it's always correct albeit a bit restrictive.

> It don't see a way to fix the version of the base image that I'm using to the one that was used in e.g. an FDA Validation process (even though the community has moved on to a newer build of CentOS 7)

Agreed. Being able to construct containers from a previous base image or Spack version or both specifying their hash is in the roadmap.

**Comment by ChristianTackeGSI** [comment]
> 3. Add a new `extra_instructions` section that is inserted prior to spack, e.g., `prebuild` or `setup`.
> 
> ```
>   extra_instructions:
>     prebuild: RUN apt-get update -y && apt-get install libibverbs-dev 
> ```

We have a use case for this:
We have our own repository with additional spack recipes which we want to use there. So we need to fetch it in the build and do a `spack repo add`.

**Comment by alalazo** [comment]
> We have our own repository with additional spack recipes which we want to use there. So we need to fetch it in the build and do a spack repo add.

That makes perfect sense. I'll  think of some shorthand in the YAML file to copy directories or files in before the build starts, since that would be probably the action required most often. I'll also add another `extra_instructions` attribute to inject arbitrary commands in the recipe file if need be.

For your use case am I correct that it would be sufficient to be able to copy the repository in and then add a `repos` section to your `spack.yaml`?

**Comment by alalazo** [comment]
@hartzell @samcmill @ChristianTackeGSI For copying things in the image from the build host or previous stage the simplest extension to the YAML file that comes to my mind is:
```yaml
copy:
  build:
  - source: '/repo/path'
    destination: '/container/path'
  final:
  - source: '/path/on/host'
    destination: '/path/in/container'
  - source: 'build:/path/from/previous/stage'
    destination: '/another/path/in/container'
```
Anything that starts with `build:` under the `final` attribute will be copied from the `build` stage.

**Comment by ChristianTackeGSI** [comment]
> For copying things in the image from the build host or previous stage the simplest extension to the YAML file that comes to my mind is:
> […]
> Anything that starts with `build:` under the `final` attribute will be copied from the `build` stage.

That looks good.

* I don't know, if `build:` is the right way, or if `build_src` and `host_src` attributes would be better?
* Allowing relative paths in the `host_src` comes to my mind.  On the other hand, our build system will generate the `spack.yaml` anyway, so we can generate absolute paths.

> For your use case am I correct that it would be sufficient to be able to copy the repository in and then add a `repos` section to your `spack.yaml`?

Probably. Things might not be as easy, because we currently like to pin the used spack version (including some patches), but in the long run, that would probably be the way to go, yes.

**Comment by alalazo** [comment]
> Allowing relative paths in the host_src comes to my mind.

I'll just treat the paths as string and forward them to the recipes. The build context will do its checks during image build.
