### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by spiani** [spack/spack#14846]
---

### Steps to reproduce the issue

```console
spack install llvm@9.0.1

...
==> Building libedit [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/step/spack-stage/spack-stage-libedit-3.1-20170329-6yorh6hmyp7mlm6ihmlnvbypcrazseqj/spack-src/configure' '--prefix=/home/step/environments/dealii-9.1-clang-9.0/spack/opt/spack/linux-ubuntu19.10-skylake/gcc-9.2.1/libedit-3.1-20170329-6yorh6hmyp7mlm6ihmlnvbypcrazseqj'

1 error found in build log:
     85    checking whether ln -s works... yes
     86    checking for gawk... (cached) gawk
     87    checking for nroff... /usr/bin/nroff
     88    checking for tgetent in -lncurses... no
     89    checking for tgetent in -lcurses... no
     90    checking for tgetent in -ltermcap... no
  >> 91    configure: error: libncurses, libcurses, or libtermcap is required!

```

### Platform and user environment

Here is a brief description of my OS:
```commandline
$ uname -a 
Linux Zorn 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Ubuntu 19.10
``` 

### Additional information

Recentely, the following lines were added to the packages.py file of llvm:

```commandline
# ncurses dependency
depends_on('ncurses+termlib')
```

and, therefore, now llvm requires that ncurses is compiled with the support for termlib. Unfortunately, it looks like libedit configure is not able to recognize the ncurses library if it is installed with the +termlib flag.

I am currently using spack (commit d1d5f5f9) without any configuration different from the default one. I do not have any other package installed when I execute
```console
spack install llvm@9.0.1
```
I am using the default compiler of Ubuntu (gcc@9.2.1)

Thank you!

**Comment by adamjstewart** [comment]
@glennpj @danlipsa @scheibelp

**Comment by glennpj** [comment]
On my CentOS-7 system libedit simply links to libtinfo when termlib is true. See #14795 for additional discussion. I am looking more at the llvm package to see if the tinfo linking can be turned off. Either way, the +termlib setting likely needs to be changed.

**Comment by scheibelp** [comment]
This particular issue could be resolved by getting a newer version of libedit. From the logs at https://thrysoee.dk/editline/: 

```
2019-12-31 Jess Thrysoee

   * version-info: 0:63:0

   * configure.ac: Support -ltinfo as split in newer ncurses
	The newer versions of ncurses support building terminfo routines as a split -ltinfo library.
	Patch by Michał Górny
```

I'm not sure when this split was added to `ncurses` but it's also possible that `libedit` should be constrained to use those older versions of `ncurses`.

**Comment by scheibelp** [comment]
@spiani would you be able to confirm whether https://github.com/spack/spack/pull/14851 addresses this issue for you?

**Comment by glennpj** [comment]
I just submitted PR #14853 that should fix this. I did not set the 'fixes #' here because I am not sure if it is preferred to do that with #14851.

**Comment by scheibelp** [comment]
From https://github.com/spack/spack/pull/14795#issuecomment-583661213

> It seems like there may be different behavior between CentOS and Ubuntu. For me `libedit ^ncurses~termlib` linked against libncurses and `libedit ^ncurses+termlib` linked against libtinfo

Sounds right, and I think the problem on Ubuntu was that `libedit` was refusing to search for symbols in a `libtinfo`. The version of `libedit` added in https://github.com/spack/spack/pull/14851 apparently is willing to look in `libtinfo`, which would allow both `libedit` and `llvm` to use `ncurses+termlib`.

#14853 takes the approach of configuring `llvm` to not depend on `terminfo`. I prefer #14851 (assuming it works) because I don't know the consequences of removing `terminfo` support from `llvm` (and I'm inclined to think it ought to be possible to allow it).

**Comment by glennpj** [comment]
> #14853 takes the approach of configuring `llvm` to not depend on `terminfo`. I prefer #14851 (assuming it works) because I don't know the consequences of removing `terminfo` support from `llvm` (and I'm inclined to think it ought to be possible to allow it).

Okay; I had already gone down that path before seeing your comments. I guess we wait to see if #14851 works then.

**Comment by danlipsa** [comment]
@scheibelp Here is a discussion for why llvm depends on terminfo (deals better with strange/older terminals). People there generally agree that it should not.

https://groups.google.com/forum/#!topic/llvm-dev/MqpXVMy6OrM

**Comment by glennpj** [comment]
I think I have figured out what is going on. In 
`.../llvm/cmake/config-ix.cmake` is this code:
```
    if(LLVM_ENABLE_TERMINFO)
      set(HAVE_TERMINFO 0)
      foreach(library terminfo tinfo curses ncurses ncursesw)
        string(TOUPPER ${library} library_suffix)
        check_library_exists(${library} setupterm "" HAVE_TERMINFO_${library_suffix})
        if(HAVE_TERMINFO_${library_suffix})
          set(HAVE_TERMINFO 1)
          set(TERMINFO_LIBS "${library}")
          break()
        endif()
      endforeach()
    else()
      set(HAVE_TERMINFO 0)
    endif()
```
The tinfo library is checked first. If ncurses is built without termlib, no libtinfo, then the system libtinfo will be checked next. On a CentOS system, that satisfies the test and llvm will link the system libtinfo. If ncurses is built with +termlib then the spack libtinfo will be found and used.

I tried a patch to move tinfo to the end of the list. With that, the search will be on the (n)curses libraries first. If spack ncurses is built with ~termlib then the tinfo symbols will be in the (n)curses library and satisfy the test. If ncurses is built with +termlib then the (n)curses libraries will fail the test. Since a CentOS system splits out tinfo, the system (n)curses libraries will also fail and it will eventually find the spack built libtinfo, which would be the correct library. It does seem that the directory order of testing is correct. Thus, moving tinfo to the end of the list in the above code will allow the spack dependency to be set to `depends_on('ncurses')` but still work if someone uses +termlib in the spec.

This would be an alternative to #14853 to fix the issue of having ncurses+termlib in the llvm package recipe, leaving llvm using TERMINFO but allowing it to use either ncurses or tinfo libraries. I guess the question is do we want to use TERMINFO for llvm or not, as @danlipsa referenced above. Let me know and I can submit another PR, or modify #14853 accordingly.

**Comment by glennpj** [comment]
There is still one scenario that would not be covered above and that would be if the system ncurses does not split out a tinfo library and one uses spack ncurses+termlib. In that scenario, with the reordering, the tinfo symbols would be found in the system (n)curses library first and that library would be linked. That would be less likely, based on the default settings. I suppose if we know which OS systems have, or do not have, a tinfo library we could conditionally patch.

**Comment by spiani** [comment]
@scheibelp Yes, I can confirm that with #14851 it works flawlessly.

I executed 
```console
spack install libedit ^ncurses+termlib
```
without any problem. This is what I get when I run the find command

```console
step@Zorn:~/environments/test/spack$ spack find -c -f -v -d libedit
==> 1 installed package
-- linux-ubuntu19.10-skylake / gcc@9.2.1 ------------------------
libedit@3.1-20191231%gcc 
    ncurses@6.1%gcc ~symlinks+termlib

```

**Comment by glennpj** [comment]
I submitted PR #14862 as the alternative to #14853 that I mentioned. #14862 will still use TERMINFO but will give preference to checking the ncurses library first. This will work better with the default ncurses package.

**Comment by danlipsa** [comment]
@glennpj linking to ncurses and / termlib is a new behavior isn't it? So llvm was somehow built without it before. If that is the case I would vote to remove that dependency.

Your alternate fix seems to depend on a fairly complex interplay of options and os choices. If we go that route we should try to upstream the patch to llvm.

**Comment by glennpj** [comment]
@danlipsa No, it is not new behavior, llvm was using ncurses before. Prior to my changes to llvm the state of the llvm package with regard to ncurses was partially broken, which I was trying to fix. Initially, there was an ncurses spack dependency only when `+lldb` was set. If `~lldb` was set then ncurses was not listed as a dependency and llvm would look for terminfo symbols from the system libraries. That is where the ordering is important, but whether the terminfo symbols are in libncurses or libtinfo, there would still be a link to system libraries. 

So, llvm always depends on ncurses if `DLLVM_ENABLE_TERMINFO` is `ON`. If `+lldb` was set then there was a dependency set for spack as lldb needs ncurses, but not the terminfo symbols, it is other parts of llvm that look for the terminfo symbols. Regardless of the setting for `lldb`, llvm will look for terminfo symbols. If `~lldb` was set then there was no spack ncurses dependency and the system library would be used. I mistook that to mean that llvm wanted libtinfo, but then later discovered the order of the libraries that it was checking, so it could be changed.

And yes, there is a complication in that in some scenarios of specs it will depend on whether the OS has libtinfo or not, ie., is it splitting the terminfo symbols into a separate library. It is really an ncurses oddity as either search ordering could lead to linking system libraries. I agree that fixing that upstream would be better, with llvm providing a way to specify the library that contains the terminfo symbols. However, I think that #14862 would cover most cases in spack in the interim.

**Comment by danlipsa** [comment]
@glennpj I see. Thanks for the explanation.
