### ISSUE TITLE
awscli package name

### ISSUE THREAD

**Issue by glennpj** [spack/spack#15174]
I am not sure if this is an issue or not. Given that the awscli package is a python package, it seems like it should be called py-awscli. The reason given in the original PR is not clear.

https://github.com/spack/spack/pull/11796#issue-289933161

**Comment by adamjstewart** [comment]
The reason is given by https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#choosing-a-package-name

Basically, it's a command-line tool, not a Python library that one would import in their code. The same is true for `aws-parallelcluster` and `mercurial`. Maybe it's possible to `import mercurial` in your code, but 99% of users only use it as a command-line tool, and don't even realize it's written in Python.

Maybe some of the `aws-parallelcluster` maintainers would like to chime in: @sean-smith @demartinofra @enrico-usai @lukeseawalker @rexcsn @ddeidda @tilne Do any of you have strong feelings about the names `awscli` and `aws-parallelcluster` vs. `py-awscli` and `py-aws-parallelcluster`? Also, would any of you be interested in maintaining the `aws-parallelcluster` package in Spack?

**Comment by glennpj** [comment]
That makes perfect sense, and with that context the comment in the original PR is clear.

**Comment by enrico-usai** [comment]
Hi @adamjstewart 
thanks for asking. 

aws-parallelcluster is a command-line tool, so we prefer the name without the py- prefix.

Our idea is to try to maintain the aws-parallelcluster package up-to-date in spack by creating a PR whenever we release a new version of the package.

Thanks
