### ISSUE TITLE
mesa should default to ~llvm

### ISSUE THREAD

**Issue by svenevs** [spack/spack#15397]
### Spack version

```console
$ spack --version
0.14.0-150-ce287bc
```

### Discussion

Can we default this to off?  Right now anybody bringing in any opengl dependency gets llvm forced on them.  I was surprised to see llvm building (and ultimately fail) for `py-matplotlib %gcc`.  The new package seems nice / it's cool to have different stuff in there, but this is a _huge_ dependency to bring in automatically for something like `mesa` in my opinion.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
    - Seems to be cause of https://github.com/spack/spack/issues/8074
    - Introduced in https://github.com/spack/spack/pull/10482
        - CC: @chuckatkins (you know what's going on here best! :))
- ~I have run the failing commands in debug mode and reported the output~

**Comment by chuckatkins** [comment]
Any change to remove llvm as a dependency would be short lived. It's not really feasible to have mesa without llvm anymore. We're currently stuck on 18.x in spack since there's not a way to transition packages path to other build systems (which might be time to revisit, but that's a different story), but in newer releases of mesa it's effectively required since the "classic" non-llvm-based driver stack is deprecated and no longer actively developed.

**Comment by svenevs** [comment]
Huh, very interesting! Ok then leave it we shall, thanks for the explanation!
