### ISSUE TITLE
How to handle security updates?

### ISSUE THREAD

**Issue by eschnett** [spack/spack#172]
For example the library `openssl` provides security updates for time to time, essentially deprecating earlier versions of the package. How should this be handled in spec files? One straightforward approach would be to remove the checksums for this version (and adding a comment into the spec file).

**Comment by sjtbham** [comment]
I asked about something similar on the mailing list, so adding here what I think is relevant.

I should be able to mark a version of a package as obsoleted.

use case: This might not just be a security reason, for example I use torque, and we build openmpi with torque support enabled, if I upgrade torque, then I should also rebuild all my dependent applications.

It would then be useful for spack to either have a rebuild dependents (which could of course be a large tree), or an option to tell me what packages I should rebuild at the far end of the tree based on the upgraded dependency, as an operator, I can then decide what I want to build again.

**Comment by tgamblin** [comment]
I think we should add something like this but I'm not sure how soon we could do it.  We recently added the ability to mark particular versions as "preferred", so that even if someone adds a new version of a package, Spack will still default to an older (maybe more stable version) if you want it to.   @trws suggested in #272 that we should be able to mark things as `stable`, `bleeding edge` or `unstable` -- I think `obsolete` might be implicit if you have those two.  Or, maybe we could have something like `obsolete` and `dangerous` for marking things you really *should* upgrade right now.

As for the rebuild, we at least have the information to do that and I think it would be useful to say "rebuild a particular tree".  Or maybe something like "rebuild everything that depends on a specific package or set of packages".  People have asked for both of those.

I will have what i need to implement that stuff once a fairly recent PR by @becker33 is merged.  That adds some features to the spec syntax that would let you refer to specs on the command line by hash -- something that is currently lacking.

Thanks for the suggestions!

**Comment by tgamblin** [comment]
Another thing I forgot to mention is that sometimes you really want to upgrade *in place* instead of rebuilding.  Rebuilding, if you do it even slightly differently, will change the hash of your spec.  So if you relied directly on a previous install, you won't get the upgrade.  If you go through something like `spack use`, `spack load`, or `spack location`, then it'll be relatively seamless, but those aren't ideal solutions.

I would like to have two things:
  1. The ability to "upgrade" by moving an old version aside and sym-linking its directory to a new version 
  2. The ability to have some kind of layer of indirection over what Spack currently builds (we're calling this an "environment" at LLNL -- sort of like virtual environments, conda environments or Nix profiles).

**Comment by alalazo** [comment]
relates to #7409
