### ISSUE TITLE
Depending on the same package conditionally and unconditionally may cause concretization failures

### ISSUE THREAD

**Issue by davydden** [spack/spack#1781]
I was trying to rewrite a long combinatorial chain of `depends_on(boost)`  (`+mpi` is `on` by default) 

```
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams",
               when='@:8.4.2~mpi')
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams+mpi",
               when='@:8.4.2+mpi')
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams",
               when='@8.5.0:~mpi~python')
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams+mpi",
               when='@8.5.0:+mpi~python')
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams+python",
               when='@8.5.0:~mpi+python')
    depends_on(
        "boost@1.59.0:+thread+system+serialization+iostreams+mpi+python",
        when='@8.5.0:+mpi+python')
```

in a much more concise and readable way 

```
    depends_on("boost@1.59.0:+thread+system+serialization+iostreams")
    depends_on("boost+mpi", when='+mpi')
    depends_on("boost+python", when='@8.5.0:+python')
```

but i got an error `Package boost requires variant +mpi, but spec asked for ~mpi`

```
==> Error: Invalid spec: 'boost@1.61.0%clang@7.3.0-apple+atomic+chrono+date_time~debug+filesystem~graph~icu_support+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals+singlethreaded+system+test+thread+timer+wave arch=darwin-elcapitan-x86_64'. Package boost requires variant +mpi, but spec asked for ~mpi
```

It looks like once the normalized spec settles on

```
^boost@1.59.0:+iostreams+serialization+system+thread
```

i.e. without `~mpi`, Spack can not add to this from other conditional dependencies even within a single `package.py`. 

It would be good to fix this (with unit tests) and also document in `Developers Guide` how Spack treats such cases. From other PRs i had an impression that Spack can make a union of dependencies, but it does not seem to be the case here. It could be that it worked by chance for other packages, that already rely on this functionality.

**Comment by adamjstewart** [comment]
Hmm, that's weird. You don't have boost in your `packages.yaml` right? This is something that should go in the Packaging Guide, not the Developers Guide. I would love unit tests for this though.

**Comment by davydden** [comment]
> You don't have boost in your packages.yaml right? 

no, i don't.

> This is something that should go in the Packaging Guide, not the Developers Guide.

sure, i mixed the two. `Packaging Guide` is of course the right place.

p.s. in case someone wants to reproduce this, it is `dealii` package.

**Comment by adamjstewart** [comment]
> p.s. in case someone wants to reproduce this, it is `dealii` package.

Ah, now I understand what's going on here. The problem is not with your `depends_on` definitions, it's with the variant defaults. Boost defaults to `~mpi` but dealii defaults to `+mpi`. Currently, Spack isn't smart enough to override the defaults with a spec that actually works.

I ran into the same problem with #1552/#1553, and @ax3l ran into the same problem in #1667/#1727. My solution was to make sure both packages defaulted to `+mpi`. However, this is only a partial solution. If one of your packages is set to `~mpi` in `packages.yaml`, the error message returns. So I also removed variant forwarding because that's really what's causing the confusing error message you're seeing. Instead, in NetCDF, I raised an error if you are trying to build `netcdf+mpi` with `hdf5~mpi`. The error can give a much more understandable message than the one you are seeing.

Obviously this isn't ideal, but it's all I could do without messing with Spack's internal dependency resolution. If someone wants to tackle the root cause, be my guest. My suggestion for fixing it would be to allow global variant forwarding, meaning that if I build something with `+mpi`, it builds all packages with `+mpi` explicitly. @eschnett had an alternative suggestion which I would also be fine with:

> If two packages want conflicting variants, and one of these is closer to the "root", then this package should take precedence. Say the user wants to install A, and A depends on B, B defaults to +mpi, and B depends on C which defaults to -mpi, then B's setting should take precedence.

**Comment by davydden** [comment]
> Boost defaults to ~mpi but dealii defaults to +mpi. Currently, Spack isn't smart enough to override the defaults with a spec that actually works.

correct, that's what I was trying to describe in OP :smile:. Had the boost `+mpi` as default, then the normalized spec would be
```
^boost@1.59.0:+iostreams+serialization+system+thread+mpi
```
and the whole thing would work.

I would still have problems with `+python`, because it's not only about the default variants in `dealii`, but also its version -- for now only the `@develop` has some python bindings, so there is no need to require `boost+python` for other versions.

> If someone wants to tackle the root cause, be my guest

I hope for that, my understanding is that one need to allow expanding `normalized` specs during conretization of the root package. So in my case, the normalized spec would contain
```
^boost@1.59.0:+iostreams+serialization+system+thread
```
and then depending on variants of `dealii` one would have `+mpi` and/or `+python` added to the `boost`.

**note:** Variant forwarding won't solve the root of the problem because it could be that there are no variants in the root package, but the decision of which variants to enable in `boost` is done based on the version (e.g. starting from some version, require more `boost` variants). Then there is nothing to forward, but the problem still exists.

**Comment by davydden** [comment]
p.s. for now, the original `depends_on` code does the job, but it's ugly and hard to read.

**Comment by citibeth** [comment]
@tgamblin is rumored to be working on a new ultimate constraints-based concretizer.  I suspect/hope it will solve many of these problematic corner cases.
