### ISSUE TITLE
Spack processes/tools to make reporting failures easier

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#1850]
I started an install and it failed with lots of text to the screeen and a pointer to a file for specifically what failed but no indication of a simple way to report back to the Spack developers all relevent information. For example what all my compiler and configuration options are etc. Perhaps on failure Spack could generate a list of exactly what files I should include in the Issue report? Maybe also generate files that we should submitt with a .txt extension since github issues don't like attachments with a .out extenstion. So you don't have to keep coming back to users and asking for more information? Perhaps you have this and I couldn't find it? 

Anyways, the specific failure I got was 
###### ################################################################## 100.0%

==> Staging archive: /Users/barrysmith/Src/spack/var/spack/stage/openblas-0.2.19-ys4mqarh3gjib36khldodtkpcl4dicix/v0.2.19.tar.gz
==> Created stage in /Users/barrysmith/Src/spack/var/spack/stage/openblas-0.2.19-ys4mqarh3gjib36khldodtkpcl4dicix
==> Applied patch make.patch
==> Building openblas
==> Error: Command exited with status 1:
'/Users/barrysmith/Src/spack/lib/spack/env/cc' '-o' 'check' 'test_cblas_dgemm.o' '-L/Users/barrysmith/Src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/openblas-0.2.19-ys4mqarh3gjib36khldodtkpcl4dicix/lib' '-llapack' '-lblas' '-lpthread'

See build log for details:
  /private/var/folders/c1/ldz_dt8n2r3dtwv_chp5pfr40000gn/T/barrysmith/spack-stage/spack-stage-bLlt6r/OpenBLAS-0.2.19/spack-build.out

I've attached the spack-build.out file 
[spack-build.out.txt](https://github.com/LLNL/spack/files/491900/spack-build.out.txt)

Note that the directory /Users/barrysmith/Src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/openblas-0.2.19-ys4mqarh3gjib36khldodtkpcl4dicix does not exist I don't know if this is because you delete it automatically on failure or if it never existed?

Also attaching ~/.spack/compilers.yaml and ~/.spack/packages.yaml (again note the nuisance factor of having to rename them to attach to github issues. Perhaps your "error report generator" could put all the information into a file .txt  and tell me about the file on failure so that I could easily attach?
[compilers.yaml.txt](https://github.com/LLNL/spack/files/491901/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/LLNL/spack/files/491902/packages.yaml.txt)

If you need anything more just let me know.

**Comment by davydden** [comment]
The problem is that Openblas cant detect fortran compiler from the default wrapper name f77. You need to patch Spack to mix Clang and Gfortran properly. See 
Mixing GCC and Clang on OSX

https://github.com/dealii/dealii/wiki/deal.II-in-Spack

Ps. Same info is somewhere in opened PRs with doc updates. 

Sent from  my iPhone. Please excuse my brevity.

**Comment by tgamblin** [comment]
This is a common enough special case that we ought to come up with a decent way to NOT require patching.  The issue is that OpenBLAS has a really horrible way of detecting compilers (using the name).  And when you mix compilers, Spack doesn't really know how to set the Fortran compiler name.

The long-term solution is an improved compiler dependency model to allow mixing.  It's something we're working on but it's not perfect.  Maybe the short-term solution should be to just create some appropriately named symlinks on the fly, rather than requiring the user to patch the `clang` compiler description.  I really don't like that solution.

**Comment by tgamblin** [comment]
Also a better bug reporting command to create a github issue with logs attached is a good idea.

**Comment by tgamblin** [comment]
Anyone have any idea how often anyone mixes Fortran compilers OTHER than gfortran with Clang? A simple short-term solution might be just to add some symlinks called `gfortran` for `clang`.

**Comment by davydden** [comment]
> Maybe the short-term solution should be to just create some appropriately named symlinks on the fly, rather than requiring the user to patch the clang compiler description. I really don't like that solution.

Fully agree, i dont like it either. Maybe on first 'spack install' check if using mixed compilers, and if so - do appropriate patching of the Spack's sourse and simlinks automatically?

**Comment by davydden** [comment]
> Anyone have any idea how often anyone mixes Fortran compilers OTHER than gfortran with Clang?

Without a survey it would be just a guess, but AFAIK gfortran is the only free fortran compiler, so on macOS they are probably used 99% of times together.

**Comment by tgamblin** [comment]
I can probably just engineer a quick fix for clang and add symlinks for everything to the `lib/spack/env/clang` subdirectory.  The compiler description can just try to detect a mixed compiler automatically and set those fields dynamically.  I don't think it needs patching.

We might not even need per-compiler `env` subdirectories -- we could just have all the symlinks in the same directory.  The idea was to keep unused compiler names *out* of the build environment so that builds that do things like hard-code `gcc` and `gfortran` will fail fast, but that might not be as important as the mixed compiler case as long as clang is the system compiler on OS X.

**Comment by davydden** [comment]
> I can probably just engineer a quick fix for clang and add symlinks for everything to the lib/spack/env/clang subdirectory. The compiler description can just try to detect a mixed compiler automatically and set those fields dynamically. I don't think it needs patching.

please do so, I can test on macOS when you have a PR.

**Comment by alalazo** [comment]
Closing as stale.
