### ISSUE TITLE
Modeling Real-World Versions

### ISSUE THREAD

**Issue by citibeth** [spack/spack#1997]
This is, in a way, a continuation of #1975.  In #1975, I set out to find a way to get what we need without coding special versions such as `develop` into the system.  That thread morphed into discussions of how we can double-down on the special versions, including changing the title to the OPPOSITE of what I originally sought.  Hence I'm starting a new Issue.  I would respectfully ask the following in this discussion:
1. Please keep an open mind as we look at example problems and solutions; we need to free ourselves from bias toward how things are currently, or what would be super-easy to implement in the  current system.  Those aspects are important later on, but not now.  At this point, I would like to come up with a model that we think WORKS, in the sense of modeling the real world.
2. Please separate semantics from syntax.  We might think up new ideas of how things MIGHT work, without yet understanding how the user should specify them.
3. Please avoid jumping to comparisons or shooting things down until we have a clear idea of what we're discussing.  Do not start shooting something down just because it's different.  New designs sometimes need time to solidify before being evaluated.
4. Please address the goals, issues and designs brought up in this thread.  New ideas are welcome.  Re-iteration of the ideas in #1983 are not (because that idea has already been discussed and we already know how it works).
# Example Versioning Schemes
## Example 1

It's been mentioned before that not all packages use the same versioning scheme.  As a way to illustrate that point, let me bring up a couple of examples.  One well-known piece of software uses the versions: `Cheetah` < `Puma` < `Jaguar` < `Panther` < `Tiger` < `Leopard` <`Snow Leopard` < `Lion` < `Mountain Lion` < `Mavericks` < `Yosemite` < `El Capitan` and `Sierra`.  Within each of these major versions are sub-versions.

But you say... those are just aliases for underlying "regular" version numbers.  True.  But people frequently refer to versions by the alias.  This scheme could be well represented using version numbers plus aliases.

**Conclusion**: People like version aliases.

**NOTE**: Aliases could replace the current `preferred=True` flag.

Another similar example is Ubuntu versions, the latest of which is `Yakkety Yak`.  These are also aliases for a well-ordered set of numeric versions.  Recent versions sort alphabetically, but not the earliest versions.  (4.10 = `Warty Warthog` but 5.04 = `Hoary Hedgehog`).
## Example 2

Another well-known piece of software uses the versions: `3.1` < `95` < `98` < `98SE` < `98SE sp3` < `Me` < `XP` < `Vista` < `7` < `8` < `8.1` < `10`. This is a little simplistic... it's atually two product lines.  Let's try again:

Product line DOS: `3.1` < `95` < `98` < `98SE` < `98SE sp3` < `Me` 
Product line NT: `3.1` < `3.5` < `3.51` < `4.0` < `XP` < ...etc.

Apparently, releases in the both product lines all have "regular" numeric identifiers.  Thus, as in Example 1, the trade names are also aliases for underlying numeric versions.  But we have a new wrinkle here: these versions actually come from two separate "branches," with no specific ordering between those branches.  For example, beetween `DOS-98` and `NT-3.51`, we can't say which one is greater or lesser.

**Conclusion**: Versions are partially ordered, not fully ordered.  Spack needs to deal with it gracefully, rather than forcing versions to be fully ordered.

One possible way to deal with the partial ordering (in some cases at least) is to define a Version as a tuple of (label, version).  The idea here is that Versions with the same label are fully ordered; and Versions with different labels are non-comparable.  In this case, there seem to be two labels (`DOS` and `NT`).
## Example 3: Git

Now consider any piece of software residing in a Git repo.  Each Git hash is potentially a version that can be installed, arranged in a partial order.  But given two hashes themselves (with no additional information), there is no way to determine their relationship in that partial order.  The algorithm to determine that relationship is specific to each package (in the sense that it needs information from that package's Git repo).

**Conclusion**: Partial ordering on versions is package-specific, not universal to Spack.  So are version aliases, for that matter.

Maybe labels could correspond to Git branches; meaning, a git hash N is labeled by a particular branch X if N is reachable from X.

Now suppose that certain hashes within this Git repo are actually releases (say, they are tagged; or we have some other way to know which Git hash corresponds to which release number).  So... we have `1.1` at one place in the Git repo, `1.2` at another place, and `2.0` somewhere else still.  Let's give these all the RELEASE label.  We would like to have `RELEASE-1.1` < `RELEASE-1.2` < `RELEASE-2.0`.  This will not always be the case within the Git repo itself.

**Conclusion**: Partial order cannot be determined JUST from the raw Git repo itself.  It needs annotation by the Spack package author.  Given a labelled release (say `2.0`) and a random Git hash, it may or may not be easy to come up with an algorithm that places the Git hash within a useful partial order with respect to the labelled release.
## Example 4: Floating Versions

We've begun to discuss floating versions.  If those versions come out of a Git repo and we have a good handle on versions in that repo (see Example 3 above), then floating versions are not so bad.  If I install `head of the master branch`, then Spack could convert to a version identified by Git hash, and then do whatever it needs there.
## Example 5: Uses of Version Comparison

AFAIK, Version ordering is used in (at least) two places: concretization and package conditionals.  In package conditionals, it is common to have code like "if version between 3.1 and 4.5.2, then apply this patch...". 

Concretization is a bit different: we want to select the "greatest" version, subject to certain constraints.  In particular, unless the user specifies otherwise, release versions are to be preferred, EVEN if there are other available versions that are "greater."

**Conclusion**: Version number comparison is not the same a priority in the concretization algorithm.

Maybe labels can help us distinguish between release and non-release versions.  A "RELEASE" label applied to ONLY released versions would allow for this.

---

I think we're still a ways from a complete versioning scheme that models the way real-world versions really work.  But I would suggest the following places to start from in thinking about designs and solutions:
1. Version comparison needs to reflect a partial order API, not a full order API.  So we can't use the regular `__lt__()` any more.  Instead, we need something like:

```
class Version(object):
    def compare(self, other):
    """Returns the smaller Version: SELF, OTHER, EQUAL or INCOMPARABLE"""
```
1. Since version schemes seem to be package-specific, that should be reflected in the Spack API.  This will give us the flexibility we need to implement different versioning schemes, partial orders, etc:  For example:
   a) Versions should maintain a reference to the Package to which they are related.
   b) New versions are constructed off of a Package (eg: Package.new_version() method).
   c) Comparison of Versions between packages throws an exception.
   d) Comparison of Versions belonging to the same package is delegated to a method on the Package.  Eg:

```
class Version(object):
    def compare(self, other):
        if self.package != other.package:
            raise Exception(....)
        return self.package.compare_versions(self, other)
```

Of course, delegating this to packages doesn't solve the problem of how version schemes should work for 99% of packages that will use the standard scheme.  But it does give us flexibility for the corner cases.  More importantly, it allows the standard scheme to do package-specific things (based on, for example, what it finds in `package.py` or the Git repo).
1. There probably needs to be some notion of "resolving" versions.  If I ask to install "head of the master branch," Spack should be able to resolve that to a SINGLE version within its well-defined partial ordering (e.g. the git hash representing head of master at that time).  If we can do useful comparisons with Git hashes, then the moving branch problem becomes pretty easy.

**Comment by citibeth** [comment]
I realized that, except for the "moving version tag" problem, versions are a really simple problem --- once one thinks of versions as package-specific, rather than universal.  Each package has a small and finite number of versions, and Spack wants them placed in a complete order.  This can be done a number of ways:

1. Require that users list versions in reverse-chronological order.

2. Require users to associate each version with an integer; those integers are then sorted.

3. Require users to associate each version with a multi-part version "number" (a tuple); those tuples are then sorted.

4. [Current Way]: Require versions to BE multi-part version "numbers" (tuples), with some special-case versions that mean special things but whose sort order cannot be changed.

5. Hybrid of (3) and (4): require users to explicitly associate with a multi-part version number if the version itself does not already parse to one.

Any way you do it, it's a pretty trivial problem.  Other than the "hidden" aspect of (1), I think it is quite elegant.

Dealing with moving "versions" is harder, and where our energies should be focused IMHO.

**Comment by adamjstewart** [comment]
A few more examples of version schemes to consider:

## Example 1: Dates

Some packages like `qhull` use the release date as the version number. This is fine as long as the date is sorted by `YYYY.MM.DD`, but if it is in any other order, Spack can't currently handle it.

## Example 2: OS/arch specific versions

Some packages, especially licensed software like `allinea-forge` or `pgi`, have different downloads for each OS. For example, the download URL for `allinea-forge` is:
```
http://content.allinea.com/downloads/allinea-forge-6.0.4-Redhat-6.0-x86_64.tar
```
This isn't necessarily a versioning problem so much as a fetching and checksum problem. Spack needs a better way to download an OS specific tarball and store a hash for just that version. Since some packages will use `Redhat` for RHEL, CentOS, etc while others will use `rhel` for the same versions, this needs to be package-specific. An if-statement should suffice. I think it would be good if we had better documentation on how to find the os/arch from within Spack and what the possible values for this are. But this is going slightly off topic. I think we can keep these problems simple by not storing the arch in the version name.

## Example 3: Package suites

Some packages like `intel-parallel-studio` have various levels or "suites" available for download depending on how much you pay. Currently, these look like:
```
professional.2016.3
professional.2016.2
composer.2016.3
composer.2016.2
cluster.2016.3
cluster.2016.2
```
These currently sort alphabetically instead of by year. This problem could be avoided by placing the date before the suite level, but should we even be comparing a professional edition to a composer edition in the first place?

**Comment by adamjstewart** [comment]
> Version comparison needs to reflect a partial order API, not a full order API. So we can't use the regular `__lt__()` any more. Instead, we need something like:
>
> ```
class Version(object):
    def compare(self, other):
    """Returns the smaller Version: SELF, OTHER, EQUAL or INCOMPARABLE"""
```

Can you elaborate more on this? What do you mean by "partial order API" vs "full order API"? I'm not sure why we can't use `__lt__()` as that is what Python uses for internal sorting. Your proposal sounds a lot like `__cmp__()`, which returns:
```
-1 if self  < other
 0 if self == other
 1 if self  > other
```
`__cmp__()` was deprecated in Python 3 and replaced by `__lt__()`, `__gt__()`, and several other so-called "rich comparison operators". See [the Python 2 docs](https://docs.python.org/2/reference/datamodel.html#object.__lt__) and [PEP 207](https://www.python.org/dev/peps/pep-0207/).

**Comment by adamjstewart** [comment]
> 1) Require that users list versions in reverse-chronological order.

This is a very interesting idea that I had never thought of!

Pros: simplicity
Cons: extra work to enforce it, works for sorting but not for dependency ranges?

I'm not sure how this would work with dependency ranges. If something depends on `@1.2:1.4` and our package includes versions `1.1`, `1.3`, and `1.5`, the order of versions alone isn't enough to determine whether or not `1.3` is between `1.2` and `1.4`. To do that, we need to fall back to our old means of sorting.

> 2) Require users to associate each version with an integer; those integers are then sorted.

This is basically the same idea as 1, but more explicit about it. It's basically an enum, but one that you need to manually specify numbers for. The main problem is that every time you add a new version (whether it is a newer version, an older version, or somewhere in the middle) you'll have to change the integer for every other version. Similar to the first idea, it allows you to sort, but it requires you to fall back on our old means of sorting for dependency ranges.

As far as I can tell, these 2 ideas require us to maintain our current means of sorting, but also add a new level or sorting? What do these actually add? They allow us to say that `develop` is newer if it comes first, but it seems like it would be difficult for us to say that `develop` satisfies `@1.2:` if the only version is `develop` or if the only versions are `develop` and `1.1`.

Like you said, Spack uses versions for:

1. concretization - choosing the default version if none is specified
2. dependency resolution - does version X satisfy `@1.2:`
3. sorting - when you print out available versions, what order do they appear in

Your first two ideas allow us to be more specific about usage 3, but it sounds like we would still have to rely on the current sorting method (or something like it) to get usage 2. And in terms of usage 1, would you put `develop` first so that Spack knows it is newer, or would you put it last so that Spack knows not to choose it by default?

Basically, I don't think ideas 1 and 2 are enough to address the problem at hand. We could combine them with other ideas though. I know you don't want me to shoot down any ideas, but I would like to shoot down idea 2. It is more explicit than idea 1, but provides a headache every time a new version is added.

One way we could combine these ideas is as follows. Idea 1 could be used solely for concretization and sorting. So when I run `spack info`, it prints out the versions in the same order as they appear in the package.py. And when I run `spack install` and no version constraints are specified, it chooses the first version listed. This could be used to replace `preferred=True` if we want. For example, Python could list `2.Y.Z` versions before `3.Y.Z` versions. But this is less explicit and would need to be documented well.

We still need a way of resolving dependencies, and specifically for solving the problem of past `develop` installations that may no longer be newer than the newest release. @tgamblin suggested a way of extracting the version from Git, which I think is worth considering if it's doable.

**Comment by citibeth** [comment]
> Some packages, especially licensed software like allinea-forge or pgi, have different downloads for each OS.

Can `url_for_version()` do the right thing in determining the correct URL?

> Can you elaborate more on this?

See: https://en.wikipedia.org/wiki/Total_order

Basically... if a set `X = {x1, x2, ..., xn}` is fully ordered under
the operator `<=` and `a` and `b` are members of `X`, then (in all
cases) either `a <= b` or `b <= a`.  Partial orders do not have this
property.

A concrete example: consider nodes in a Git DAG, A and B.  if A is a
descendent of B (meaning there is a path from A to B by following
parent pointers), then B <= A.  If B is a descendent of A then A <= B.
If neither is a descendent of either one (for example, A and B are
commits after having branched off of some common ancestor C), then you
can't say that A<=B or B<=A.  Neither one is "greater" than the other.

Partial orders are natural in VCS systems.  If we can figure out how
to work with them in Spack, more natural and obvious ways to do what
we want will open up.  For example, an ability to pull useful version
information right out of a Git repo.


>  Basically, I don't think ideas 1 and 2 are enough to address the problem at hand

I consider all the ideas 1-5 to be "homomorphic," i.e. essentially equivalent from a fundamentals perspective.  They differ mainly in their UI.  But I agree, they are not enough to address the problem at hand:

1. You brought up version ranges --- in which users are allowed to talk about versions that are NOT listed in the Spack package.  This could be solved in one of several ways, most simply by diallowing it (although I don't think we want to do that, since then things like `python@3:` wouldn't work).

2. There's still the problem of moving version targets.  I'd like to see if we can find something that solves all our versioning issues, not just the easy ones.

Pluggable Version Schemes
-------------------------

I suggested above that version schemes work on a per-package basis.  This is not so much a solution as a meta-solution.  But it would allow us to move forward and experiment with different things for different cases.

**Comment by adamjstewart** [comment]
> > Some packages, especially licensed software like allinea-forge or pgi, have different downloads for each OS.

> Can url_for_version() do the right thing in determining the correct URL?

Kind of. Let me open up a sample PR to show you what I think the best solution is for that particular problem. It's hard to explain otherwise.

**Comment by citibeth** [comment]
BTW, here's some fun I just discovered in `lua-luafilesystem`:

```
   homepage = 'http://keplerproject.github.io/luafilesystem'
    url = 'https://github.com/keplerproject/luafilesystem/archive/v_1_6_3.tar.gz'

    version('1_6_3', 'd0552c7e5a082f5bb2865af63fb9dc95')
```

**Comment by adamjstewart** [comment]
I was just thinking about this while working on #2062. I prefer versions like `1.6.3` for uniformity, so maybe we should change it to dotted and create a `url_for_version()` that uses `versions.underscored`.

But then I started thinking about how if you force it to be dotted and run `spack versions` or `spack checksum`, it will show new versions like `1_6_3` in addition to the `1.6.3` that is already in Spack. Not ideal either...

**Comment by alalazo** [comment]
Closing, since the most current discussion is in #26557
