### ISSUE TITLE
Load Modules for Build

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2086]
This would fix #2085 and might affect #2055 as well.  The proposal is...

When installing package `xyz`, set up the environment by loading all the modules listed in `spack module loads xyz` before running the `install()` procedure.  This is in contrast to the current system, where the build environment is set up "by hand," based on assumptions on how installed Spack packages work.

I expect this proposal would have little or no discernable effect for most Spack packages that install standard compiled code.  But it would really improve (for example) a lot of Python builds.  See #2085 for details...

**Comment by citibeth** [comment]
@tgamblin @alalazo

**Comment by pramodk** [comment]
@citibeth : Will this fix #2056 ? Today if I specify `modules` in `packages.yaml` or `compilers.yaml`,  I always have to use `--dirty` flag!

**Comment by tgamblin** [comment]
@citibeth: I don't want to do this because it would make Spack depend on modules.  We have a general mechanism for environment settings in @alalazo's `EnvModifications` in `modules.py`, and I think the better solution would be to add tests that ensure that _that_ is always doing the same thing as modules.  Validating module behavior in tests, I think, is better than actually requiring them to use Spack.

I think this is tricky, because there are several places where we want to validate that Spack and modules are doing the same thing.  I *think* what you are asking for here is to make sure that every setting produced by a spack-generated module is *also* included in the build environment for dependents of the module's package.  Is that right?  This is a good default but I am not sure we want it in all cases... I would need to think about that more.

**Comment by citibeth** [comment]
Maybe

**Comment by citibeth** [comment]
Yes, that is what I'm asking for.  If it's not the right thing for all
cases, we can add the exceptions when needed.
