### ISSUE TITLE
Per-Project Scope

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2171]
In addition to the configuration scopes introduced in #2152 we also need a project scope.

Typical use case... I'm building two software stacks with different version/dependency selections in them. Or I want to run an integration test with a packages.yaml different from my "normal" one. Suggested ways to find the project scope would be:
1. An env var
2. A command line argument. (This would have to be available on all commands, ideally parsed and set up before the command is run. So then one could alias myproject-spack 'spack --config ~/myproject/dotspack'
3. Search up the source tree for a dotspack directory.

I would lean toward (2) as probably the best way to do this. As long as the Bash alias works, users can easily set up as many per-project Spack-like commands as they need.

@tgamblin Do you have any preferences of how the per-project scope would be specified --- or maybe something different from 1,2,3 above?

**Comment by tgamblin** [comment]
I edited the original post for formatting since 1, 2, 3 got munged.

I think this is related to Spack bundle support, #1926.  

I like 2 and 3, but I think they're two separate scopes. I think 3 is most important but 2 should take precedence, so the final precedence would be:

1. defaults
2. site settings
3. user global settings
4. project settings
5. command line settings

This is not dissimilar to what git does with its preferences -- each project can have a `.git/config`, and you can also specify `--git-dir` on the command line if you want to completely swap `.git` directories, or `-c key=value` if you want to specify a single config option.

I like (3) as I was hoping that there could be a per-project scope that actually gets *versioned* with a repository, since I think that is important.  So, there might be a `.spack` directory or a `Spackfile` at the top level of your project, and you can put Spack configuration and dependency requirements in there.  We could allow a single file for this since all the config scopes start with keys like `packages:`, `config:`, `compilers:`, etc.  Some of our code teams want functionality like this and we should flesh it out.

I am not sure there is a clear separation right now between what you do and don't want to check into a repository.  For example, I *know* our code teams want to check their compiler settings in to use with a particular project.  And they need that right now because there's no good place to query system-by-system compiler locations.

Anyway, I think this issue enumerates the options... I just think we should hash this out carefully so that we build something a lot of people want to use.

**Comment by citibeth** [comment]
OK, this is more involved than I imagined at first.

Maybe project-level configurations should be part of the repository.  (i.e. `builtin/configs` alongside `builtin/packages`).  This would make many things "just work," piggybacking on the infrastructure we already have to deal (eg) with multiple repositories: specifying them, allowing users to keep them in a separate repo, etc.  But this does beg the question of how the repos would be configured (maybe that's something that just can't be configured from project-level scope).

**Comment by tgamblin** [comment]
Closing as we have environments (#9612) and command-line scopes (#8560) now.
