### ISSUE TITLE
Fix PyPI Downloads --- The Right Way

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2281]
@alalazo @adamjstewart 

We can't do this for every crazy download site out there.  But PyPI is important and provides lots of stuff to Spack.  So let's get it right... here is the link describing their XMLRPC API:
    https://wiki.python.org/moin/PyPIXmlRpc

1. We can use this to create a `url_for_version()` method that will call the API's `release_urls(package_name, version)` to determine the download URL.  It should NOT download the checksum at install time, since the whole point is to CHECK it at install time.

2. This new `url_for_version` would come standard in the `PyPIPackage` base class.  Or... we provide it as a method and ask Package authors to write `url_for_version = pypi_url_for_version` as needed.

3. We can use the API to improve automagic generation of PyPI packages.  The auto-generator would query it for a bunch of URLs and checksums.  If we're clever enough with picking apart `package.py` files, we could even have a procedure that auto-updates a `package.py` file for new versions of the package.

**Comment by alalazo** [comment]
I think this relates somehow to #1249

**Comment by citibeth** [comment]
I see... I would say it does relate, but is less ambitious (and therefore more likely to get done in the near term).  I think the approach in this Issue would be a good first step toward #1249.

**Comment by adamjstewart** [comment]
Both of these proposals are very interesting ideas!

**Comment by adamjstewart** [comment]
I'm looking more at their documentation, and I'm wondering if we can get rid of the `version` directives entirely. Since the query returns a list of URLs, version numbers, and checksums, can we hack Spack to allow all PyPi versions to be available and checksummed?

**Comment by tgamblin** [comment]
@adamjstewart: The checksum needs to be in Spack so that you're not asking the same site you're fetching from for the checksum.  Otherwise it's just a download verifier and not a measure against attacks.  Also, if the checksum is not in the package, we can't verify packages fetched from a mirror on airgapped networks.

So we should keep the version directive.  However, we don't have to keep the URLs.  Why not make a `PyPIFetchStrategy`? Fetch strategies are identified by keyword arg names (git=, url=, hg=, etc.) in the version directive.  All spack would need, I think, is the *name* of the package on PyPI.  So:

```python 
version('1.4.5', 'afde3782863febc825', pypi='pypi-package-name')
```

You can inherit a property like that from the package, too, so we could just remove the `url` property and add `pypi`:

```python 
class PyFrobulator(Paclage):
    pypi = 'pyfrobulator'
    version('1.4.5', 'afde3782863febc825')
    version('1.3.2', 'febac6284d837efafc2')
    # etc
```

PyFetchStrategy would then implement the xmlrpc stuff behind the scenes.  Note that doing this as a fetch strategy would allow you to have some versions fetched from PyPI and others  (develop?) fetched from a separate location.  Making this part of PythonPackage would make that hard.

I think there was an outstanding bug with inheriting attrs other than URL and I can't remember if I fixed it so I may need to do that, but this should work.

Thoughts?

**Comment by adamjstewart** [comment]
I think a `FetchStrategy` makes perfect sense. I'll take a look and see what I can do. Btw, will that allow us to run commands like `spack versions` or `spack checksum` if we remove the url?

**Comment by tgamblin** [comment]
I think there may be some hard-coded reliance on packages using URLFetchStrategy in those commands, but I don't see why we couldn't move the url/list_url scraping stuff into a function on URLFetchStrategy, add the same function to the PyPI fetch strategy, and generalize the commands to call that.

**Comment by citibeth** [comment]
I had imagined a url_for_version() function that looks up on pypi to
construct the url, rather than concatenating strings.  Packages that want
to use it would write:

url_for_version=pypi_url_for_version('packagename')

no need for a new superclass.

**Comment by adamjstewart** [comment]
I think a new `PyPiFetchStrategy` is the way to go, but looking at the code I might be a bit out of my league. I'll see what I can do though. But it probably won't be a part of #2709 since it has nothing to do with the `PythonPackage` superclass.

**Comment by citibeth** [comment]
I'm thinking I'll make a function that does the dirty work --- and then we
can figure out how to integrate it.  I agree, the PyPiFetchStrategy looks
like probably the way to go.

But I'm still trying to understand it.. we have many fetch strategies, but
it seems that the system is biased to URLs via `url_for_version()`.  I'd be
happier if we had a system that were agnostic to fetch strategy AND
convenient for all of them.

**Comment by adamjstewart** [comment]
Working on this now. I think the only thing I need to override is `fetch()` if I subclass `URLFetchStrategy`.

**Comment by adamjstewart** [comment]
How do I access the version being requested from within a `FetchStrategy`?
