### ISSUE TITLE
internal BLAS/LAPACK in packages

### ISSUE THREAD

**Issue by davydden** [spack/spack#2392]
I was always of opinion that no package in Spack should try using some internally provided dependencies like BLAS/LAPACK (e.g. in SuperLU https://github.com/LLNL/spack/pull/2390). To me there is no difference between internal BLAS/LAPACK or internal dependencies like what PETSc can do (download Superlu-Dist, Hypre, Openmpi, Openblas, HDF5, etc). So if we don't encourage packages to do the latter (I think we all agree on that point), i see no reasons why we should allow using internal BLAS/LAPACK either.

The reason is always the same and applies to both cases: imagine what happens if you have a graph of packages which are used to build something. All packages in the DAG are build as shared libraries, and each use it's own BLAS, some 32bit, some 64bit, some with threading, some without, etc. It defeats the whole beauty of Spack which guarantees that only one version of package is used within the DAG.

So if there is a collective agreement not to allow usage of internal BLAS/LAPACK (and any other dependency for that matter), then

- it should be documented in Packaging Guide
- current packages need to get rid of all variants which allow internal BLAS/LAPACK.

Thoughts?

**Comment by citibeth** [comment]
I agree in general.  But I want to make it clear that there are two bad things about using internal packages:

1. As @davydden pointed out, it messes with Spack, in case there are other things that need the same package, etc.

2. Sometimes, upstream builds try to download the "internal" package during their build.

(2) is a problem because Spack needs to work on Internet-isolated clusters, because it's not cached, etc.  All downloads should happen through Spack's regular download or resource mechanisms.

As long as an internally-provided BLAS/LAPACK is built as a static library and doesn't involve any Internet activity, I think that changing it would be a low priority.

**Comment by alalazo** [comment]
Closing the discussion for lack of activity. Feel free to reopen if you disagree.
