### ISSUE TITLE
py-h5py is sometimes installed without a listed dependency on py-cython.

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#2448]
`py-h5py` depends on `py-cython` as described in it's `package.py` file.

If you take a clean spack installation and just install `py-h5py` with `spack install py-h5py`, `py-cython` is installed but `py-h5py` is installed without any dependence on `py-cython` somehow.

You can see this here after I install `py-h5py` in an empty spack installation:

```
spack find -d py-h5py                
==> 1 installed packages.
-- linux-arch-x86_64 / gcc@6.2.1 --------------------------------
    [+]  xe5msgwjlcwb5ogz6qbiakgpwub5gbgn  py-h5py@2.6.0
    [+]  nxdxelzwt4yasq5fr5smvl5rp2fm2qfj      ^hdf5@1.8.16
    [+]  il64wykvgxfwr4ekwx5uw5elznkt7ru2          ^mpich@3.2
    [+]  5yu5k2tmrdaqp3au25mxtatpolxzoifc          ^szip@2.1
    [+]  muw275cludcbyfss3qhrwfdgqzyawobo          ^zlib@1.2.8
    [+]  a3pmovb6xdl7iaicmkjavsq22l7nlhaa      ^py-mpi4py@2.0.0
    [+]  af6yvqzowdwsgobjttgaprjxoiqn77xb          ^python@2.7.12
    [+]  mqtezjgupjgsgmbgekm7uyo4trg6ixng              ^bzip2@1.0.6
    [+]  3zob25ylu6v2lfipkjm7lutux2gybije              ^ncurses@6.0
    [+]  edfjjophrb5mctxwwabuwogkyhbeustr              ^openssl@1.0.2j
    [+]  hwzccevopyg7wep3hgypvoa25rqhasas              ^readline@6.3
    [+]  k7pl5saz7okbaxxkwru7o2utyqehxw4a              ^sqlite@3.8.5
    [+]  jgzx5mzs2oakd5npr4dnkgt3frvpbeoq      ^py-numpy@1.11.2
    [+]  443ize6rvixorrj5ftlz4brlmju2lrfq          ^openblas@0.2.19
    [+]  3vhn2rov67fp2kobqkqvvuwyszmpbu3m      ^py-six@1.10.0
```

But `py-cython` definitely was built and installed:

```
spack find -d py-cython
==> 1 installed packages.
-- linux-arch-x86_64 / gcc@6.2.1 --------------------------------
    [+]  5g2bnwt4birzhzznoxsoqykaahxab7lm  py-cython@0.23.5
    [+]  af6yvqzowdwsgobjttgaprjxoiqn77xb      ^python@2.7.12
    [+]  mqtezjgupjgsgmbgekm7uyo4trg6ixng          ^bzip2@1.0.6
    [+]  3zob25ylu6v2lfipkjm7lutux2gybije          ^ncurses@6.0
    [+]  edfjjophrb5mctxwwabuwogkyhbeustr          ^openssl@1.0.2j
    [+]  muw275cludcbyfss3qhrwfdgqzyawobo              ^zlib@1.2.8
    [+]  hwzccevopyg7wep3hgypvoa25rqhasas          ^readline@6.3
    [+]  k7pl5saz7okbaxxkwru7o2utyqehxw4a          ^sqlite@3.8.5
```

Strangely, `py-cython` is missing as a dependency, and even stranger, if you install a package that depends both on `py-cython` as well as `py-h5py` like `py-astropy`, it will install _another_ `py-h5py` which _does_ have a dependence on `py-cython`. 

No idea why this happens.

**Comment by JaroslavHron** [comment]
`py-h5py` has `py-cython` as `'build'` dependency type only, that means it is used in build process only.
(see. [py-h5py/package.py#L44](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/py-h5py/package.py#L44))

`py-astropy` has `py-h5py` as `nolink=('build','run')` dependency type
(see. [py-astropy/package.py#L44](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/py-astropy/package.py#L44))

I think this problem was observed for example here #1831 that the dependency type specification is taken from the package being installed?

So yes, installing `py-astropy` will have `py-h5py` with `py-cython` dependency type `('build','run')`
while installing `py-h5py` will have `py-cython` dependency type only `('build')`

**Comment by adamjstewart** [comment]
@mathstuf @tgamblin 

I don't like this behavior. Specifically, we shouldn't be installing another `py-h5py` here.

**Comment by alalazo** [comment]
@adamjstewart I don't think we install `py-h5py` twice according to the description above. Rather the `py-cython` dependency doesn't get listed on `spack find` because it's build only. 

I just tried using `spack spec` on `py-h5py` and `py-astropy` and didn't notice any wrong behavior, so I am closing this. Feel free to reopen if I missed something.
