### ISSUE TITLE
Better Compiler Support

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2469]
This thread is to further discuss the ideas about compilers and variants that arose in this thread:

https://groups.google.com/forum/#!topic/spack/rl2OSwhj1cE

**Comment by tgamblin** [comment]
@TomasPuverle:
> I think the virtual "standard" dependency is a great idea.  Having said that, as you will no doubt know, different compilers - particularly in the C++ world - tend to have varied/incomplete support for C++ standards.  As such, rather than specifying a C++ standard, it would also be useful to be able to specify a list of supported compiler versions.  One way I was thinking about this would be to introduce variants for compilers, too, perhaps like this:
> ```
> depends_on('gcc@4.9.2:', when = 'cxx_compiler=gcc')
> ```
> The %<comp> syntax could then be re-purposed to really imply %cxx_compiler=<comp> internally.  This suddenly brings in the notion of "propagated variants", which a number of people have proposed (i've read a number of these both here and on github).  

I like the ideas from the original thread about propagated variants.  I think that rather than propagating compiler versions, though, we could do this by allowing variants on virtual dependencies and using them to specify language features, e.g.:

```python
    depends_on('cxx+lambda+atomic')
```

This way the packager neither has to memorize standard versions, nor levels of support in particular compiler versions, and the specification is very clear.  Spack compilers could add things like:

```python
    provides('cxx+lambda+atomic+threads+whatever', when='@4.9.3:')
```

I am not sure why the variants necessarily need to be propagated down the DAG in this case, though.  If *this* package needs `+lambda`, it doesn't necessarily need to link against a library that was built with lambda support, right?  I haven't gotten enough into the details of compatibility across `libstdc++` versions, but this is actually something we could work into the concretization rules once Spack supports slightly more sophisticated compiler dependencies.

We are thinking about modeling compilers as build dependencies that "impose" link dependencies on the generated binaries.  i.e., if you build with `gcc`, you also have to have a dependency on its `libstdc++` version, which has to be compatible with other such `libstdc++` versions in the DAG.  As long as two compilers use the same `libstdc++`, we can link (this is a narrow example that doesn't include all the runtime baggage compilers carry around, but maybe you get the idea).  We implement that in a kludgier way right now in `abi.py`.

**Comment by TomasPuverle** [comment]
@tgamblin 

Todd,

Thank you for your response.  As I was writing my original suggestion, I too considered not relying on compiler versions but rather on specific features, in almost an identical way to what you suggest, and had even drafted my original email along similar lines.  As such, I am happy to see that you are also considering it.  However, let me tell you why I, ultimately, rejected the idea and decided not to mention it at all:

1. The fact that a feature is "present" doesn't really mean that it's complete.  Since you mention lambdas, I have no doubt you know that the papers and implementation went through a number of phases.  For example, what would "lambda" imply for C++?  The initial lambda specification?  The subsequent implementation for generic lambdas?  Or the part where named lambda captures along with move semantics were added?  Another example would be constexpr: Is this the initial, C++11 restricted version? Or the more permissive C++14 version?  C++ 17 constexpr if?  I hope you can see that this road is strewn with more problems than it solves.
2. Even if a feature is in the compiler, is can be incomplete/buggy.  All compilers do it; especially during the time when the standard hasn't been completely ratified yet.  For example, for a long time, MCVC++ supported "move semantics v1" but not the full C++ specification.  What may work for my code may expose an ICE in your code.  I believe this way lies madness.
3.  There is already a fairly well understood system of handling such discrepancies; cmake, waf, autotools etc. all have feature detection capabilities.  In addition, the new C++ standards support "feature detection" directly in the language now.  I think trying to push this into spack is a step too far.  I've never really talked to any experienced C++ developers who really think of individual "features"; they consider their problems as a whole, and use the available features to solve their problems.  And as much as it  "offends the purity" of the specification, I think the compiler and its version is the clearest and most ubiquitous way among C++ developers to communicate what may or may not work in the given toolset.
4.  As you've already mentioned yourself, there is also the difficulty of specifying that a library which uses "+lambda" is perfectly fine as a dependency for another which doesn't.  I think such a system would eventually be useful in the long term (e.g. "don't worry spack, I am telling you that this debug-enabled library is a perfect substitute for the optimized version"), but right now it does appear like unnecessary complication.

As for standard libraries, I would *love* to see the support for it; as you are no doubt aware, clang supports two different standard libraries.  And while this is not the area of my expertise, I know that many embedded developers use specialized versions of the standard library which changes how exceptions (if any), memory allocation etc are handled.  Out of the embedded space, many game development studios, in a similar effort, rely on specialized standard libraries, too - electronicarts/EASTL being an example.  With compilers being specified as packages, I feel this problem would be "trivial" in the sense that it would get handled in the same way spack handles all other types of contretization.  As an aside, this would allow the handling of other "variants" of the compiler in the same way (static vs dynamic runtime lib, exceptions on/off, etc)

Kind regards,

Tom

**Comment by becker33** [comment]
Closing in favor of #31357
