### ISSUE TITLE
Allow spack create to handle already downloaded tarballs

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2545]
We should make `spack create` work with already downloaded tarballs. This is useful for licensed software. I don't see any reason why it wouldn't work. For some reason, fetching fails currently.

**Comment by tgamblin** [comment]
@adamjstewart: can you post a use case?  Questions:

1. If the package doesn't exist yet, how would there be tarballs for it in `var/spack/cache`?  Is this just for when you're re-creating a package that existed before?
1. Is this for packages that maybe share tarballs with other packages?  The fact that the cache is a mirror means the tarballs are stored per-package, so if two packages share a tarball, they'll be duplicated within the per-package mirror directories (`var/spack/cache/pkg1/foo.tar.gz`, `var/spack/cache/pkg2/foo.tar.gz`, etc.).  We could, of course, cache by hash.  But then mirrors are hard to make, or at least unintuitive.  Right now, a human can pretty easily give a mirror tarball the right name.
1. Or (maybe I get it now), you want spack create to just take a tarball as a parameter because you have it lying around already?

**Comment by adamjstewart** [comment]
@tgamblin Yes, 3 is the use case. I'm trying to create a package for MATLAB, and I had already downloaded a tarball for it. `spack create /path/to/tarball.tar.gz` was unable to fetch the tarball, so it couldn't create a template for me. I think this is a common problem when trying to create new packages for licensed software.

**Comment by Piping** [comment]
Hi, I want to have this feature so that I can zip the directory that was setup by current internet connected machine and unzip at offline machines.

**Comment by adamjstewart** [comment]
@Piping the feature I'm proposing here is only for creating new packages, the feature you're looking for already exists. `spack mirror` lets you download tarballs for all of your software, then you can move them to an air-gapped network and run `spack install` using that mirror.

**Comment by Piping** [comment]
@adamjstewart I see. Thanks.

**Comment by becker33** [comment]
@adamjstewart do you think that using a file url (and then editing the template to `manual_download = True` instead) is a sufficient solution, or do you want to keep this open for a cleaner solution than that?

**Comment by adamjstewart** [comment]
I think file URLs are an okay workaround, but it would be even better if a filesystem path was automatically converted to a file URL. Note that this issue is low priority, it doesn't happen often and it only impacts developers.

**Comment by becker33** [comment]
You can directly pass a path to `spack create` already (I discovered when I went to implement it). I'll close this issue.
