### ISSUE TITLE
conflicting variants

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#267]
We can get a conflict when trying to install a package that has dependencies that themselves depend on different variants of a dependent package. For instance:

[lee218@hype2:spack]$ spack -v install py-basemap
==> Error: Invalid spec: 'libxml2@2.9.2%gcc@4.8.5~python=chaos_6_x86_64_ib^xz@5.2.2%gcc@4.8.5=chaos_6_x86_64_ib^zlib@1.2.8%gcc@4.8.5=chaos_6_x86_64_ib'. Package libxml2 requires variant +python, but spec asked for ~python

The underlying problem is that the mesa package requests libxml2+python, while qt and fontconfig just request libxml2. I can work around this by explicitly requesting "py-basemap^libxml2+python".

**Comment by mathstuf** [comment]
Related to #593.

**Comment by mathstuf** [comment]
See also #839.

**Comment by rashawnLK** [comment]
Hello,

I think this is related to what I am seeing with recent attempts to install STAT. If I should post this in response to another issue, please let me know.

I am experiencing all kinds of grief trying to install STAT 4.0.1 with my own installed Python 3.6.5,  gcc 8.3.0, and MPICH, while asking Spack to install Dyninst 10.1.0 and specifying stat 4.0.1 + examples in my packages.yaml. My installation line is this:
`spack -C ${confs} -d install -v stat@4.0.1 %gcc@8.3.0 2>&1 | tee logs/2020_0225_stat-4.0.1_gcc-8.3.0_python3_mpich-gnu32_spack-01.out`


I am using Spack version 0.14, and the error is:

` spack.variant.UnsatisfiableVariantSpecError: An unsatisfiable variant constraint has been detected for spec:

    ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=linux-sles15-skylake_avx512
        ^pkgconf@1.6.3%gcc@8.3.0 arch=linux-sles15-skylake_avx512


while trying to concretize the partial spec:

    llvm@6:
        ^cmake@3.14.3%gcc@8.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-sles15-skylake_avx512
        ^perl-data-dumper
            ^perl@5.30.1%gcc@8.3.0+cpanm+shared+threads arch=linux-sles15-skylake_avx512
                ^gdbm@1.18.1%gcc@8.3.0 arch=linux-sles15-skylake_avx512
                    ^readline@8.0%gcc@8.3.0 arch=linux-sles15-skylake_avx512
                        ^ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=linux-sles15-skylake_avx512
                            ^pkgconf@1.6.3%gcc@8.3.0 arch=linux-sles15-skylake_avx512


llvm requires ncurses variant +termlib, but spec asked for ~termlib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rlknapp/sources/spack-repo7-stat-poc/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/rlknapp/sources/spack-repo7-stat-poc/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/home/rlknapp/sources/spack-repo7-stat-poc/spack/lib/spack/spack/cmd/install.py", line 315, in install
    args.spec, concretize=True, tests=tests)
  File "/home/rlknapp/sources/spack-repo7-stat-poc/spack/lib/spack/spack/cmd/__init__.py", line 161, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: An unsatisfiable variant constraint has been detected for spec:

    ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=linux-sles15-skylake_avx512
        ^pkgconf@1.6.3%gcc@8.3.0 arch=linux-sles15-skylake_avx512


while trying to concretize the partial spec:

    llvm@6:
        ^cmake@3.14.3%gcc@8.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-sles15-skylake_avx512
        ^perl-data-dumper
            ^perl@5.30.1%gcc@8.3.0+cpanm+shared+threads arch=linux-sles15-skylake_avx512
                ^gdbm@1.18.1%gcc@8.3.0 arch=linux-sles15-skylake_avx512
                    ^readline@8.0%gcc@8.3.0 arch=linux-sles15-skylake_avx512
                        ^ncurses@6.1%gcc@8.3.0~symlinks~termlib arch=linux-sles15-skylake_avx512
                            ^pkgconf@1.6.3%gcc@8.3.0 arch=linux-sles15-skylake_avx512


llvm requires ncurses variant +termlib, but spec asked for ~termlib`

What is the best way for me to resolve this?  I spent some time fiddling with the spack.py file for ncurses, changing the default to True for the variant, but I ran into errors with that. It seems that termlib shoud be built prior to LLVM so that it is available when the LLVM build happens.  Will I need to build termlib in a separate step and specify it's location to Spack?

Best regards,

-Rashawn

**Comment by scheibelp** [comment]
Hi @rashawnLK https://github.com/spack/spack/issues/267#issuecomment-591201208 is definitely an instance of this bug, but there is a more-specific report at https://github.com/spack/spack/issues/14793. You can resolve this particular case by adding `^ncurses+termlib` like 

```
spack -C ${confs} -d install -v stat@4.0.1 %gcc@8.3.0 ^ncurses+termlib 2>&1 | tee logs/2020_0225_stat-4.0.1_gcc-8.3.0_python3_mpich-gnu32_spack-01.out
```

We are also working on a patch that would make it so you don't have to do that.

**Comment by rashawnLK** [comment]
@scheibelp, this is good news that I can go forward with the command line work-around an that a patch is in the pipeline. Thank you for your speedy response.

-Rashawn
