### ISSUE TITLE
Need a method of blacklisting compilers for packages

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2795]
Some packages cannot be built with certain compilers. For example, I am unable to build `openssl`, `libpciaccess`, `bison`, `ncurses`, and `pkg-config` with the PGI compilers. This is not Spack's fault, the packages contain sloppy code and PGI is more strict than GCC. NAG is even more strict, and has a much larger list of packages that it cannot build.

I need to build a software stack including MPI, HDF 4/5, NetCDF, and pNetCDF with 4 different compilers, including PGI and NAG. But all of these unbuildable packages are picked up as dependencies. I would like to build these dependencies with GCC instead. So how can I do that?

One way is to manually put `^libpciaccess%gcc ^bison%gcc ^ncurses%gcc ... etc.` on the install line every time I build them. This is tedious, but it should work. Except it doesn't due to the bug reported in #2786.

But that option is still tedious and can't be shared with other users. Is there a way we could do this in our existing framework? One way would be to put something like:
```yaml
packages:
  libpciaccess:
    compiler: [gcc, intel, nag]
```
in the default `packages.yaml`. This would mean build with gcc or intel if we are using those compilers, or build with gcc if we are using pgi. But this is also broken (see #1371)

So at this point, I've had to comment out all of those dependencies from the packages I need to install. Luckily they are available on the system. But a better solution would be much appreciated.

**Comment by tgamblin** [comment]
I think we need `conflicts()`, `prefer()`, and `require()` directives for things like this.  `require()` would be like `depends_on()` but for self constraints, which at the moment is mostly compiler stuff but it could grow to things like:

```python
require('+foo', when='+bar')
```

I think `conflicts()` is fairly obvious.  Most package managers have some form of this directive but we've gotten away with it so far because `conflicts` is usually about version mismatches, and Spack can usually just build a new version to avoid a conflict.  `prefer()` would be a soft version of require.  Thoughts?  I could try to tackle this stuff along with the new concretizer; it's related.

Another thing I've thought about would be some way to list a matrix of preferred versions of dependencies for different versions of a package. Right now we don't have a great syntax for that.  e.g. the ROSE compiler has preferred versions of `boost` and compilers depending on its version.

Putting things in the defaults config scope would be a good workaround for some of this in the meantime.

**Comment by eschnett** [comment]
I would like this for operating systems as well: `conflicts_with("gcc", "darwin")`.

**Comment by tgamblin** [comment]
This would probably look like: 

```python
conflicts_with('%gcc', when='os=darwin')
```

**Comment by adamjstewart** [comment]
Yes, I believe Homebrew has something similar. So it sounds like we should either put these things in `compilers.yaml` or put them in the `package.py` files themselves. The former is simpler and already works (once it is fixed) but the latter is probably much more obvious to people and would explain why Spack is using a different compiler all of a sudden.

**Comment by adamjstewart** [comment]
Is there any progress on this issue? I once again need to install that nasty MPI/NetCDF/PnetCDF/HDF4-5 stack with 2 different versions of PGI. Guess I'll have to comment out all of the dependencies again...

**Comment by alalazo** [comment]
@tgamblin @adamjstewart I may have time next week to take a stab at the `conflict` directive, if it is fine with everybody. My plan is to make it a validation step after concretization, the rationale being that concretization should not be affected by a conflict (like e.g. access specification in languages that permit it doesn't affect which name is looked up). Does this sound good? If so I'll create a new issue for that.

**Comment by citibeth** [comment]
I like this idea.  My only note is that implementing these directives, and using them effectively in the concretizer, are two different things.  I would prefer that we implement them in a "simple" way sooner, rather than later --- i.e. they get implemented, but the concretizer ignores them.  At the end of concretization, Spack will give an error if the constraints are violated.  I know this sounds lame; but it is effective what we have right now, with these constraints hand-coded in `install()` methods.  And it mostly works.  So we will gain and not lose if we do the simple implementation now.

**Comment by alalazo** [comment]
> I like this idea. My only note is that implementing these directives, and using them effectively in the concretizer, are two different things. I would prefer that we implement them in a "simple" way sooner, rather than later --- i.e. they get implemented, but the concretizer ignores them. 

I would say more than that. **Conflicts must be ignored by the concretizer** otherwise we will start to see weird behaviors where specs that used to concretize one way will continue to work after a `conflicts` has been added (but will install something completely different).

---

I see a parallel example in the C++ language, with overload resolution taking the part of concretization and access specification of conflicts. Declaring something `private` where before it was `public` may trigger an error, but it never changes the way overload resolution is done.

**Comment by alalazo** [comment]
I'll close this as conflicts were added in #3125
