### ISSUE TITLE
spack extensions broken

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2895]
Last I remember, running `spack extensions python` printed a list of installed Python extensions and a list of activated Python extensions. Now it simply prints:
```
$ spack extensions python
==> python@2.7.13%clang@8.0.0-apple~tk~ucs4 arch=darwin-sierra-x86_64 -ckrr4mg has no extensions.
```

**Comment by scheibelp** [comment]
I'll try to look into this by the end of 4/21

**Comment by scheibelp** [comment]
This occurs because the provided spec is disambiguated right off, so in the first phase when Spack checks for possible extensions it doesn't find any because the disambiguated spec is too specific (the next two phases seem to work fine), and it exits early because it decides there are not possible extensions.

For now I'm going to wait on https://github.com/LLNL/spack/pull/3227 to create a PR for this (which I am reviewing).

**Comment by adamjstewart** [comment]
Ping @scheibelp.

@tgamblin @alalazo Can this be added to a milestone?

**Comment by scheibelp** [comment]
Thanks for the ping!

This was fixed by https://github.com/spack/spack/pull/5415 and https://github.com/spack/spack/pull/5600. Feel free to reopen if it comes up again.

**Comment by adamjstewart** [comment]
Well look at that, it works like a charm now. Thanks @mathstuf! I'll update the list of Known Issues now that this has been fixed.
