### ISSUE TITLE
spack initial compiler detection issue at NAS

### ISSUE THREAD

**Issue by mathomp4** [spack/spack#2985]
All,

I recently decided to try using Spack to maintain my own packages/modules out at NAS, NASA's supercomputing site at Ames (note: expect many a bugfix for tcsh shell integration). However, the simple "git clone; spack install libelf" that is the "Hello World" of Spack fails:

```
(3) $ spack install libelf 
==> Installing libelf
==> Fetching http://www.mr511.de/software/libelf-0.8.13.tar.gz
######################################################################## 100.0%
==> Staging archive: /nobackupp9/gmao_SIteam/spack/var/spack/stage/libelf-0.8.13-iotm5hoaoi7bqgidhelltsr3we6si5y6/libelf-0.8.13.tar.gz
==> Created stage in /nobackupp9/gmao_SIteam/spack/var/spack/stage/libelf-0.8.13-iotm5hoaoi7bqgidhelltsr3we6si5y6
==> Ran patch() for libelf
==> Building libelf [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/nobackupp9/gmao_SIteam/spack/var/spack/stage/libelf-0.8.13-iotm5hoaoi7bqgidhelltsr3we6si5y6/libelf-0.8.13/configure' '--prefix=/nobackupp9/gmao_SIteam/spack/opt/spack/linux-sles11-x86_64/gcc-4.3.4/libelf-0.8.13-iotm5hoaoi7bqgidhelltsr3we6si5y6' '--enable-shared' '--disable-dependency-tracking' '--disable-debug'
/nobackupp9/gmao_SIteam/spack/lib/spack/spack/build_systems/autotools.py:268, in configure:
     261      def configure(self, spec, prefix):
     262          """Runs configure with the arguments specified in :py:meth:`.configure_args`
     263          and an appropriately set prefix.
     264          """
     265          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     266  
     267          with working_dir(self.build_directory, create=True):
  >> 268              inspect.getmodule(self).configure(*options)

See build log for details:
  /nobackupp9/mathomp4/scratch/spack-stage/spack-stage-xygf38/libelf-0.8.13/spack-build.out
```
I did a bit of sleuthing around and I think the reason it fails is because of the compilers.yaml that spack autogenerated:
```
(4) $ cat ~/.spack/linux/compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles11
    paths:
      cc: null
      cxx: null
      f77: /usr/bin/gfortran-4.3
      fc: /usr/bin/gfortran-4.3
    spec: gcc@4.3.4
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles11
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@4.3
    target: x86_64
```
When it tried to build libelf, it chose to use gcc@4.3.0 which, indeed, does not have a very useful C compiler "null". So, I'm guessing I could easily fix this by hand-editing this file to combine the two compilers into one. I'm more concerned about why Spack did this in the first place. Any ideas?

Matt

**Comment by adamjstewart** [comment]
> So, I'm guessing I could easily fix this by hand-editing this file to combine the two compilers into one.

Yep, that would fix your problem.

> I'm more concerned about why Spack did this in the first place. Any ideas?

Take a look at `lib/spack/spack/compiler.py`. I believe the relevant function is `_find_matches_in_path`. There could be two things going on here:

1. Spack doesn't group compilers with suffixes (gfortran-4.3) with compilers without suffixes (gcc)
2. Spack doesn't group compilers of different version (4.3 vs 4.3.4)

**Comment by mathomp4** [comment]
@adamjstewart Okay. Next question. Pursuant to (closed) issue #2932 (which I found while searching around), what would be the "best" way to hand-hack this? Should I hand edit `~/spack/linux/compilers.yaml`? Or move that file to `~/spack/compilers.yaml` and then edit?

**Comment by adamjstewart** [comment]
@mathomp4 It doesn't make a difference.

The problem that leads to #2932 is that `spack compilers find` automatically puts things in `~/.spack/linux/compilers.yaml` while `spack config edit compilers` opens up `~/.spack/compilers.yaml`. Both are perfectly valid scopes. The problem is that the two commands aren't consistent in their default scope.

**Comment by citibeth** [comment]
> The problem that leads to #2932 is

@tgamblin  @adamjstewart Do you know how to fix this problem of inconsistent scopes?  I gave a tutorial 1 week ago --- and now 2 out of my <10 students have fallen into this trap.  It's embarassing, and risks alienating new users.

@mathomp4 My suggestion is to remove ~/.spack/linux and hand-edit ~/.spack/compilers.yaml to be correct.  There is debate about whether it's better to have this automagic that sometimes fails --- or to just tell users to set up their compilers before running Spack for the first time.

Why did Spack think you have two partial compilers?  Probably because the suffixes of `gcc` and `gfortran-4.3` don't match.  I assume that whoever installed this on NAS thought it was a good idea?

**Comment by adamjstewart** [comment]
> My suggestion is to remove ~/.spack/linux and hand-edit ~/.spack/compilers.yaml to be correct.

I would actually suggest the opposite. Otherwise, every time you run `spack compiler find`, you will end up with duplicated compilers and concretization will fail (see #2164). With these inconsistent scopes, you basically have to either do:
```
spack compiler find --scope user
spack config edit compiler
```
or
```
spack compiler find
spack config --scope user/linux edit compilers
```
With the former, if you forget the scope, you end up with duplicate compilers. With the latter, if you forget the scope, you just end up with an empty file.

P.S. Why does `spack config --scope user/linux edit` work but not `spack config edit --scope user/linux`?

**Comment by citibeth** [comment]
> I would actually suggest the opposite.

This is creating more trouble than it's worth.  99% of users use a single
Spack instance on just one OS.  They should be able to edit `~/.spack`
scope and ignore the fact that Spack can work in a multi-architecture
environment.

Either that, or get rid of `~/.spack`

**Comment by adamjstewart** [comment]
@citibeth I like to assume that most users add compilers via `spack compiler find` as opposed to vim/emacs.

**Comment by citibeth** [comment]
In this case, the `spack compiler find `automagic messed up.  How else do
we explain two partial compilers in the OP (one that has gcc and g++, and
one that has gfortran-4.3)?  The danger of automagic is it leaves users
cursing and helpless when it doesn't work.

**Comment by alalazo** [comment]
Closing as stale and probably fixed.
