### ISSUE TITLE
Add `-g` compiler flag in Spack Wrappers

### ISSUE THREAD

**Issue by citibeth** [spack/spack#3124]
What would others think if we (optionally) add the `-g` compiler flag in Spack wrappers?  This would ensure that debugging symbols are present in all Spack binaries.  Other than saving a little bit of HDD space (cheap these days), there is very little to be gained by NOT using `-g`.  And in modern compilers, it even gives useful information with higher `-O` levels.

How would such an option be implemented?

**Comment by alalazo** [comment]
I disagree with this. @svenevs Do you recall where we discussed this issue extensively? I can't find the  link to the discussion on the size of `llvm` and making `Release` the default for `CMakePackage` objects.

**Comment by scheibelp** [comment]
> Do you recall where we discussed this issue extensively? I can't find the link to the discussion on the size of llvm and making Release the default for CMakePackage objects.

There is discussion at https://github.com/spack/spack/pull/5261 and https://github.com/spack/spack/issues/5265 on that

**Comment by svenevs** [comment]
It started [about right here](https://github.com/spack/spack/pull/5261#issuecomment-326590176), with some continuation [over here](https://github.com/spack/spack/issues/5265).

@citibeth the general synopsis is that the debugging symbols being present give only a partial benefit (namely, no mangled names where CXX binaries are concerned).  However, given that the original source code has since been deleted, you still can't really do anything about it.

What might be interesting, though, and would greatly help facilitate things, is if `-g` took on a different form.

1. If possible, the special-case scenario of a `CMakePackage` would somehow `conflict` when `build_type=Release` and `spack install -g`.  I don't know if that is possible though.
2. What may be most useful is to make `-g` a little more heavy-weight.  Specifically, instead of using a stage directory and then installing, you build in the installation prefix in some specifically named folder.  Maybe hide it in `install_prefix/.spack/original_source`?

The idea for (2) is really just including in the installation of the built binaries the original (post-patching) source code.  I feel like there would be a much more clever way to achieve this by building in the normal place, and somehow automatically remapping the debugging symbols.  I think @pramodk may know more as to whether or not that is possible / how to do it?

@mwkrentel had noticed some things going on with autotools in #6096, and may also have some thoughts on this subject as well.

**Comment by citibeth** [comment]
Thanks, I've read the two threads.  Unfortunately, the synopsis is missing some important information.  Everybody debugs, but only some people use debuggers.  Reasons to not use debuggers include:
  a) Some programs are run by application-specific wrapper scripts that don't know how to launch with a debugger.
  b) MPI
  c) Writing out core files, and then reading them in with a debugger can be a big pain.
  d) Setting breakpoints that disappear with the end of your session can be a big pain; some find printf() statements to be easier in some cases.
  e) Debuggers can be slow and cumbersome
  f) The code works in the debugger (or without -O) but not in real life (with -O2)
  g) Debugging with -O2 can be challenging
  h) Debuggers (but not compilers) requires root access to install
  i) One more thing to figure out /master / fiddle with / keep working

The most efficient tool I have for debugging is the stacktrace.  That's really all I want, I don't want to step through the code line-by-line.  print() statements let me see what's going on inside, and are no easier or harder than setting watches in a debugger.  And they stay in my code until I rip them out when constructing my final Git check-ins.

All of this is a long way of saying... It is useful for me to compile everything with -g, whether or not the source code is sitting on my system or the debugger can find it.  When things crash in 3d-party library code, it's not hard to look it up on Github and see what's going on, even without ever downloading the source code.  And if I go deeper into the library, I'll probably end up downloading it, applying Spack Setup, and building it myself.

Sorry, nothing in the above discussions convinces me of the errors of my ways in the original request.  It just convinces me that debuggers require a lot of overhead effort to work their "magic," and that magic might not be worth the effort.

**Comment by svenevs** [comment]
> f) The code works in the debugger (or without -O) but not in real life (with -O2)

My personal favorite.  Always fun.......

I guess the corollary here: if you aren't using a debugger, what use are the debugging symbols?

In terms of `spack`, `CMakePackage` needs a way to conflict with this.  A `Release` build does a lot automatically behind the scenes, e.g. adding `-DNDEBUG`.  Adding a `g` in addition may cause dysfunctional code.  I don't think the other build systems are generic enough for this to be problematic, though it may potentially break specific packages.  I don't know enough about autotools to know what is / is not relevant in this discussion. 

In terms of binary sizes, it truly does make a difference.  It is more than just binary size, for which the `llvm` package is an excellent example.  It also greatly impacts performance, there's a reason why this flag is not included in a `Release` build.  I like to think of it as "the easier it is for me a human to read, the harder it is for a computer."  That's a gross over-simplification.

In addition, it has effects on overall compile time (specifically, linking).  The `llvm` case is extreme, but is an excellent example.  I literally couldn't even link it without creating a 10GB swapfile.

**Comment by citibeth** [comment]
> I guess the corollary here: if you aren't using a debugger, what use are
> the debugging symbols?
>

STACK TRACES!  Saves me oodles of time, and that's 95% of what debuggers
are good for anyway.  I've gone to effort to get stack traces EVERY TIME my
program exits, for whatever reason, without using a debugger; and then to
interpret those traces as lines in code, if the compiler's run-time system
didn't do so already:

https://github.com/citibeth/everytrace

> In terms of spack, CMakePackage needs a way to conflict with this. A
> Release build does a lot automatically behind the scenes, e.g. adding
> -DNDEBUG. Adding a g in addition may cause dysfunctional code.
>
I doubt that adding -g will ever break anything.  It's a legal compiler
flag, no matter what else CMake did.  You can also strip binaries without
affecting anything.

> In terms of binary sizes, it truly does make a difference. It is more than
> just binary size, for which the llvm package is an excellent example. It
> also greatly impacts performance, there's a reason why this flag is not
> included in a Release build. I like to think of it as "the easier it is
> for me a human to read, the harder it is for a computer." That's a gross
> over-simplification.
>
"Debugging symbols hurt performance" is a pure myth.  The image loaded into
memory is about the same with or without -g.  The debugging symbols just
sit there on disk, in case you need them.  See here for more technicals on
this issue:

https://stackoverflow.com/questions/5936181/gcc-g-vs-not-g-and-strip-vs-not-strip-performance-and-memory-usage

The ELF loader loads *segments*, not *sections*; the mapping from sections
> to segments is determined by the linker script used for building the
> executable.
> The default linker script does not map debug sections to any segment, so
> this is omitted.
> Symbol information comes in two flavours: static symbols are processed
> out-of-band and never stored as section data; dynamic symbol tables are
> generated by the linker and added to a special segment that is loaded along
> with the executable, as it needs to be accessible to the dynamic linker.
> The strip command only removes the static symbols, which are never
> referenced in a segment anyway.
> So, you can use full debug information through the entire process, and
> this will not affect the size of the executable image in RAM, as it is not
> loaded. This also means that the information is not included in core dumps,
> so this does not give you any benefit here either.

As for binary size... yes, binaries with -g can be bigger than binaries
without -g, something a LOT bigger.  I'm sure you can find a case where
this makes a difference. But for the typical HPC user with 4+Tb of HDD
space and data files 100-10,000x bigger than the compiled binaries they
use... it doesn't make any real-life difference.  If it does, you can
always strip them later (or not use the -g option in Spack to begin with).

> In addition, it has effects on overall compile time (specifically,
> linking). The llvm case is extreme, but is an excellent example. I
> literally couldn't even link it without creating a 10GB swapfile.
>
Can you find anything to back this up?

Even if everything you say is true... it's still not a good reason to not
include this feature in Spack.  It's just a good reason for YOU to not use
it, depending on your circumstance.

**Comment by alalazo** [comment]
Sorry for the noise, but:

> What would others think if we **(optionally)** add the -g compiler flag in Spack wrappers?

I missed the part in bold on first read. My opinion is that:

- Spack should come out of the factory with debug symbols disabled
- a user can in a very simple way (a line in `packages.yaml`?) turn debug symbols on for everything
- (bonus feature) if debug symbols are turned on we should put in some subdir of the prefix the sources and have binaries that point there

Sounds fine?

**Comment by svenevs** [comment]
> The ELF loader loads *segments*, not *sections*; the mapping from sections

Fascinating!

> Can you find anything to back this up?

Personal experience accidentally trying to install `llvm` after `+debug` was removed but before the `build_type` was set back to `Release`.  It took over 8 hours to compile, done twice because I needed to get the admins to add more swap to complete the linking phase.  To the best of my knowledge, `llvm` is the only package this is a concern for.

> - Spack should come out of the factory with debug symbols disabled
> - a user can in a very simple way (a line in packages.yaml?) turn debug symbols on for everything

I agree.  Maybe it would be as easy as just making a generic `extra_compile_flags` entry available?  That way people who want them on always can just put it on the `all` section, and just put a warning in the docs saying "if you supply flags in this entry and a package fails to build, first try removing the `extra_compile_flags`".  This way if people put in specific flags that do create a conflict (e.g. they ask for position independent code and the build system does the opposite), the blame is on the user.  This would solve the un-optomized autotools builds, people could just explicitly add e.g. `-g -O2`.

How would putting flags in the `packages.yaml` work with hashing though?  I feel like it would be "easy enough" to forward these to the compiler, but I think the hashing does not allow spaces.  That's an impression, not a fact.

Maybe the would-be PR would also set `CMakePackage` default to `Release` :laugh:

**Comment by citibeth** [comment]
>
>
> Personal experience accidentally trying to install llvm after +debug was
> removed but before the build_type was set back to Release. It took over 8
> hours to compile, done twice because I needed to get the admins to add more
> swap to complete the linking phase. To the best of my knowledge, llvm is
> the only package this is a concern for.
>

Sounds like your computer didn't have enough RAM to build LLVM efficiently
with debug symbols.  I suspect that with enough RAM to avoid swapping,
there would have been little or no discernable slowdown.  Still, point
taken... it looks like linking with debug symbols requires more RAM.

**Comment by mplegendre** [comment]
@citibeth, -g can have performance impact in some compilers because it can change the default optimization level (e.g., Intel defaults to -O2 without -g, and -O0 with -g).  I think debug flags also disable some optimizations in xlc (though I don't know if that's still true).  Otherwise you're correct that -g has no impact on the in-memory image.  

Unfortunately, disk space isn't yet cheap enough for some of our very-large codes where people are both building many copies and trying to fit into quota.  So we can't have an always-on or default-on -g.

But despite that I think a standardized and optional way to add -g to packages would be overall helpful.  It would be even better if we could keep source code so the line info mapping associated with that -g would be functional.

**Comment by svenevs** [comment]
Another thought occurred to me, if we enable two specific entries for `packages.yaml`:

- `extra_compiler_flags` maps to `CFLAGS` (shouldn't be a problem for CXX) in the build environment
- `extra_linker_flags` maps to `LDFLAGS` in the build environment

this would pretty much cover all bases.  For example, if you have a Xeon Phi cluster, there are likely many codes that you would like to run on them that do not explicitly consider these boards.  I think @balay was battling this in some other issues.  `extra_compile_flags` would allow him to add `-xCORE-AVX512`, or [one of the others](https://software.intel.com/en-us/articles/compiling-for-the-intel-xeon-phi-processor-and-the-intel-avx-512-isa).

The question: can these be compiler specific package settings?  I once set something up where we were using an anaconda installation of `clang` to compile various packages, and since we had to load a module to enable use of this for `compilers.yaml`, there were issues with linking.  So the solution was as simple as:

```yaml
packages:
    curl:
        paths:
            curl@7.52.1%clang: /share/apps/anaconda3
```

would there be a way to support something like

```yaml
packages:
    all:
        extra_compile_flags:
        - g
        - O2
    all%intel:
        extra_compile_flags:
        - xCORE-AVX512
```

A list makes it look somewhat like what you'd add to the command-line, and  makes it very flexible in terms of letting users specify exactly what they want (including just for a specific package).

**Comment by pramodskumbhar** [comment]
> extra_compile_flags would allow him to add -xCORE-AVX512, or one of the others.
>     all%intel:
>            extra_compile_flags:
>                 - xCORE-AVX512

need to consider here cross-compiling aspects and dependency types (because we don't want to pass above flag for build dependencies).

**Comment by HadrienG2** [comment]
Aside from stack traces, another major use case for RelWithDebInfo builds without source code is profiling. In profiling use cases, DWARF allows inline frame analysis and stack trace generation that survives the evil `-fomit-frame-pointer` compiler optimization, both of which are invaluable.

**Comment by citibeth** [comment]
You can already add extra compilers in Spack's compiler setup.  Would that
work?

**Comment by alalazo** [comment]
Closing as I think this can nowadays be solved by either specifying variants in `packages.yaml` or customizing flags in `compilers.yaml`. Feel free to reopen if there's some point people think it has not been addressed.
