### ISSUE TITLE
ncurses fails to install due to permission problem on a shared AFS file system

### ISSUE THREAD

**Issue by davydden** [spack/spack#3509]
we had a user who tried Spack and had a problem with installing ncurses https://groups.google.com/forum/?fromgroups#!topic/dealii/r7P682fTF7Y

I cross-post his message here in case there is something to be fixed in Spack. From the user's comment, i was not able to tell if that's the case or not. Feel free to reply to the original post if you think it's more appropriate, as well as close this issue if it is definitely not a problem with Spack.

The original message is below:

---

Hello,
I'm trying to install dealii on a shared AFS file system. Originally, I tried to install everything manually, which I had done successfully on our HPC cluster, but ran into a PETSc link error and decided to try Spack.

I followed the instructions on the deal.II wiki, but installation stopped during the "install" phase for "ncurses". The packages "bzip2" and "muparser" installed without a problem.

Here's the error message:
######################################################################## 100.0%

==> Staging archive: /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/var/spack/stage/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/ncurses-6.0.tar.gz

==> Created stage in /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/var/spack/stage/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m

==> Applied patch sed_pgi.patch

==> Ran patch() for ncurses

==> Building ncurses [AutotoolsPackage]

==> Executing phase : 'autoreconf'

==> Executing phase : 'configure'

==> Executing phase : 'build'

==> Executing phase : 'install'

==> Error: ProcessError: Command exited with status 2:

    'make' '-j2' 'install'

/afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/lib/spack/spack/build_systems/autotools.py:282, in install:

     277      def install(self, spec, prefix):

     278          """Makes the install targets specified by

     279          :py:attr:``~.AutotoolsPackage.install_targets``

     280          """

     281          with working_dir(self.build_directory):

  >> 282              inspect.getmodule(self).make(*self.install_targets)

See build log for details:

  /tmp/stvdwtt/spack-stage/spack-stage-7oak9b/ncurses-6.0/spack-build.out

I went to the build log (which is quite long), and see several errors like this:
cd ../lib && (ln -s -f libpanel.so.6.0 libpanel.so.6; ln -s -f libpanel.so.6 libpanel.so; )

/usr/bin/ld: total time in link: 0.021996

/usr/bin/ld: data size 29224512

cd /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/lib && (ln -s -f libpanel.so.6.0 libpanel.so.6; ln -s -f libpanel.so.6 libpanel.so; )

test -z "" && /sbin/ldconfig

/sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied

make[1]: [/afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/lib/libpanel.so.6.0] Error 1 (ignored)

The last few lines of the build log (which I'm not sure are relevant) are:
Running sh /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/var/spack/stage/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/ncurses-6.0/misc/shlib tic to install /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/share/terminfo ...

        You may see messages regarding extended capabilities, e.g., AX.

        These are extended terminal capabilities which are compiled

        using

                tic -x

        If you have ncurses 4.2 applications, you should read the INSTALL

        document, and install the terminfo without the -x option.

** creating form.pc

** creating ncurses++.pc

touch pc-files

/bin/sh -c 'for name in *.pc; do /usr/bin/install -c -m 644 $name /afs/umich.edu/user/s/t/stvdwtt/Public/PRISMS/software/spack/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/ncurses-6.0-4wkexyzgaxdwrfs6wqje2ppcm5di263m/lib/pkgconfig/$name; done'

Judging from the error, I'm assuming that it's a permissions issue. I double-checked that my $SPACK_ROOT environment variable is set correctly. The first line of the build log includes a '--prefix=' statement, which correctly picks up the $SPACK_ROOT path.

Does anyone have ideas on what the problem is? Digging around the Spack documentation didn't turn up anything.

Thanks!
Steve

**Comment by jrood-nrel** [comment]
I am seeing this same error on a new cluster we have at NREL when I compile with Intel 2017.0.2. Everything works fine with GCC.

```
/sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

I wouldn't expect to be able to write to /etc and I have just started looking into this problem because I will need to build with Intel.

I also noticed someone complain about Spack on the Deal.ii group where this post came from and noticed someone saying it wasn't working for them on their cluster and giving up, and I would assume they didn't put the effort in to configure it correctly, which isn't easy, but I think that's why people claim it doesn't work for them. I think that's something that should be emphasized. I have it configured for machines at NREL and people seem to be having positive experiences. As an aside, that I have said before is that I hope something like Spack can help expose how many problems build systems and compilers have and it would be great if these tools in the future would be expected to conform to a general overarching build system like Spack, and not vice-versa. Building manually is not sustainable. I've wasted more time searching for how to solve build problems over my entire career than any other task. This is why if everyone committed to something like Spack, we can use it as a knowledge base for building where the logic of jumping over these hurdles gets encoded into the system for everyone to benefit from. This ends my Friday afternoon rant.

**Comment by s-sajid-ali** [comment]
I'm seeing the same issue on my system as well (as well as another one where I was trying to use spack on someone else's system and gave up) where I can build ncurses and other packages using gcc@7.3.0 but not with intel@2019.0.0.046. Was a fix ever found for this issue ?

**Comment by s-sajid-ali** [comment]
I have no issue installing it with gcc. The issue occurs only with intel compilers because spack fails to set environment variables correctly and it looks like this can be solved by using spack to install the compilers and loading it. ( I'll report back on how that goes in a few weeks as I was doing this with a beta preview and will get access to intel compilers soon. )

**Comment by sethrj** [comment]
I think this is fixed thanks to `ncurses+symlinks`. Reopen if not the case.

**Comment by mabraham** [comment]
I had problems with ncurses failing in the above manner when using spack on a shared filesystem even when using `ncurses+symlinks`
