### ISSUE TITLE
gcc is detected as 4.8 instead of 4.8.5

### ISSUE THREAD

**Issue by davydden** [spack/spack#3879]
on Ubuntu 16.04, `gcc` compiler is detected as `4.8` instead of `4.8.5`.  Name of the binary is `/usr/bin/gcc-4.8` but `gcc-4.8 -v` prints `gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)`.

**Comment by adamjstewart** [comment]
What about `gcc -dumpversion`? I think that's what we use, but you can check in `lib/spack/spack/compilers/gcc.py` to see.

**Comment by davydden** [comment]
you are right, `-dumpversion` shows `4.8`. That's Ubuntu's fault then...

**Comment by tgamblin** [comment]
Welll, if -dumpversion no longer gets us the version we want, we could use -v.  Is the -v output more consistent across platforms?

**Comment by adamjstewart** [comment]
Here is what I'm seeing:

### Fedora 25, GCC 6.3.1
```
$ gcc -v
...
gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)
```
### CentOS 6, GCC 4.4.7
```
$ gcc -v
...
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
```
### CentOS 7, GCC 4.8.5
```
$ gcc -v
...
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
```
### Spack-built, GCC 6.3.0
```
$ gcc -v
...
gcc version 6.1.0 (GCC) 
```
### Spack-built, GCC 5.3.0
```
$ gcc -v
...
gcc version 5.3.0 (GCC) 
```
So it looks fairly standard if we do want to switch to that.

**Comment by davydden** [comment]
@adamjstewart presumably you have a typo above in the Spack's build gcc?

**Comment by davydden** [comment]
reopening as it looks like we are switching to `-v` instead of `-dumpversion `

**Comment by citibeth** [comment]
The behavior you're seeing with `gcc -dumpversion` is considered a bug, and has been fixed in later veresions of GCC on Ubuntu (debian).  See here:

https://bugs.launchpad.net/ubuntu/+source/gcc-4.8/+bug/1360404

With that in mind, I would highly recommend we create a narrow patch that ONLY calls (and parses) `gcc -v` if `gcc -dumpversion` returns a two-part (rather than three-part) version number; which will likely take effect only on Ubuntu/Debian systems when using the system compiler.  In general, `gcc -dumpversion` is STILL the right way to get the GCC version number.

We might also consider checking whether this patch is needed for our GCC builds.  I suspect not.  FWIW, my Spack-built `gcc -dumpversion` replies with `4.9.3`.

**Comment by tgamblin** [comment]
I agree with everything @citibeth said.

**Comment by tgamblin** [comment]
If someone wants to create a PR for the deeper version check in gcc.py that would be great.  If not we'll just say this is a bug.

**Comment by alalazo** [comment]
Considering what @citibeth and @tgamblin said, I am going to close this. Reopen if you don't agree.
