### ISSUE TITLE
Which methods pertain to `Spec` and which to `PackageBase`?

### ISSUE THREAD

**Issue by alalazo** [spack/spack#3968]
I want to start a more general discussion to drive a refactoring based on #3915, #3965, #3967 and related PRs. Basically, I think that all the `do_*` methods that are now in `PackageBase` are logically tied to specs rather than packages. To be more precise they are tied to **concrete specs**. If people agree with this I'll start moving them from `PackageBase` to `Spec`, taking care of checking that the prerequisite on being concrete is respected.

Waiting for feedback before proceeding.

**Comment by tgamblin** [comment]
I think there is a larger discussion here about whether there is more than just spec and Package.  I think methods like do_install and do_uninstall pertain most closely to the particular *store* the spec will be installed in.  Eventually I'd like to have more than one root.
 (E.g. If we register external spack instances  whose installed packages could be used by this one).  

Methods like stage and fetch are different - they allocate some temporary storage and fetch source. Maybe they should get their own manager classes, as their storage is managed differently from the install store.

I hesitate to move much more into the spec class, as it is getting overloaded already.  I think we should separate concerns more in the core. The Spec wrapper build interface should probably be factored out of spec.py (even if it's mostly unchanged), and spec.py should probably just contain parsing, basic spec methods, and concretization.

Lots of stuff in spack is *keyed* by specs, since specs are really the core of the system, but I don't think spec.py will survive under its own weight if we tack everything onto it.

**Comment by tgamblin** [comment]
All that said, I do completely agree that more things need to take specs and not packages-- otherwise we run into expressiveness problems as with the hook interface.  We need to be able to refer to packages that no longer exist, and specs are how you do that.

**Comment by alalazo** [comment]
> I hesitate to move much more into the spec class, as it is getting overloaded already.

Moving the methods out of `PackageBase` would be just a first step. Then I think it will be good to separate what in `Spec` is there to support syntax from what is needed to support concrete installations and other orthogonal behaviors. I was not suggesting this here because I know that a refactoring of concretization is underway, and something like that can be a pain to manage in terms of conflicts.

Anyhow, I think my overall idea is quite similar to what you have in mind when you say :

>  spec.py should probably just contain parsing, basic spec methods, and concretization

Regarding:

> Methods like stage and fetch are different - they allocate some temporary storage and fetch source.

we had our first issue some time ago where the tarball to be fetched depended on the `spec` for the same version of a package. Most likely we had to fetch binaries instead of sources, but I don't recall the details right now. Will try to see if I can find the issue.

> I think methods like do_install and do_uninstall pertain most closely to the particular store the spec will be installed in. Eventually I'd like to have more than one root.

Nice. I didn't take multiple stores into account when thinking about this.

> The Spec wrapper build interface should probably be factored out of spec.py (even if it's mostly unchanged)

I'll do that. Is `spec_build_interface.py` a good enough name for the module?

**Comment by citibeth** [comment]
I must admit I have not looked at this particular factorization issue deeply.   But based on looking at Spack in general, I believe we are too reliant on classmethods, as opposed to free functions.  To our detriment.

In general, I would suggest that classmethods on specs focus on manipulating the spec itself.  Things like `spec.prefix`, for example, that get used inside of `package.py`.  Algorithms that operate ON a spec, or operate WITH RESPECT to a spec, should not be methods.  For example:

1. Concretization: I would make this a separate package.  The concretize() method in in principle a function that takes a spec and a bunch of config info, and returns another spec.

2. Building: These should also be free functions.  We're beginning to think about a "Spack Server," in which the building/installation of a fully concretized spec is potentially done on a different process or machine from concretization.  Building a fully concretized spec doesn't change it at all, and doesn't simply return intrinsic info about that spec.  Three good reasons to not have it be a method on spec.

3. @scheibelp @tgamblin and I are discussing a new data structure called a Spec List.  Further understanding of a Spec List could change ideas about how best to factor these things.  However, I believe that keeping methods simple and using free functions more is almost always future-proof.

---------------

My criteria for what is to be a classmethod would be:

1. If its signature is `mymethod(const self)`, then it's a good candidate for a classmethod.

2. If its signature is `mymethod(self, ...)` --- and it modifies `self` based on the other parameters provided, then it's a good candidate for a classmethod.

3. If it reads/writes lots of files based on `self` or `const self`, then consider using a free function.  In this case, the files written could be considered the base "class," except that they are not represented as such.  As an exception, functions that store/retrieve the object to disk based on a standard representation (eg. a JSON writer/reader) can be as methods; unless you have many different on-disk representations you want to support.

4. If it modifies more than one object of different classes, then it should be a free function; since it doesn't fit neatly as a classmethod for either class.
