### ISSUE TITLE
Should packages have build dependencies on Python?

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4063]
Continuing the discussion from #3975.

Many packages in Spack require Python as a build dependency. For these packages, we've explicitly add:
```python
depends_on('python', type='build')
```
to denote this fact, and Spack will install Python before installing the package. For most build dependencies this makes sense, as we can't guarantee whether or not the OS has this package installed, or whether or not it is a new enough version. We can, however, guarantee that Python is installed and is relatively new. Otherwise, the user wouldn't be able to run Spack! So should we really tell Spack to reinstall Python?

### Pros of the build dependency

There are some pros to explicitly declaring a Python dependency. First of all, it offers more freedom. If you want Spack to build a new version of Python and use it, it will. If you want Spack to use your system Python instead, just add it as an external package to your `packages.yaml`. If you are a developer and want to make sure your project can be built with several versions of Python, it makes it easy to test with Spack.

For packages that only build with Python 2, we don't really have a choice. Now that Spack works with Python 3, we can't ensure that the first python in `PATH` is Python 2. But for packages that build with both Python 2 and 3, we could theoretically use whatever Python the user is running Spack with.

### Cons of the build dependency

More installations. Need I say more? 😉 

The biggest benefit of removing Python build dependencies that I can see is the ability to get around some nasty concretization problems in Spack. For example, it currently isn't possible to install `python+tk` because of the following dependency chain:
```
python+tk -> tk -> libx11 -> libxcb -> python
```
Right now, the concretizer won't allow you to install 2 variants of the same package in a single spec, so `python+tk` essentially depends on `python+tk`, creating a dependency loop. Once #2548 is merged, this won't be a problem anymore. But until then, it's a show stopper for many users (@svenevs).

@citibeth @tgamblin

**Comment by davydden** [comment]
> The biggest benefit of removing Python build dependencies that I can see is the ability to get around some nasty concretization problems in Spack.
> ...
> Once #2548 is merged, this won't be a problem anymore. But until then, it's a show stopper for many users (@svenevs).

maybe a few crucial packages should drop `python` build dependency, and have a `# TODO: turn on after #2548 is merged`.  In general, I would not drop python build dependency.

**Comment by citibeth** [comment]
Dependencies should be declared explicitly, including Python.  Then Spack should figure out how to satisfy those dependencies.

One idea would be that the first time it's run, Spack roots around the Python installation and creates a `packages.yaml` file based on it.  It would put `python` in that file, as well as maybe some other common Python packages (`py-setuptools`, etc).

My only concern here is that users might want to use these auto-found Python packages for build-only dependencies, not run dependencies: I would want a "clean" Spack-built Python for any "serious" development (i.e. run dependencies).  We currently have no way to specify in `packages.yaml` to "use this for build dependencies but not run deps."

If that feature could be added, I think we would have all the tools we need to have Spack use the system Python for build dependencies (when appropriate).

Even without that feature, we could hack it.  A simple way would be to inspect packages for `depends_on('python', type='build')` when loading them into memory.  If that's the case, and if the system Python satisfies the dependency version request, then remove it from the package and add Spack python to the build environment.

**Comment by citibeth** [comment]
> Right now, the concretizer won't allow you to install 2 variants of the same package in a single spec...

How close is #2548 to getting merged?  Whatever the merits are of being able to use the System Python, wouldn't it be easier to just finish and merge #2548?

**Comment by davydden** [comment]
> One idea would be that the first time it's run, Spack roots around the Python installation and creates a packages.yaml file based on it.

or we can push OS specific configuration scopes, with python https://github.com/LLNL/spack/issues/2700

>  We currently have no way to specify in packages.yaml to "use this for build dependencies but not run deps."

that would be good to have, indeed 👍

**Comment by adamjstewart** [comment]
> or we can push OS specific configuration scopes, with python #2700

I'm not sure how well this will work. There are some packages that _should_ be installed on every RHEL release, but even within the same RHEL release, the exact versions of packages that are installed can vary.

**Comment by adamjstewart** [comment]
> maybe a few crucial packages should drop `python` build dependency, and have a `# TODO: turn on after #2548 is merged`.

I would be fine with that solution. I've been doing it manually whenever I've needed those things.

> How close is #2548 to getting merged?

No idea. I know @svenevs has been using it without too many problems. But it is a major change, so it may take a while to get merged.

**Comment by svenevs** [comment]
> No idea. I know @svenevs has been using it without too many problems.

I've pretty much been exclusively building off 2548, it works very well!  They've still got their work cut out for them with `py-setuptools` though.  The intermediate patch being force it as a `link` dependency _for every python package that uses it_.  So it's probably still a little ways off if I understand the situation.

### show-stopper

Only in that if you need `python+tk` you have to dig through the trenches to figure out how to actually get it to work.  A while ago I had tried to get a conversation about the "right" way to hack it and put it in the official documentation, fully disclaiming that it is not forever and is actively being fixed etc, but that didn't go anywhere.  While I agree with the sentiment of "instead of documenting what is broken, fix it", it's really crippling for anybody who actually wants `python+tk`.  Perhaps just add the following to the docs?

```rst
.. tip::

   The ``spack`` developers are hard at work resolving complex issues related to concretization,
   ``python``, and ``tk``.  Without too much background information, the high-level problem is there
   is a circular dependency that cannot be resolved with the current `develop` branch of `spack`.

   If you need ``python+tk``, for example to install ``py-matplotlib``, here is what the process would
   look like for a fresh ``clone`` of ``spack`` (noting that if you already have it, make sure you
   ``git pull`` before merging).  Please note that you may encounter merge conflicts, refer to the
   discussion in `Pull Request 2548 <https://github.com/LLNL/spack/pull/2548>`__ for what may
   be going on / what you should choose in the merge.

   If you are unfamiliar with merging / resolving conflicts with ``git``, this may be quite a challenge.
   We strongly encourage you configure a `git mergetool` (search online, `vimdiff` is a good option
   if you know ``vim``, or choose a GUI client from
   `the excellent list here <https://git-scm.com/downloads/guis>`__).  If you are unable to resolve
   conflicts or make mistakes, you can always start over with a new branch.

   .. code-block:: console

      # Navigate to the directory you want to keep spack in.  We choose /opt
      # in this example, it is your decision.
      $ cd /opt
      $ git clone https://github.com/LLNL/spack.git

      # Enter the spack directory, and download PR 2548 (work in progress)
      # The default branch of `spack` is `develop`, remain on this branch.
      # This will create a local copy of the current 2548 PR, called local-2548-PR
      $ cd spack
      $ git fetch origin pull/2548/head:local-2548-PR

      # We strongly advise you do not work on this branch directly.  Instead, create
      # a new branch (e.g. test-2548) and merge the local PR in.  This will make it
      # so that you can restart if needbe, as well as get new updates from 2548
      # without causing local merge conflicts.
      $ git checkout -b test-2548
      # Verify you are on this branch, and have the local branch of the PR
      # The * indicates which branch you are on
      $ git branch
        develop
        local-2548-PR
      * test-2548

      # We checked out test-2548 from `develop`, now merge in the 2548 PR
      $ git merge local-2548-PR

      # < you may need to resolve merge conflicts now >

      # Test if you can install python+tk.  If the `spec` command completes, you should
      # have no trouble completing the installation!
      $ spack spec python+tk
```

I think that is all valid `rst` but didn't actually test it.  Also worth noting that it would be nice, if this is actually put in the docs, to get 2548 rebased if that is possible.  There are a lot of merge conflicts right now, making the above pretty challenging for people not familiar with `git`.  It's up to you, I just really feel like at this point it's worth just telling people straight up it's a problem, you know about it, here is one thing you can try, but ultimately it's a **very** hard problem to fix so thanks for the patience :wink:

That said, I don't think this is a major concern for `spack`.  I'm an end user managing my own system with a desktop login.  I want `py-matplotlib` and friends.  I need `+tk`.  On the other hand, the majority of applications of `spack` in my understanding are for deployment on clusters etc, for which `+tk` doesn't make sense and is usually not possible / X sessions are explicitly forbidden.

<hr>

On topic, what if you promote `python` to be more like `compiler`.  Say it is called `pybuilder.yaml` and introduce `spack pybuilder find` or whatever.

- What are you going to do about `py-X` packages?  Personally, I would be _furious_ if `spack` started putting things in my system python path, _even if_ it was a symlink.
- How are you going to find the system python?  This is not the same as the first one found in the `$PATH`.  My understanding is Windows support is dwindling at best (it should be, they don't deserve spack hehehe).  But that adds additional complexity.
    - Maybe this isn't actually an issue?  Even if they are using `anaconda` python, if you make the assumption that `pybuilder.yaml` is up to date, then they can do whatever they want.
    - **HUGE BENEFIT**: all of the other folks e.g. linux distros and anaconda have already solved the `py-setuptools` dilemma.  Basically, I think you can **assume** `py-setuptools` exists already.

On the other hand, would it maybe be better to wait until [PEP 518](https://www.python.org/dev/peps/pep-0518/) is official?  That's going to introduce some fantastic capabilities that `spack` could really lean on.

I :heart: my `spack` managed python.  Where else can I get the `matmul` operator so easily?!!!  I don't think you are saying `python` will disappear altogether though, just make it so it doesn't have to be installed so many times (which I'm a proponent of).  I have 8 python installations now :scream:

**Comment by scheibelp** [comment]
> Also worth noting that it would be nice, if this is actually put in the docs, to get 2548 rebased if that is possible. There are a lot of merge conflicts right now

I've updated #2548 so it should at least merge cleanly with develop.

**Comment by adamjstewart** [comment]
Closing this as the discussion is long over.
