### ISSUE TITLE
ParaView with osmesa support

### ISSUE THREAD

**Issue by MathiasMen** [spack/spack#4077]
Hi guys,

I just tried installing ParaView with osmesa-support with a simple `spack install paraview+osmesa` on a cluster where I have no sudo-access. git and a gcc-compiler are in PATH and all of the dependencies build smoothly. During the CMake-phase of the ParaView-module however, I get an error which essentially comes down to the fact that the osmesa-library is missing. I attached the (renamed) spack-build.out of the ParaView-stage. Is it intended behaviour that I would have to build that library myself and then (somehow) link against it or provide a path? I would love to avoid having to build it myself. Thanks in advance!

Regards,

Mathias

Attachment - ParaView stage output:
[spack-build.out.txt](https://github.com/LLNL/spack/files/969788/spack-build.out.txt)

**Comment by davydden** [comment]
it looks like it's missing in `paraview`. Probably because it comes with whole lot of x11 dependencies. Although they are in Spack now. I would do the following:
(i) contact sysadmins to install osmesa on the cluster. 
(ii) while waiting for (i), try to create a package for `osmesa` with `spack create ftp://ftp.freedesktop.org/pub/mesa/mesa-17.0.5.tar.gz`, see https://www.mesa3d.org/osmesa.html and https://github.com/macports/macports-ports/blob/master/x11/mesa/Portfile . Macports will give you rough ideas on build and link dependencies.

**Comment by davydden** [comment]
also checkout this branch https://github.com/LLNL/spack/issues/3201#issuecomment-284211371

**Comment by MathiasMen** [comment]
What about changing the dependency of `paraview` to `mesa`? I guess it's possible to then do something like `depends_on('mesa cxxflags=some_flags_needed', when='+mesa')` and add the CMake-flags specified [here](http://www.paraview.org/Wiki/ParaView/ParaView_And_Mesa_3D#Configuring_ParaView_for_use_with_OSMesa) to `cmake_args`?

**Comment by davydden** [comment]
CMake flags are added in `package.py` file of `paraview` and are not related to `depends_on`. Otherwise I have not idea what's the difference between `mesa` and `osmesa`. One thing for sure -- those are not the same.

**Comment by ax3l** [comment]
it's on `+mesa` by now.

probably chaning to `llvmpipe` instead of gallium as the default backend would also increase performance and features (OpenGL2 support does not seem to work for volume rendering due to missing features in 3D proxy textures).

**Comment by chuckatkins** [comment]
This is no longer applicable given the current state of mesa and paraview.
