### ISSUE TITLE
Lmod and changing hashes

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4233]
This is a continuation of the discussion in #1325, specifically geared toward how to handle this problem in relation to Lmod.

In #1325 we came to the conclusion that Spack is not backwards compatible. Every time the hashing algorithm changes or support for things like multi-valued variants is added, Spack has to be reinstalled. Since users could have RPATHed their executables to these old installations, you have to install the newer version of Spack in a new directory and keep the old one.

My question is, how do others handle this problem in relation to Lmod? For example, what if a user wants to use one module installed with Spack 0.9.1 and another installed with Spack 0.10.0? Lmod is special in the sense that it won't let you load multiple compilers at the same time. If both Spack installations have separate Core/Compiler/MPI hierarchies, how do you get `module load intel/17.0.3` to add both directories to the `MODULEPATH`?

One more question. How do people handle module files for things installed outside of Spack? Do you throw the module file in the Spack Lmod hierarchy and hope that no one accidentally refreshes it? Do you add a separate Lmod hierarchy outside of Spack? If the latter, how do you handle this same hierarchy problem? Do you create copies of the Spack module files that add the right directories to `MODULEPATH`?

**Comment by adamjstewart** [comment]
Other solutions that I've thought of.

You can [configure Spack to install module files to a different location](https://github.com/LLNL/spack/blob/develop/etc/spack/defaults/config.yaml#L22,L26). But if you `spack module refresh --delete-tree`, it will delete the module files installed with other Spack installations.

Worse yet, I want to have a Spack installation in my home directory so I can build and rebuild stuff without breaking anything, but I don't want these to install global module files. Right now I have 4 site installations of Spack and 1 in my home directory. All of my configuration files go in `~/.spack`. If I want the same settings to apply to my 4 site installations but not my 1 user installation, I would have to put the same configuration files in 4 site locations and keep them up-to-date.

**Comment by alalazo** [comment]
> How do people handle module files for things installed outside of Spack?

The easy one: I personally make every application of this kind an external package. With #1167 external packages get registered in the DB which means, among other things, that you can create module files for them via Spack.

**Comment by adamjstewart** [comment]
In that case I might need to make a package for Spack itself...

**Comment by alalazo** [comment]
Like @hartzell would suggest "Spack all the way down." :laughing:

**Comment by hartzell** [comment]
My plan is to make periodic "formal" deployments of my application tree.  Those deployments are immutable.  Changes pile up until enough pressure builds to make a new release.  Old deployments are  deleted after a suitable deprecation period.   Teams that need faster paces, or just one more thing really this time I mean it will just get there own deployment starting from whichever of the previous releases they want (or HEAD, or ...)  If one were to rpath into something in the public tree then one is safe until that tree is deleted.  The deprecation period is designed to provide breathing room.  Important apps/projects, which much run forever, should have their own tree.

I have buy in for this scheme, but we'll see how it survives its encounter with reality.

I haven't had much luck with composing an environment from multiple trees.  I use the Lmod package installed within in the tree to load the modulefiles within that tree (plus a dir for snowflakes, see below).

So far I haven't had a reason to have two spack trees in play.  If you have one tree with a bunch of stuff built and another with other stuff built, my solution is to build a tree with the union.  Only downside it build time.  I can imagine that there are problems with compilers/libraries etc..., but so far I haven't suffered for it.

The one exception is when I'm working on e.g. a new package.  My world is indeed spackified (I used to get most of my tools from a personal linuxbrew tree, but I'm dogfooding now).  I've developed this habit:

```
(module purge; spack install <package>)
```

To empty my environment so that the spack build process doesn't have trouble with the compilers in the tree I'm developing and in the dogfood tree.

I have a directory tree of hand-crafted module files that is added to people's world via a `module use` in the default config files.  People are free to do something different.

**Comment by alalazo** [comment]
@hartzell We are doing exactly the same thing since one year, and overall I'd say it's working fine.

We install software with one Spack instance (that we freeze, not to have problems with changing DB format / package recipes), and let users interact with what is installed via modules. 

The only use case that seems really sub-optimal is for the few "power users" that need many different custom deployments of relatively complex libraries or applications. What I am doing right now is making them aware we are installing things with Spack, and helping them rebuilding the stack they need in their `/home`. But that leads to a lot of duplication.

What I think I'll try to work on as soon as I have some more time (we are in the process of redeploying new software right now) is to extend Spack in some way to permit to have more than one "store". What I am thinking is to merge different DBs in the same way we do for config files. Assuming the installations we do as cluster mainatiners will be immutable, people could put a reference somewhere do a read-only DB and will pick from there things that are already installed.

**Comment by hartzell** [comment]
> [...] rebuilding the stack they need in their /home. But that leads to a lot of duplication.

I expect to do something like that.  Given the size of our datasets, even if everyone had their own tree it wouldn't break the bank.  Many of them are doing it already with [multiple] *conda* environments.  And don't get me started on Docker images...

**Comment by alalazo** [comment]
Can we consider this answered?

**Comment by adamjstewart** [comment]
I think so. For anyone else running into this question, my best answer for now would be to configure Spack to write module files to a common directory. In the long term, hopefully Spack will become more backwards compatible and this won't be necessary.
