### ISSUE TITLE
Unable to load module in compilers.yaml

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#4249]
I want to load modules for compilers when I build software with Spack. For example, when I build something with the Intel compiler, I want things like `xar` to be in my `PATH`. If I add the following to my `compilers.yaml`:
```yaml
compilers:
- compiler:
    modules:
    - intel/17.0.3-gbgtimn
...
```
and try to build something, I see the following error message:
```
==> Error: AttributeError: 'NoneType' object has no attribute 'add_default_arg'
```
The problem is that in the [`load_module` method of `build_environment.py`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L130), we search for the `modulecmd` executable and use that to load modules. But `modulecmd` isn't in my `PATH`. Is there any way we can use the normal `module` command?

**Comment by skosukhin** [comment]
Hi! I think you can start reading from here #3250.

We need not the "module" command that generates bash (usually) scripts to modify the environment but the "modulecmd" executable that can generate a python script for us that does the same thing. And there is a problem to get the path to the "modulecmd" from the definition of the shell function "module" because there are too many ways to define the function wrongly. I've seen cases when it's a custom wrapper of a custom wrapper of a wrapper of the modulecmd executable.

**Comment by adamjstewart** [comment]
Thanks, I knew I saw someone working on this, although the discussion was always about Cray. I guess I'll have to have `modulecmd` in my `PATH` for now.

**Comment by adamjstewart** [comment]
Hmm, I took another look at this. It turns out that my Lmod installation doesn't have any `modulecmd` script anywhere. Anyone know how this was supposed to work? Does it only support Environment Modules?

**Comment by adamjstewart** [comment]
Haven't had any problems with compiler modules in recent years, closing.
