### ISSUE TITLE
Changing flags causes dependencies to be re-installed

### ISSUE THREAD

**Issue by EmreAtes** [spack/spack#4610]
When I install a package e.g. `spack install gromacs@5.1.4%cce@8.5.6`, and then I try to install the same package with a modified flag, e.g. `spack install gromacs@5.1.4%cce@8.5.6 cppflags=-O1`, spack tries to compile and install all of the dependencies for gromacs again.

Is this the desired behavior? I feel like the dependencies can be kept as they are, and only the gromacs installation can be modified to use the extra flag.

**Comment by tgamblin** [comment]
@EmreAtes: this is normal, as we try to enforce consistent flags across a DAG.  If you want to force gromacs to depend on installed things, you can use `spack install gromacs ^/hash-of-existing-dependency [...]` but that can be somewhat tedious.

@becker33: is there an easy way to avoid propagating flags to dependencies?  Also, are flags currently propagated to build dependencies?

**Comment by becker33** [comment]
@tgamblin Currently compiler flags do propagate to build dependencies, I doubt that's what we want.

There is not currently an easy way to avoid propagating flags to a dependency, the easiest I can think of is to build the dependency without the flag and then request that build by hash as a dependency.

**Comment by jbigot** [comment]
I am struggling with the same issue and trying to script my way around it. I manage to get a list of installed packages with their hash using `spack find`, I can get a resolution reusing installed packages with `spack solve` with no `flag` specified, however I didn't find a way for simply putting all of that together to reuse the installed packages by hash when adding my flags. 

Are there any news on the direct support of non-propagatable flags in spack?

Otherwise, did anyone manage to work-around the issue in an automated way? A nice first step would be to be able to provide the hash of already installed packages in `spack solve`

**Comment by jbigot** [comment]
As a matter of facts, it seems the issue can not be easily worked around using hashes of already installed first-level deps only. It seems that in that case, spack tries to reinstall deps below by adding the new flags if that does not change the hash of the first-level dep (build deps)

**Comment by becker33** [comment]
This is resolved since #29761
