### ISSUE TITLE
Issue with lmod when enabling direct autoload?

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#4666]
Hello,

I am playing with `lmod` first time and enabling autoload of `direct` dependencies:

```
# in ~/.spack/darwin/modules.yaml

  lmod:
    core_compilers: ['gcc', 'clang']
    hash_length: 0
    all:
      suffixes:
          +profile: 'profile'
      autoload: 'direct'
```

I have following modules : 

```
mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2
mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master
mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master-profile
mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2
```

Now if I try to load neuron module which has `tau` dependency I see:

```
module load mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master-profile
Autoloading tau/2.25.2
Lmod has detected the following error:  The following module(s) are unknown: "tau/2.25.2"


Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "tau/2.25.2"
```

The error seems obvious as we have to specify full name `mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2`. Is this a bug or any configuration that I am missing?

**Comment by adamjstewart** [comment]
You should read [this section of the Lmod documentation](http://lmod.readthedocs.io/en/latest/080_hierarchy.html). Lmod uses what is called a "Core/Compiler/MPI" hierarchy. Let's walk through an example with the following module files:
```
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/Core/clang/8.1.0-apple.lua
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/clang/8.1.0-apple/mpich/3.2-vanqx22.lua
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2.lua
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master.lua
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master-profile.lua
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2.lua
```
When you set up Lmod, your `MODULEPATH` should be set to:
```
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/Core
```
not:
```
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64
```
This way, when you first log in, all you see available are compilers (and other things built with the core compiler). You have to choose a compiler:
```
$ module load clang
```
this module file contains a line that prepends `MODULEPATH` to add:
```
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/clang/8.1.0-apple
```
Now, `module avail` will show things built with this compiler as well as things built with the core compiler. If you run:
```
$ module load mpich
```
then:
```
$SPACK_ROOT/share/spack/lmod/darwin-sierra-x86_64/mpich/3.2-vanqx22/clang/8.1.0-apple
```
will be prepended to `MODULEPATH`. At this point, `module avail` should show:
```
tau/2.25.2
neuron/master
neuron/master-profile
tau/2.25.2
```
at the top, and things will work correctly.

The problem that you seem to have is:

1. You don't have the correct initial `MODULEPATH` (with `Core` at the end)
2. You may not have module files for `clang` or `mpich`

Fixing 1 is easy, but fixing 2 may require a little work. You can either write your own module files if you know what you are doing, or you can add the compiler and MPI as [external packages](http://spack.readthedocs.io/en/latest/build_settings.html#external-packages) and let Spack create module files for you. I recommend the latter.

EDIT: Now that I think about it, you are probably on macOS and `clang/8.1.0-apple` _is_ your core compiler. You need to set `%clang@8.1.0-apple` to be your core compiler [like so](http://spack.readthedocs.io/en/latest/tutorial_modules.html#core-compiler-mpi). Then ask Spack to regenerate all of your module files. I think you'll still need an MPI module file though. I've never built anything aside from compilers with my core compiler, so I couldn't say.

**Comment by pramodk** [comment]
thank you very much @adamjstewart  for explanation!

I gone through modules tutorial and understood some more details. I see how the `Core` compiler is set and then as we load modules, new paths get added and hence available modules.

>  you can add the compiler and MPI as external packages

I can see how to add MPIs but, if I am not wrong, compilers don't get registered into DB. (I tried adding entry into `packages.yaml`)

Here is scenario : I have `gcc` and `clang` compilers on my mac. Both are externally installed via brew and hence there is no single core compiler. I install bunch of packages with these two compilers.

Now suppose `spack find` shows following : 

```
$ spack find

==> 6 installed packages.
-- darwin-sierra-x86_64 / clang@8.1.0-apple ---------------------
mod2c@develop mpich@3.2 neuronperfmodels@neuron

-- darwin-sierra-x86_64 / gcc@4.9.4 -----------------------------
mod2c@develop mpich@3.2 neuronperfmodels@neuron
```

With `lmod`, what I want to achieve is following : 

- initially module av should show two available compilers (clang & gcc)
- after loading one of those will show packages built with that specific compiler and mpich package
- loading mpich will show the packages built with selected compiler & mpich (and so on..)

I wondering if there is easy way to do this with configurations.

If I specify both as core compilers : 

```
    core_compilers:
      - 'gcc@4.9.4'
      - 'clang@8.1.0-apple'
   hash_length: 0
```

I see conflict : 

```
file: /Users/k...../share/spack/lmod/darwin-sierra-x86_64/Core/mod2c/develop.lua
spec: mod2c@develop%clang@8.1.0-apple arch=darwin-sierra-x86_64
spec: mod2c@develop%gcc@4.9.4 arch=darwin-sierra-x86_64
```
 Ok, because I specified both as core compilers and these modules will end up in same path. And this will be the case for many other packages.

**Comment by adamjstewart** [comment]
Okay, so if the behavior you want is:

> initially `module av` should show two available compilers (clang & gcc)

then you have to remove them as core compilers. Compilers _should_ get registered in the database. What happens when you add them to `packages.yaml`, mark them `buildable: False`, and run `spack install gcc` and `spack install clang`?

**Comment by pramodk** [comment]
Ok, I was installing other packages but not compiler itself. I see DB registration once I try to install them.
With below commands do we expect to have two registrations? (i.e. gcc %clang && gcc %gcc ?)

```
○ → spack install gcc@4.9.4 %clang
==> gcc@4.9.4 : externally installed in /usr/local
==> gcc@4.9.4 : generating module file
==> gcc@4.9.4 : registering into DB

○ → spack install gcc@4.9.4 %gcc
==> gcc@4.9.4 : externally installed in /usr/local
==> gcc@4.9.4 : already registered in DB

○ → spack find gcc
==> 1 installed packages.
-- darwin-sierra-x86_64 / clang@8.1.0-apple ---------------------
gcc@4.9.4
```

By the way, `clang` is not a package. So we can't install it. I created new package and then installed.

Now once I refresh modules, `module av`  takes `very long` time. I did `^C` :

```

○ → spack module refresh --delete-tree -y -m lmod

○ → echo $MODULEPATH
/Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64


○ → module av
^C/usr/local/opt/lua/bin/lua: /usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: interrupted!
stack traceback:
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:382: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	...
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:390: in function 'l_build_parentT_helper'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:402: in function 'l_build_parentT'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Spider.lua:481: in function 'buildDbT'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Cache.lua:566: in function 'build'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/ModuleA.lua:669: in function 'singleton'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/Master.lua:788: in function 'avail'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/cmdfuncs.lua:130: in function 'cmd'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/lmod:479: in function 'main'
	/usr/local/Cellar/lmod/7.5.2_1/lmod/libexec/lmod:526: in main chunk
	[C]: in 
```
After waiting for long time it doesn't return anything:

```
→ time module av

real	3m45.616s
user	1m58.368s
sys	1m18.882s
```

But module tree is generated :

```
○ → tree /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64
/Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64
|-- clang
|   `-- 8.1.0-apple
|       |-- clang
|       |   `-- 8.1.0-apple.lua
|       |-- gcc
|       |   `-- 4.9.4.lua
|       |-- mod2c
|       |   `-- develop.lua
|       |-- mpich
|       |   `-- 3.2.lua
|       |-- neurodamus
|       |   `-- develop.lua
|       |-- neuronperfmodels
|       |   `-- coreneuron.lua
|       `-- python
|           `-- 2.7.10.lua
|-- gcc
|   `-- 4.9.4
|       |-- mod2c
|       |   `-- develop.lua
|       |-- mpich
|       |   `-- 3.2.lua
|       |-- neurodamus
|       |   `-- develop.lua
|       |-- neuronperfmodels
|       |   `-- coreneuron.lua
|       `-- python
|           `-- 2.7.10.lua
`-- mpich
    |-- 3.2-vanqx22
    |   `-- clang
    |       `-- 8.1.0-apple
    |           |-- coreneuron
    |           |   |-- perfmodels-profile.lua
    |           |   `-- perfmodels.lua
    |           |-- neuron
    |           |   |-- master-profile.lua
    |           |   `-- master.lua
    |           |-- neuronperfmodels
    |           |   |-- neuron-profile.lua
    |           |   `-- neuron.lua
    |           `-- tau
    |               `-- 2.25.2.lua
    `-- 3.2-xboj7as
        `-- gcc
            `-- 4.9.4
                |-- coreneuron
                |   |-- perfmodels-profile.lua
                |   `-- perfmodels.lua
                |-- neuron
                |   |-- master-profile.lua
                |   `-- master.lua
                |-- neuronperfmodels
                |   |-- neuron-profile.lua
                |   `-- neuron.lua
                `-- tau
                    `-- 2.25.2.lua

31 directories, 26 files
```

Have no idea whats going on... backtracking :)

Uninstalled `gcc` and `clang` and regenerated modules. Now I see:

```
module av

-------------- /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64 ---------------
   clang/8.1.0-apple/mod2c/develop                                     (L)
   clang/8.1.0-apple/mpich/3.2
   clang/8.1.0-apple/neurodamus/develop
   clang/8.1.0-apple/neuronperfmodels/coreneuron
   clang/8.1.0-apple/python/2.7.10
   gcc/4.9.4/mod2c/develop                                             (L)
   gcc/4.9.4/mpich/3.2
   gcc/4.9.4/neurodamus/develop
   gcc/4.9.4/neuronperfmodels/coreneuron
   gcc/4.9.4/python/2.7.10
   mpich/3.2-vanqx22/clang/8.1.0-apple/coreneuron/perfmodels-profile
   mpich/3.2-vanqx22/clang/8.1.0-apple/coreneuron/perfmodels           (D)
   mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master-profile
   mpich/3.2-vanqx22/clang/8.1.0-apple/neuron/master                   (D)
   mpich/3.2-vanqx22/clang/8.1.0-apple/neuronperfmodels/neuron-profile
   mpich/3.2-vanqx22/clang/8.1.0-apple/neuronperfmodels/neuron         (D)
   mpich/3.2-vanqx22/clang/8.1.0-apple/tau/2.25.2
   mpich/3.2-xboj7as/gcc/4.9.4/coreneuron/perfmodels-profile
   mpich/3.2-xboj7as/gcc/4.9.4/coreneuron/perfmodels                   (D)
   mpich/3.2-xboj7as/gcc/4.9.4/neuron/master-profile
   mpich/3.2-xboj7as/gcc/4.9.4/neuron/master                           (D)
   mpich/3.2-xboj7as/gcc/4.9.4/neuronperfmodels/neuron-profile
   mpich/3.2-xboj7as/gcc/4.9.4/neuronperfmodels/neuron                 (D)
   mpich/3.2-xboj7as/gcc/4.9.4/tau/2.25.2

  Where:
   L:  Module is loaded
   D:  Default Module
```

As I have commented out `core_compilers` in `modules.yaml`, `Core` directory is missing. But
- `module av` is showing all directory structure
- even though `hash_length: 0`, mpich version has 7 chars hash

**Comment by adamjstewart** [comment]
Hmm, I think you're going to need some sort of core compiler (the one that comes from the operating system, not the ones you installed with Homebrew/Spack). Then, use that compiler to install newer versions of GCC/Clang if you want. Until you have a `core_compiler` that was used to install GCC/Clang, things aren't going to work the way you expect. I assume you have XCode installed and that comes with Clang? I would use that to build a newer version of GCC with Spack.

@alalazo You know a lot more about Lmod than I do. How should the hierarchy look if you actually use the core compiler as one of your more common compilers? I've only ever seen the hierarchy setup so that you install newer compilers with your core compiler, but @pramodk probably wants to use Clang (core compiler) and switch back and forth to GCC.

> With below commands do we expect to have two registrations?

Yes, I would expect to see two. @alalazo is this a bug in our external packages database support? Maybe it is ignoring the compiler.

> By the way, clang is not a package. So we can't install it.

I ran into a similar problem with `intel-parallel-studio`. Technically it is a compiler and MPI implementation. I ended up hacking the module file so that it prepended the same `MODULEPATH` as both `intel` and `intel-mpi`. In your case, it might make sense to add it to `packages.yaml` as `llvm+clang`. You can always rename the module file if you want. I think `llvm` contains special logic so that it knows it's a compiler even though it's not called `clang`. You may have to change the `MODULEPATH` it uses.

> Now once I refresh modules, `module av` takes very long time.

Maybe it's rebuilding the cache?

> even though `hash_length: 0`, mpich version has 7 chars hash

@alalazo might be able to explain that. I'm not sure why that's the case. I don't have the luxury of setting `hash_length: 0` so I've never experimented with it. But I'm glad that some hash is added to the MPI provider by default. We have 3 different IB fabrics at work, so we need 3 versions of each MPI provider.

**Comment by hartzell** [comment]
> Hmm, I think you're going to need some sort of core compiler (the one that comes from the operating system, not the ones you installed with Homebrew/Spack). Then, use that compiler to install newer versions of GCC/Clang if you want. Until you have a core_compiler that was used to install GCC/Clang, things aren't going to work the way you expect.

Here's my modules.yaml:

```yaml
modules:
  enable::
    - lmod
  lmod:
    core_compilers:
      - 'gcc@4.8.3'
      - 'gcc@4.8.5'
    hash_length: 0
    whitelist:
      - gcc
    blacklist:
      - '%gcc@4.8.3'
      - '%gcc@4.8.5'
    verbose_autoload: false
    all:
      suffixes:
        '+X': x-windows
        # must make sense vis a vis the pythons being installed below
        '^python@2.7.9': py2.7.9
        '^python@3.5.1': py3.5.1
        '^python@3.6.0': py3.6.0
      filter:
        environment_blacklist: ['CPATH', 'LIBRARY_PATH', 'LD_LIBRARY_PATH']
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
    ^python:
      autoload:  'direct'
      filter:
        environment_whitelist: ['LD_LIBRARY_PATH']
```

I use the system compiler (gcc 4.8.x on various releases of CentOS 7) to `spack install` and `spack compiler add` gcc@5.4.0 as the first steps in deploying my environments.  I use that compiler to build all of my toys.

I end up with a `.../share/spack/lmod/linux-centos7-x86_64/Core` directory that I `module use`; it contains a `gcc/5.4.0` modulefile.  I `module load gcc/5.4.0` which adds `.../share/spack/lmod/linux-centos7-x86_64/gcc/5.4.0` to the module search path and makes available all of the things that I've built.

"Works a charm." 

At one point I was using the system's gcc to build a gcc@5.4.0 (technically that's `gcc@5.4.0%gcc@4.8.x` and then used that to build a `gcc@5.4.0%gcc@5.4.0`.  That, and/or the resulting modulefiles, confused the daylights out of Lmod.  Don't do that.

**Comment by alalazo** [comment]
@pramodk

> I can see how to add MPIs but, if I am not wrong, compilers don't get registered into DB. (I tried adding entry into packages.yaml)

This statement is not completely true. If you build a compiler via Spack, it is added to the DB as every other package. This also happens if the package is external. What doesn't happen automatically is to register *this* compiler as one of the compilers usable in specs.

> By the way, clang is not a package. So we can't install it. I created new package and then installed.

The package that provides `clang` is `llvm`.


@adamjstewart

> How should the hierarchy look if you actually use the core compiler as one of your more common compilers?

This is a nasty corner case. The [LMod documentation](http://lmod.readthedocs.io/en/latest/080_hierarchy.html) says:

> The Core directory is for modules that are **not dependent on Compiler** or MPI implementations.

We can't fit exactly into this model, because in Spack everything is dependent on a compiler (you can't have a concretized spec without the `%` sigil). One can always have a mock compiler to be used as Core though. @pramodk I don't get why you can't set `gcc@4.9.4` as your core compiler, and build more recent `gcc` or `llvm` with that. Doing so will fit into the hierarchy model and won't require any hack (plus you'll be using a more recent compiler, which sometimes help :smile: ).

> Yes, I would expect to see two. @alalazo is this a bug in our external packages database support? Maybe it is ignoring the compiler.

It seems a bug, maybe in the handling of external packages? 

> @alalazo might be able to explain that. I'm not sure why that's the case. I don't have the luxury of setting hash_length: 0 so I've never experimented with it. But I'm glad that some hash is added to the MPI provider by default. We have 3 different IB fabrics at work, so we need 3 versions of each MPI provider.

You can set the hash length to zero, and that will generate a lua module file with no hash. In the directory hierarchies the hash is retained because you need to differentiate among variations of the same provider package. 

A use case to be less abstract is the following: imagine you want `lapack` in the hierarchy and you use `openblas@X.Y` as your provider. You want to build libraries for your users against `openblas@X.Y+openmp` and `openblas@X.Y~openmp` so that they can choose whether or not to use multi-threaded lapack. If you remove the hash from the diretory structure you will get a name clash in this situation.

**Comment by pramodk** [comment]
@alalazo @hartzell @adamjstewart : thank you for all feedback. Finally I got this setup as I wanted!

Before that here is why I would like to have setup this way : our software stack include simulators/tools for neuroscience that I want to develop/deploy on hpc systems where compilers, mpi stack is already provided (MIRA, TITAN, Piz Daint). I then deploy our stack using 2-3 compilers on these system. Our `end users` will go to these systems and use pre-installed software stack. If necessary, they should be able to swap/switch between compilers with minimal efforts (hence I started looking at lmod).

And thats why there was no `core` compiler / compiler installation from scratch.

Here are all steps in case someone else want to setup.

Following @alalazo suggestion I added `dummy` compiler `gcc@4.4` in `compilers.yaml`. Then I added entries to `packages.yaml` as:

```bash
    gcc:
        paths:
            gcc@4.9.4%gcc@4.4: /usr/local
        buildable: False
        version: [4.9.4]

    llvm:
        paths:
            llvm@8.1.0-apple%gcc@4.4: /usr/local
        buildable: False
        version: [8.1.0-apple]
```

Then registered compilers into DB by trying to install them :

```bash
spack install gcc@4.9.4 %gcc@4.4
spack install llvm %gcc@4.4
```

Now I added `gcc@4.4` as core compiler in `modules.yaml` :

```bash
  lmod:
    core_compilers:
      - 'gcc@4.4'
```

If I now look at generated modules I see only compilers:

```bash
spack module refresh --delete-tree -y -m lmod && module av

------------- /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64/Core -------------
   gcc/4.9.4    llvm/8.1.0-apple
```

Loading `llvm` shows packages built using `clang/llvm` :

```
$ module load llvm/8.1.0-apple
$ module av

------ /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64/clang/8.1.0-apple -------
   mod2c/develop    mpich/3.2    neurodamus/develop    neuronperfmodels/coreneuron    python/2.7.10

------------- /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64/Core -------------
   gcc/4.9.4    llvm/8.1.0-apple (L)
```

If I load some modules and try to swap `llvm` by `gcc` then all loaded modules get switched:

```bash

$ module swap llvm gcc

Due to MODULEPATH changes, the following have been reloaded:
  1) neurodamus/develop     2) neuronperfmodels/coreneuron

$ module av

---------- /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64/gcc/4.9.4 -----------
   mod2c/develop    mpich/3.2    neurodamus/develop (L)    neuronperfmodels/coreneuron (L)    python/2.7.10

------------- /Users/kumbhar/workarena/software/sources/spack/share/spack/lmod/darwin-sierra-x86_64/Core -------------
   gcc/4.9.4 (L)    llvm/8.1.0-apple

```

Yay! All works fine!
