### ISSUE TITLE
Running 'spack mirror create' tries to look for compiler using local os spec

### ISSUE THREAD

**Issue by mcfadden8** [spack/spack#5147]
I received the following error when attempting to create a mirror for a rhel7 os on a machine that was running rhel6:
```
spack mirror create -d `pwd` -D -o tmux@2.4 os=rhel7 %gcc@4.8.5
==> Error: No compilers with spec gcc@4.8.5 found for operating system rhel6 and target x86_64
```
I worked around the problem by creating a fake compiler entry for gcc@4.8.5 for rhel6 in the compilers.yaml file.

**Comment by adamjstewart** [comment]
Mirrors aren't dependent on OS, are they? Why are you specifying the OS?

**Comment by becker33** [comment]
@adamjstewart I was working with @mcfadden8 on this.

Yes, in this particular case it would not have come up if we didn't specify the os. I can look at the packages and confirm that we don't change the dependency tree by changing the os.

However, we could theoretically have packages with different dependencies depending on os, target, or compiler. Spack has to concretize the given specs to determine which dependencies to download when using `spack mirror create -D`, so it fails when concretizing to a nonexistent compiler. It would be nice if we could make the non-existence of the compiler a warning instead of an error in this context, so that we can accurately download the packages for a different machine (which seems to be the entire point of the mirror).

**Comment by adamjstewart** [comment]
@scheibelp?
