### ISSUE TITLE
Julia package builds only run on the x86_64 CPU family they were compiled on

### ISSUE THREAD

**Issue by wccropper** [spack/spack#5224]
I have found that I can only run the spack compiled module of Julia on the same family Intel CPU it was compiled on. It complains if you run on any other family. "ERROR: Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}." I have compiled on our oldest family (Nahalem). Based on my experience with compiling R on my cluster (non-Spack) by compiling on the oldest family, it will run everywhere. This was not the case with the Julia package.

**Comment by tgamblin** [comment]
@eschnett: do you know if Julia does something arch-specific to nehalem in the build that wouldn't be compatible with later generation intel chips?

**Comment by eschnett** [comment]
Yes, Julia pre-compiles packages and uses architecture-specific code. For example, the way in which floating point vectors are passed (SSE registers or AVX registers) depends on this. In essence, there exist several incompatible x86_64 ABIs.

As a work-around you can manually specify the architecture when you run Julia. Specifying the older architecture on a newer system should work fine, as the CPUs are backward compatible. The only drawback is that you will see a lower speed since certain optimization will be omitted. I don't recall how to do this -- however, this is a Julia-specific issue and not related to Spack.
