### ISSUE TITLE
Using "spack view symlink" with xSDK fails

### ISSUE THREAD

**Issue by AlexisPerry** [spack/spack#5237]
I have installed xSDK with Spack and I want to grab all the involved packages and put them in one place that is easy to refer to.  I am currently using Spack's "view symlink" capability to do this.  However, it fails every time with the following message...

...
==> Warning: Skipping existing file: /home/aperry/local/amanzi/tpls/lib64/valgrind/arm-with-vfpv3.xml
==> Warning: Skipping existing file: /home/aperry/local/amanzi/tpls/lib64/valgrind/mips-linux-valgrind.xml
==> Warning: Skipping existing file: /home/aperry/local/amanzi/tpls/lib64/valgrind/power-vsx-valgrind-s2.xml
==> Warning: Skipping existing file: /home/aperry/local/amanzi/tpls/lib64/valgrind/vgpreload_memcheck-amd64-linux.so
==> Warning: Skipping existing file: /home/aperry/local/amanzi/tpls/lib64/valgrind/s390x-core64-valgrind-s2.xml
==> Error: [Errno 17] File exists

Obviously, there are many more warnings than that, but it's the error that is troubling.  It is my understanding that xSDK is about having a cohesive set of software that all play well together.  How then is it an error to try and install them all in the same place?  Warning about copying existing files is one thing, but throwing an error is a different thing all together.

**Comment by aprokop** [comment]
Ping @amklinv

**Comment by healther** [comment]
@obreitwi and I ran into similar problems. In our case it turned out that some packages disregard any courtesy and just blast their stuff in global directories (notably ```llvm``` shipped a ```six.py``` and ```tensorflow``` shipped its own ```wheel.py``` directly into the ```site-packages```-folder). We worked around that by basically just ignoring any occurrence of the file beyond the first.

@obreitwi did you get around to include that into #3227?

On a more general note: How should ```spack``` handle such conflicts? (Besides reporting a more informative error?) In our case the ```six.py``` was functionally identical, but had formatting differences -> It is not possible to do just a check whether the files are identical...

**Comment by joymcclemens** [comment]
@BarrySmith @tgamblin

**Comment by amklinv** [comment]
@BarrySmith @tgamblin

**Comment by AlexisPerry** [comment]
This is still a problem.  Any updates on status?

**Comment by alalazo** [comment]
Closing as stale and possibly outdated, but feel free to reopen if I'm wrong. Since this issue was opened we have environments which support `views` and `projections` to deal with cases where packages try to overwrite each other.
