### ISSUE TITLE
Cray, cross-compiling environment and MODULEPATH

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#5274]
Hello,

I find it confusing and hence thought I should ask:  on Cray systems, by default module path is pointing to backend arch, e.g.

```
$ spack arch
cray-CNL-mic_knl

$ echo $MODULEPATH
/gpfs/some-path/spack/share/spack/modules/cray-CNL-mic_knl
```

`spack find` shows packages that we have built for both arch: 

```
$ spack find
==> 32 installed packages.
-- cray-CNL-haswell / intel@17.0.0.098 --------------------------
mpich@7.6.0  tau@2.26.2

-- cray-CNL-mic_knl / cce@8.6.0 ---------------------------------
cmake@3.5.2  coreneuron@develop  mpich@7.6.0  neurodamus@develop  reportinglib@develop
```

When we try to load packages for font-end arch we get:
```
$ spack load tau arch=cray-CNL-haswell
ModuleCmd_Load.c(244):ERROR:105: Unable to locate a modulefile for 'tau-2.26.2-intel-17.0.0.098-suv5xlb'
```

One can manually set `MODULEPATH` to appropriate directory and then it works fine.
But, could we do this automatically (i.e. without setting MODULEPATH manually) ?

**Comment by scheibelp** [comment]
It looks like this is because the modules are split into directories based on architecture and for now setup-env.sh only adds one of them (in this case the back-end). It should be possible to detect if there are multiple viable architectures and add them both.

**Comment by albestro** [comment]
Hi,
I know that it is an old comment, but I hope this may help someone or it may be a way to restart thinking about this problem and solve it.

I'm also working in a Cray environment, cross-compiling code for two different architectures.

After digging into the mechanism, this is what I understood:
- `setup_env.sh` calls `spack --print-shell-vars sh,modules` and from its output extracts both system architecture in `_sp_sys_type` and all the available roots for modules (e.g.` _sp_tcl_roots`)
- `_sp_*_roots` are used as prefixes for populating `MODULEPATH` environment variable and letting `module` find modules managed by Spack
- `_sp_sys_type` is populated with `spack.architecture.sys_type()`
- `spack.architecture.sys_type()` returns the string representation of an `Arch` object, i.e. _platform-os-target_
- `Arch` internally uses a `Platform` object and in our particular case this object is an instance of the specialization `class Cray(Platform)`
- `Cray(Platform)` is responsible for setting the *target* throug the next code snippet, from which is clear that, for what concerns the backend, it looks for an hint from environment variable `SPACK_BACK_END`, and in case it does not exists it defaults to the default architecture.

https://github.com/spack/spack/blob/ba0cd4d912ef66908a0e560cdbdc6f8cbf633390/lib/spack/spack/platforms/cray.py#L57-L67

The default architecture is computed with next code snippet, and it consists in launching a subshell with a clear environment and getting the value of the environment variable `CRAY_CPU_TARGET`.

https://github.com/spack/spack/blob/ba0cd4d912ef66908a0e560cdbdc6f8cbf633390/lib/spack/spack/platforms/cray.py#L111-L125

Since it is a new shell with a clean environment, it will always fall into default architecture. So without setting `SPACK_BACK_END`, it is not possible to have in MODULEPATH modules for an available platform different from the default one.

What I'm doing, not knowing if it is a solution or just a workaround, it is to set `SPACK_BACK_END` before calling `setup_env.sh`. In this way, Spack setup will set my `MODULEPATH` with modules for the specified target architecture. But, this allows to have modules just from one target architecture at a time, and it may lead to problems in case of cross-architecture dependencies.

**P.S. In order to manage `SPACK_BACK_END` automatically before `setup-env.sh`, I have few lines in `.bashrc` that allows me to choose what target machine I want to use and it acts accordingly**

**Comment by becker33** [comment]
Since the `cray` platform is deprecated, and cray systems are now utilized directly as `linux`, this issue is outdated.
