### ISSUE TITLE
setup-env.sh not adding lmod files to MODULEPATH

### ISSUE THREAD

**Issue by deOliveira-R** [spack/spack#5377]
I was having a problem where I wanted to use lmod for hierarchical modules but it was not working. Lmod itself was working fine as a environment module manager, but only tcl files in **share/spack/modules** were added to MODULEPATH. Whereas in my case, **/share/spack/lmod** should be the target folder.

Upon closer inspection of the code block starting at line 239 in setup-env.sh, it appears that it doesn't check if one wants to use tcl or lmod in order to add the correct folder to MODULEPATH:

[setup-env.sh.bak.txt](https://github.com/LLNL/spack/files/1308294/setup-env.sh.bak.txt)

For my particular problem, I fixed the issue by adding some lines and commenting the one that adds tcl module to MODULEPATH, as shown:

[setup-env.sh.txt](https://github.com/LLNL/spack/files/1308295/setup-env.sh.txt)

This works, but is this really the only way to do it at the moment? Did I miss something?

**Comment by alalazo** [comment]
Relates to #3057 . Before that PR nothing was set automatically after sourcing `setup_env.sh`, so the burden was still upon the user. I think we need to extend the logic to allow a user to configure Spack so that it will prefer Lmod by default.

**Comment by scheibelp** [comment]
> Relates to #3057 . Before that PR nothing was set automatically after sourcing setup_env.sh

To be clear, the lines set by the user are not affected by #3057, for example:

> _spack_pathadd MODULEPATH "${_sp_tcl_root%/}/$_sp_sys_type"

This existed before #3057 so I'm not sure if #3057 is directly related. #3057 *is* the first PR to define commands in the user's shell in certain cases (namely the `module` command).

IMO this is also related to discussion in https://github.com/LLNL/spack/issues/5351, which gets into what module system should be set up by default.

**Comment by krafczyk** [comment]
@deOliveira-R I've created #5955 Which should solve this issue. Please give it a try!

**Comment by alalazo** [comment]
Closing since `setup-env.sh` is not meant to be working with `lmod`. The entire point of setting MODULEPATH in the shell integration script is to make `spack load/unload` work. The fact that up to now this has been done using `environment-modules` as a driver is to be considered imo an implementation detail. There's currently a PR that will drop the dependency on `environment-modules`, see #14062

**Comment by becker33** [comment]
@alalazo I disagree. I think that even with `spack load/unload` working without modules, Spack should add the user's modules to their modulepath appropriately for any module systems they have enabled.

**Comment by alalazo** [comment]
> I disagree. I think that even with spack load/unload working without modules, Spack should add the user's modules to their modulepath appropriately for any module systems they have enabled.

There are two main arguments against managing `MODULEPATH` from Spack init script, once we have a mean to make `spack load/unload` work without modules. 

The first one is that if we keep setting `MODULEPATH` as we do now in `setup-env.sh` we can't get rid of:

https://github.com/spack/spack/blob/3cd6ca02d2d58c42d6864b25ed5e4479557eaa8c/share/spack/setup-env.sh#L306-L327

which slows down the start-up because it needs a call to Spack (and thus we need to pay for the starting time of the Python interpreter). In my opinion getting rid of that part is some added value that #14062 can bring.

The second one is that managing **any** module system that the user has enabled might not be feasible without complicating further the init script, instead of simplifying it. Currently we support the generation of `tcl` and `lmod` module files and there has been talk in the community on Slack to add a new type of TCL module using `environment-modules` v4 flavors. All  of the above module systems rely on `MODULEPATH` being set to some specific path for them to work correctly and all of them might be enabled at the same time within Spack. They also have different requirements in terms of tools and version of the tools that can be used with them. I don't think it is Spack responsibility, in particular during initialization, to check:

1. Which module systems are enabled
2. Which module commands do we have on the system and with which of the generated modules are they compatible
3. Which one should in the end be activated from the pool computed at point 2

I'd rather just provide convenience functions for the above module system to generate valid shell code that any user can then append to their init script if they want and need it.

**Comment by becker33** [comment]
@alalazo Ok that sounds like a good plan to me. We could (and probably should) even put the wrappers in the `spack` shell function so that the modules for any given system can be automatically added by `spack module <type> init`, while `spack module <type> init --sh` would give the bash code for it (like we do for `load/unload/env activate`).
