### ISSUE TITLE
Version requested in packages.yaml not respected

### ISSUE THREAD

**Issue by citibeth** [spack/spack#548]
I requested the following in my packages.yaml:

```
    pism:
        version: [local]
```

There is no version called "local" in pism/package.py; only 0.7.3.  The "local" version was installed by running "spack diy" (actually, spack spconfig, which is pretty equivalent for our purposes here).

I then requested:

```
spack spec icebin@local +python +coupler +pism ^netlib-lapack+shared ^netlib-blas+fpic ^netcdf+mpi ^eigen~suitesparse ^python@3:
```

Spack tried to get pism@0.7.3, ignoring the request for local in packages.py.  My guess is it did an algorithm as follows:
1. User made no version request on command line.
2. Default in packages.yaml is "lcoal"; let's see if we can find such a version.
3. pism/packages.py doesn't list any version called "local," so let's throw that out
4. No other defaults are listed in packages.yaml, so just use the latest version listed in pism/packages.py

Not sure what the best approach to solving this issue is.  For now, I'm adding "^pism@local" to my command lines.

**Comment by mplegendre** [comment]
Your guess is essentially correct.

Spack's operations when deciding to re-use an installed package are:
1) Concretize a spec by filling in its version, compiler, options, etc.
2) If the chosen spec is already installed then re-use it.  Else build it.

The preferences are only used in the concretization step, which doesn't currently inspect what's already installed.  We may eventually make concretization look at what's installed (that would be part of the "reuse packages if they're installed" feature request), but it's not there now.

One way to work around that could be to make your DIY an external package.  Have packages.yaml be something like:

pism:
  paths: 
    pism@0.7.3%gcc@4.9.3=linux_x86_64: /spack/pism/install/location
  buildable: False

I think it would need a pism version that matches something from package.py rather than local.

**Comment by tgamblin** [comment]
Once we add the ability to search what is installed, this issue should go away pretty naturally.  I actually think we have most of what we need for that already; I just need to add one more method to search for candidates in `concretize.py`, and some rules to prefer installed packages.

Note to @citibeth based on a comment I read at one point or another: searching installed packages in general does make for a nondeterministic build, but it's also what people expect in many cases by default.  When this gets added, I plan to add an option to install so that you can *not* consider installed packages if you want (so you can still get a nice deterministic build if you don't mind building lots of new stuff).

**Comment by citibeth** [comment]
The issue here is different from a feature that would concretize/fill-in-the-blanks based on what's already installed.  In that feature, Spack would add version information if the user doesn't supply it.  That is the opposite of what's going here, where I've ALREADY GIVEN Spack a version, and it is throwing that information away.  Moreover, Spack works DIFFERENTLY whether I provide that version on the command line, or in packages.py.  I'm suggesting that we make both cases work like it currently does on the command line.

More specifically... when Spack is looking through a list of versions to try in packages.yaml, it should be willing to use versions that are already built, EVEN if the current package.py file is not able to build that version.  With the caveats:
 1. It should be an error, or at least a warning, if packages.yaml suggests a version that Spack doesn't know how to build.
 2. One should be able to turn off this "feature," because it DOES produce non-repeatable builds.  This feature is for use in package development, when you've installed one or more packages with "spack diy" (or equivalent).  (Spack diy is already non-repeatable).

-----------------------------

@tgamblin Yes, I still think that making automatic decisions based on what's already installed is a bad idea:  https://groups.google.com/forum/#!topic/spack/Ut_beZApESg

A better approach would be for Spack to be able to create a packages.yaml file based on what's already there (or add to an existing packages.yaml file, if there are any new packages not in it).  You then review/edit the file; and when you have it the way you like,  you can install with respect to that packages.yaml file.  By separating out the yaml-creation step, things are made explicit and repeatable.  It also allows the user to intervene in cases where there are many things already installed and it's not clear which version you want Spack to use.  Would that be:
  (a) The most recently installed?
  (b) The one with the highest version number?  (Remembering that Spack cannot always tell an ordering between version numbers, since it allows versions to be any string at all.)
  (c) The one with the variants you care about (which you didn't necessarily specify at first)?

Making this approach work would require the following upgrades to packages.yaml infrastructure.  I suggest we pursue these upgrades before tackling the install-based-on-what's-there problem:
 1. Multiple packages.yaml files that override each other in some order (rather than one in /etc and one in $HOME/.spack).
  2. Get variants working in packages.yaml

If Spack is changed to actively search installed packages when concretizing... then please, make it an optional feature that can be turned off.  I think this is the kind of feature that users THINK they want, and it seems natural --- but once it gets implemented, it will produce an unending stream of "why did Spack do this" questions.

**Comment by alalazo** [comment]
Closing as possibly outdated. Currently, with the ASP-based solver, externals are always preferred over rebuilding something and version preferences are taken into account *if* the version exists in `packages.py`. If this issue maps to prefer already installed packages, there are already other issues tracking that. Feel free to reopen if I missed something.
