### ISSUE TITLE
How to use ccache with spack?

### ISSUE THREAD

**Issue by aprokop** [spack/spack#5504]
It seems to me that because spack uses full paths to `gcc` and other compilers, there is no place to inject `ccache` to use it. Does anybody use Spack with ccache? If yes, how do you manage to do that? Particularly, in combination with mpi wrappers?

**Comment by junghans** [comment]
See #3761

**Comment by mayrmt** [comment]
@aprokop Did your question (and the proposed fix) aim at "using ccache to cache compilations of spack packages", i.e. to speed-up recurring compilations of packages managed by spack, or to a development scenario, where spack provides packages (e.g. some mpi implementation, maybe even a compiler, ccache) in order to build a non-spack software, while using ccache for that non-spack software? 

I'm very interested in the latter scenario, but I'm not sure, whether the fix done in #3761 by @junghans matches that scenario. Can anyone outline, how to setup spack's ccache installation to work for the development scenario outlined above? Thanks!

**Comment by junghans** [comment]
Once you have ccache installed you can use it like described here:
https://stackoverflow.com/questions/13929514/how-to-enable-ccache-on-linux
incl. non-spack compiles.

**Comment by mayrmt** [comment]
@junghans Thanks for your quick help! On machines, where I don't use spack, I usually use symbolic links to let ccache masquerade as the compiler as described in the ccache manual's section on [run modes](https://ccache.dev/manual/latest.html#_run_modes). That works just fine. 

Now, with spack, I'm not sure, which symbolic link to set to warp for example `mpicxx`. When typing `which mpicxx`, I get
```
/Users/mayr/utils/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/openmpi-3.1.4-pghbdlk64r33k6bzmsuo243y2klfpkec/bin/mpicxx
```
Is that the path to be used for the symbolic link, i.e. `ln -s ccache /Users/mayr/utils/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/openmpi-3.1.4-pghbdlk64r33k6bzmsuo243y2klfpkec/bin/mpicxx`?

**Comment by junghans** [comment]
Just run `mpicc --showme` to see which compiler is called under hood and hence needs to be symlinked.

**Comment by mayrmt** [comment]
I intend to use `ccache` not for caching compilations of spack-installed packages, but rather to install `ccache` via spack and then use it in my development toolchain for software, that's not packaged via spack, but just uses spack to obtain its external dependencies.

Here's my solution for `CMake` projects:
1. Install and load `ccache` via spack
2. Add `-D CMAKE_CXX_COMPILER_LAUNCHER:FILEPATH="ccache"` to the `cmake` command
3. Configure and build
