### ISSUE TITLE
Feature request: enhance version range specification

### ISSUE THREAD

**Issue by wrwilliams** [spack/spack#5795]
If you wish to construct a package with multiple active development versions, you're forced into awkward dependency semantics for any changed dependencies. Where you would ordinarily say:
```
depends_on(old_dep_spec, when=@:last_old_version)
depends_on(new_dep_spec, when=@first_new_version:)
```
you now must say:
```
depends_on(old_dep_spec, when=@0.0.0:last_old_version)
depends_on(new_dep_spec, when=@first_new_version:@999.999.999)
depends_on(WIP_dep_spec, when=@develop)
depends_on(WIP_dep_spec, when=@some_dev_branch)
```
It would be convenient to have a way to express the following concepts:

1) Explicit half-open version intervals, rather than repeating nines as a hack.
2) Named versions may be ordered with respect to each other and with respect to numeric versions
3) \@develop should be a marker for "first version of those that are named and successors to all numeric releases"

This allows the above to become:
```
depends_on(old_dep_spec, when=@:first_new_version)
depends_on(new_dep_spec, when=@first_new_version:@develop)
depends_on(WIP_dep_spec, when=@develop:)
```
possibly with an explicit marker for half-open intervals, and allows master and some_dev_branch to be named versions rather than a single variable \@develop.

**Comment by davydden** [comment]
does this https://github.com/LLNL/spack/pull/1983 do what you want? You would be able to say `@develop.1 < @develop.2` as well as `1.9 < 1.develop`.

**Comment by junghans** [comment]
While we are at it, it would be nice to have something like:
```
depends_on("xxx", when="@1.*")
```

**Comment by davydden** [comment]
@junghans that should be possible with  #1983 

```
depends_on("xxx", when="@1:1.develop")
```

(note that that PR introduces other names in addition to `develop`)

**Comment by wrwilliams** [comment]
#1983 is a step in the right direction, I think. My use case is the following:

* released code has one set of dependencies
* current master incorporates one dependency change
* topic branch incorporates more new dependencies

I'd like to be able to specify `@latest_release < @master < @topic` for active topic branches, and `@base_old_release < @topic < @next_old_release` for archived topics. Certainly #1983 can be forced in that direction but it loses the meaningful names.

Or is the right thing to do here to construct named variants for these topic branches rather than adding versions?

**Comment by davydden** [comment]
> #1983 is a step in the right direction, I think.

@tgamblin  ^^^ :smile: 

> current master incorporates one dependency change

That can be done right now. Look at `dealii`, current stable is `8.5.1`, but there is `depends_on("assimp",           when='@9.0:+assimp')` which for now will work only with `@develop`, but once `9.0` (next release) is out, it will keep working OOB.

> Certainly #1983 can be forced in that direction but it loses the meaningful names.

i think you can play around with #1983 to still keep meaningful version names, i.e.  `1.0 < 1.develop.my_topic < 2.0`. Not ideal, but should serve the purpose. To save some space and hopefully make it more readable for users, one could add `infty` to #1983 so that `infty > develop > master > head > trunk > 12345 > otherstring` with a convention that `infty` is only to be used as `@1.infty.1234abc` instead of `@infty` (not that it changes the code, of course, just for convenience).

> is the right thing to do here to construct named variants for these topic branches rather than adding versions?

probably not, you want to checkout different code snapshots (diffeerent branches), So it is indeed a different version. 

You can also `grep` for `xsdk` in versions (i.e. `trilinos`, `petsc`, `superlu-dist`) that approach this problem by prefixing versions with `xsdk`, i.e. `xsdk-x.y.z`. Downside is that you need to duplicate `depends_on()`. That's probably OK there as version numbers are absolutely different (i.e. `xsdk-0.2.0` vs `12.2.2`) so the two live in somehow different universes although functionality is certainly overlapping.

**Comment by mathstuf** [comment]
Using a semver style specifications would be nice to have. I don't know if the parser would be robust to it, but Rust's Cargo uses [some special characters](http://doc.crates.io/specifying-dependencies.html) to indicate version ranges. For example `python@^2.7` would indicate compatible with any `2.7.x` or `2.8` while excluding `3` since the major version bump is a break that `^` won't bridge. `python@~2.7` would be similar, but also disallow `2.8`.

This works best for projects which actually follow semver, but it might be an option to ranges.

**Comment by tgamblin** [comment]
I agree about semver, although we already have some special characters in Spack -- we'd need to see if this would make the parsing hard, or maybe we could just support them in packages.  We can't do semver everywhere, though, as not every package supports semver.  But that doesn't mean we can't support the semantics.

**Comment by becker33** [comment]
We have settled on improved version semantics in #36273
