### ISSUE TITLE
spack view needs to install sitecustomize.py for easy_install.pth to be found

### ISSUE THREAD

**Issue by kljohann** [spack/spack#6131]
(I just wanted to open an issue since this was not obvious to me and should perhaps be fixed in the spack view code.)

When using #3227 to create a spack view that both contains python and a python package installed as a `.egg` file (i.e. present in `easy_install.pth`), a python process started via the spack view path fails to import that package.
As explained in e.g. https://docs.python.org/2.7/library/site.html, python will look inside the `site-packages` directory relative to `sys.exec_prefix` and `sys.prefix` for `.pth` files:
> Importing this module will append site-specific paths to the module search path and add a few builtins.
> It starts by constructing up to four directories from a head and a tail part. For the head part, it uses sys.prefix and sys.exec_prefix; empty heads are skipped. 

But those do not point into the filesystem view but to the install directory of the package:

```
In [3]: sys.exec_prefix
Out[3]: '/path/to/spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/python-2.7.13-jtpih7wfgjrzzk4reevynswu54pmif5m'

In [4]: sys.prefix
Out[4]: '/path/to/spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/python-2.7.13-jtpih7wfgjrzzk4reevynswu54pmif5m'
```
Consequently python will not see the `easy_install.pth` created by `spack view`. I was able to work around this by using `export PYTHONUSERBASE=/path/to/spack/spackview/`.

But perhaps `spack view` should create a `sitecustomize.py` inside the `site-packages` of the view directory to adjust the site prefix path such that `sys.prefix` points to the filesystem view:
> After these path manipulations, an attempt is made to import a module named `sitecustomize`, which can perform arbitrary site-specific customizations.
> `site.addsitedir(sitedir, known_paths=None)`
>    Add a directory to sys.path and process its .pth files. Typically used in sitecustomize or usercustomize (see above).

From looking at #5415 this issue still is present in the merged version. Maybe @mathstuf or @obreitwi can share their thoughts.

**Comment by kljohann** [comment]
Note that setting `PYTHONUSERBASE` is not a long-term solution since this will lead to `pip install --user` installing into the spack view. This may a) lead to unintentionally messing up the spack view b) "permission denied" errors for users. Users may want to install things in their home using `--user`, which is a legitimate request from my point of view ;)
So there does not seem to be a way around the `sitecustomize.py`.

**Comment by scheibelp** [comment]
Hi @kljohann thanks for the detailed explanation! I am planning on fixing this within the next few weeks

**Comment by opadron** [comment]
I've been testing different configurations locally to reproduce this issue.  What I'm finding is that `sys.prefix and sys.exec_prefix` always seem to point to the install directory, as that is where the real, non-symlink, python binary lives. As far as I can tell, you would need to add a `sitecustomize.py` file to the *install* directory -- not the view, as python is blissfully unaware of it as far as finding packages go.  Of course, that's not workable since a python install can be part of multiple views and figuring out which one to use isn't feasible.

The only way I managed to get python to see the package is to set `PYTHONPATH`, which as I understand it, defeats the purpose of manually installing packages into a view.

IMO, the long-term solution is to make views work like virtual environments, with some activation command to "enter" the environment.  Care would be taken to create an environment compatible with python's virtualenv tool, so that pip, easy_install, and others just work as expected (and, of course, the right packages are actually found).  We can look to conda for prior art.

P.S.: I'm willing to bet the above behavior in the presence of symlinks is why environments created using virtualenv don't symlink to the original python executable, but make a copy and symlink to that, instead.

**Comment by opadron** [comment]
ping @tgamblin

**Comment by kljohann** [comment]
In fact what we do is to set several variables (including `PYTHONPATH`) to point to the spack view using a module file:
```tcl
set module_basedir /.../spack/view

prepend-path  PATH                ${module_basedir}/bin
prepend-path  PYTHONPATH          ${module_basedir}/lib/python2.7/site-packages
prepend-path  MANPATH             ${module_basedir}/man
prepend-path  MANPATH             ${module_basedir}/share/man
prepend-path  LIBRARY_PATH        ${module_basedir}/lib
prepend-path  LIBRARY_PATH        ${module_basedir}/lib64
prepend-path  LD_LIBRARY_PATH     ${module_basedir}/lib
prepend-path  LD_LIBRARY_PATH     ${module_basedir}/lib64
prepend-path  TCLLIBPATH          ${module_basedir}/lib
prepend-path  CPATH               ${module_basedir}/include
prepend-path  C_INCLUDE_PATH      ${module_basedir}/include
prepend-path  CPLUS_INCLUDE_PATH  ${module_basedir}/include
prepend-path  PKG_CONFIG_PATH     ${module_basedir}/lib/pkgconfig
prepend-path  PKG_CONFIG_PATH     ${module_basedir}/lib64/pkgconfig
prepend-path  CMAKE_PREFIX_PATH   ${module_basedir}
```
Due to the changed `PYTHONPATH` most imports will work. However, as reported above, packages installed as python eggs do not work, even though they are registered in `/.../spack/view/lib/python2.7/site-packages/easy-install.pth` by the `spack view` code. This is due to the fact that python will not consider this directory. Python _would_ however look for a `sitecustomize.py` module in this directory (as it's on the `PYTHONPATH`).

Our current work-around is to set
```
prepend-path  PYTHONUSERBASE      ${module_basedir}
```
however this is not optimal, as described above.

**Comment by scheibelp** [comment]
@kljohann 

https://github.com/spack/spack/pull/7152 updates how python is linked into views: it allows packages to customize how they are added to views and Spack's python package is updated to copy in the python binary (so sys.exec_prefix should be correct now).
