### ISSUE TITLE
Spack using system CMake instead of Spack CMake

### ISSUE THREAD

**Issue by rspavel** [spack/spack#6202]
I noticed a similar error on a few other spackages but llvm seems to trigger it most consistently. It appears that even though Spack thinks it is using the specified version the path is not set up to actually use the intended CMake. So if your platform has a particularly old version of CMake, it is unable to build things that are dependent on more modern features

```
[rspavel@cn212 ~]$ spack install llvm
...
==> cmake@3.7.1 : externally installed in /projects/opt/centos7/cmake/3.7.1/bin/cmake
==> cmake@3.7.1 : already registered in DB
...
==> Building llvm [CMakePackage]
==> Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '/home/rspavel/Software/spack/var/spack/stage/llvm-5.0.0-r2jo5zftpctuqjouhlzacb2fc4mlezgr/llvm-5.0.0.src' '-G' 'Unix Makefiles' '
...

1 error found in build log:
     [ ... ]
  >> 3     CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
     4       CMake 3.4.3 or higher is required.  You are running version 2.8.12.2
     5
     6
     7     -- Configuring incomplete, errors occurred!
...
[rspavel@cn212 ~]$ cat ~/.spack/packages.yaml
packages:
    cmake:
        paths:
            cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/bin/cmake
        buildable: False
[rspavel@cn212 ~]$ /projects/opt/centos7/cmake/3.7.1/bin/cmake --version
cmake version 3.7.1
[rspavel@cn212 ~]$ /usr/bin/cmake --version
cmake version 2.8.12.2
[rspavel@cn212 ~]$ spack env llvm which cmake
/usr/bin/cmake
```

**Comment by davydden** [comment]
i think the reason is your external CMake.

> cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/bin/cmake

You need to specify installation `prefix` of the package.

Spack can use external package when whey comply with default directory structure for that package. In case of `cmake` you should have `<prefix>/bin/cmake`. So it looks like you should have had

```
cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/
```

in your `packages.yaml`. 

Please re-open if the issue persist.

**Comment by davydden** [comment]
i think the reason is your external CMake.

> cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/bin/cmake

You need to specify installation `prefix` of the package.

Spack can use external package when whey comply with default directory structure for that package. In case of `cmake` you should have `<prefix>/bin/cmake`. So it looks like you should have had

```
cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/
```

in your `packages.yaml`. 

Please re-open if the issue persist.

**Comment by davydden** [comment]
i think the reason is your external CMake.

> cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/bin/cmake

You need to specify installation `prefix` of the package.

Spack can use external package when whey comply with default directory structure for that package. In case of `cmake` you should have `<prefix>/bin/cmake`. So it looks like you should have had

```
cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/
```

in your `packages.yaml`. 

Please re-open if the issue persist.

**Comment by tgamblin** [comment]
We could probably catch stuff like this by adding [`sanity_check_file()`](https://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=sanity%20check#checking-an-installation) to more packages (especially those used as externals) and actually executing the sanity checks on externals before we build with them. 

@rspavel: any interest in adding that?

Also, what does your external specification for `cmake` look like?

**Comment by tgamblin** [comment]
We could probably catch stuff like this by adding [`sanity_check_file()`](https://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=sanity%20check#checking-an-installation) to more packages (especially those used as externals) and actually executing the sanity checks on externals before we build with them. 

@rspavel: any interest in adding that?

Also, what does your external specification for `cmake` look like?

**Comment by rspavel** [comment]
I could definitely go through some spackages to add sanity checks (and probably should have from the start...), although adding one to the base CMakePackage class would probably make the most sense for this specific case (but would also require me to learn another part of spack as I have mostly stuck to the spackage side of things). I'll gladly take a look, but it won't be the most efficient solution

And I could have sworn this was the config that was generated by spack finding cmake for me (I recall pointing out to a colleague that one of our more tedious annoyances was resolved), but am not at all going to rule out a PEBKAC as I manually added a few on a different platform while getting things working there. This was the original spec in packages.yaml

```
[rspavel@cn212 ~]$ cat ~/.spack/packages.yaml
packages:
    cmake:
        paths:
            cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/bin/cmake
        buildable: False
```

And making the suggested change appears to have fixed it (or at least spack got to build and is chugging away doing something)
```
[rspavel@cn212 ~]$ cat ~/.spack/packages.yaml
packages:
    cmake:
        paths:
            cmake@3.7.1: /projects/opt/centos7/cmake/3.7.1/
        buildable: False
```

**Comment by tgamblin** [comment]
Awesome!

For the problem here, I think you could just add `sanity_check_file('bin/cmake')` to Spack's cmake package (`spack edit cmake`), as that's what's being added as an external.  We'll need to add some logic in `build_environment.setup_package()` to actually call `Package.sanity_check_prefix()`, which is currently only executed after installation.

I'm not sure adding stuff to `CMakePackage` helps here, as that's just a superclass for packages that use cmake.  It would add checks to everything that derives from it, and you don't know the install layout of all the packages -- some might have `bin/foo` and others might have `bin/bar`, etc.
