### ISSUE TITLE
How to use a different install_tree for a local package repository

### ISSUE THREAD

**Issue by KineticTheory** [spack/spack#6204]
I have a local package repository that contains software that I want to install in a different `install_tree` than the normal spack location (`$spack/opt/spack`).  Is there a configuration option that allows me to do this?  

The idea is to keep installations of proprietary, locally developed packages separate from open source packages provided by spack.  As a work around, I may be able to hack `~/.spack/config.yaml` to temporarily use a different `install_tree`, but this is cumbersome.

Any ideas on how to achieve this layout?

**Comment by tgamblin** [comment]
I'd like to provide more first-class support for this, but for now there isn't a (good) way.  If you want to hack it in, modify the `path scheme` in `lib/spack/spack/directory_layout.py` -- look at `YamlDirectoryLayout` (which is a somewhat esoteric name but refers to the fact that it's sticking `spec.yaml` files in the prefix).  

If your local packages are in their own repository, you can key off of the namespace of specs passed to `relative_path_for_spec()` to force them into a different location.  Bulitin stuff will be in namespace `builtin`, and your stuff will be in whatever you called your repo namespace.

Worst case you can set Spack's install root to `/` and map packages from one namespace to `/path/to/open/stuff` and your own stuff to `/path/to/closed/stuff` in `relative_path_for_spec`.

Does that help enough for now?

**Comment by mwkrentel** [comment]
You could clone the spack repo twice, config one with your satellite
repository and the other not and put different config files in
$spack/etc/spack.  (Of course, you'd have to disable the ~/.spack/
files because they would take precedence.)  But really, this is just
as clumsy as swapping config files in and out.

What you'd really like (and what I'd like) is the ability to specify
things like install_tree from the command line.  But rather than
adding a bazillion new options, I propose adding a single new option
to specify an alternate config directory.

spack install -E <dir> package ...

That's -E for etc.  This would tell spack to look in <dir> for
possible config files, but with <dir> having the highest precedence.
Note: for this to work, pretty much all spack commands would need to
recoginze the new option, but they would all treat it the same way.

Todd -- would that be feasible?  Spack already has a search path of 4
directories for config files.  Is it that hard to add a 5th from the
command line?

Btw, I've always considered how spack treats its config options to be
a bit rigid.  Offering an option to push this to the command line
would offer a lot more flexibility.

Now, if what you really want is to write a single config file that
says treat this namespace this way and that namespace some other way,
then that requires hacking the format of the config files.  That's why
I suggest a single command line option.

--Mark

**Comment by KineticTheory** [comment]
Spack chain (#8722) will resolve my particular UseCase.

**Comment by markyoder** [comment]
Is this something that has since been solved with `Spack --config-scope=my_special_config_path/ install ...`.

if not, it looks like `--config-scope` + a `config.yaml file` overriding `install_tree` would do the trick:
```
config:
  install_tree:
    root: $spack/opt/spack_proprietary
```
