### ISSUE TITLE
use local package source in package.py

### ISSUE THREAD

**Issue by mileschen360** [spack/spack#6225]
Can I use a local package source code in package.py?

Usually, the source code for a package is specified by url in package.py. What if I want to use a source code folder that I am currently developing?

**Comment by tgamblin** [comment]
Look at `spack diy`.  It allows you to cd to the source you're developing, build, and install a one-off version of it.  Other than the source location it works similarly to `spack install`.

```console
$ cd /path/to/pkg/source
$ spack diy pkg@1.0-diy
```

The syntax is `spack diy <spec>`.  The spec needs to have a name (here, `pkg`) and a version.  The name is used to pick the right `package.py` file, like you'd expect.  And, since Spack is just taking the source from _right here_, it needs you to tell it what the version is.  This will run the install routine for `pkg` with `.` as the working directory and install it to a prefix for version `1.0-diy`.
