### ISSUE TITLE
How to build Trilinos with cxxflags=-O3

### ISSUE THREAD

**Issue by floquet** [spack/spack#6769]
## Summary

The Trilinos build on Trinitite does not appear to accept the `cxxflags` directive in `compilers.yaml`. 

### Expected Result

With the `compilers.yaml` setting
```
    flags:
      cxxflags: -O3
```
we expected the Trilinos `build.out` file to record C++ compilations using the `-O3` flag. The 1101 C++ compilation and linking statements should look like this

`
.../bin/mpic++   ...  -DMUMPS_5_0 -std=c++11 -O3 -fPIC   .../Amesos_Status.cpp
`

Here is a shorthand version of the build log  [trilinos.build.out.txt](https://github.com/spack/spack/files/1585072/trilinos.build.out.txt)

### Actual Result

While the Trilinos specification acknowledges the `cxxflags` setting,
```
$ spack spec trilinos   
...
Concretized
--------------------------------
trilinos@12.12.1%intel@17.0.4 cxxflags="-O3" ~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost ...
```
the build log indicates defaults settings for `cxxflags` were used. For example

`
.../bin/mpic++   ...  -DMUMPS_5_0 -std=c++11 -O2 -g -DNDEBUG -fPIC   .../Amesos_Status.cpp
`

### Steps to reproduce the issue

We configured Trinitite to only see one compiler, then we built Trilinos:
```console
$ spack install trilinos
```

### Information on your system

This example was created on LANL's Trinitite machine. The compiler configuration was recorded as:
```
$ spack config get compilers
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cxxflags: -O3
    modules:
    - PrgEnv-intel
    - intel/17.0.4
    - craype-haswell
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@17.0.4
    target: any
```

Insights and suggestions are greatly appreciated.

/cc @KineticTheory

**Comment by adamjstewart** [comment]
> we expected the Trilinos `build.out` file to record C++ compilations using the `-O3` flag.

Spack uses compiler wrappers that behave a little differently than you would expect. Since not all packages accept `CC` and `CFLAGS` and friends, Spack is a little more forceful. We add a `cc` wrapper script that appears first in the path and automatically injects things like `CFLAGS` directly into the call to the actual compiler. As a consequence of this, the Trilinos script does not know that we are using these flags, but it should actually be using them behind the scenes. I don't know enough about Trilinos to know if there is an easy way to confirm this. I agree that the `build.out` is a little misleading, but I'm not sure if there's an easy way to fix this. Perhaps we could explicitly set `CFLAGS` and friends in addition to passing them on the command line.

**Comment by scheibelp** [comment]
If you want to see the final flags used for the compiler invocations you can run Spack in debug mode with `spack -d install ...`.

> Perhaps we could explicitly set CFLAGS and friends in addition to passing them on the command line.

Since , you can edit the `trilinos` package to pass compiler flags as arguments to the build system. In particular since `trilinos` is a `CMakePackage` you can do

```
flag_handler = build_system_flags
```

as described in http://spack.readthedocs.io/en/latest/packaging_guide.html#compiler-flags.

*Note*: in the above example this *exclusively* exports flags as build system arguments vs. injecting them into the compiler wrappers. If you want to do both then you would have to define your own flag handler.

**Comment by KineticTheory** [comment]
All CMake-based build systems that do not explicitly set compiler flags via `-DCMAKE_CXX_FLAGS=(whatever)` (and variants) will use the values provided by cmake. For example, for `g++`, CMake automatically uses these flags:

```
CMAKE_CXX_FLAGS ""
CMAKE_CXX_FLAGS_DEBUG "-g"
CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG"
CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG"
CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG"
```

Any additional flags that spack tries to embed into the compile wrappers may be overridden by the default CMake flags.  Assuming that the default `build_type=RelWithDebInfo`, then the optimization level will be `-O2` no matter what `cxxflags` spack tries to set. This leads me to ask the question:

Should the CMakePackage base class automatically set the CMake compiler flags based on spack's xxflags variables?
