### ISSUE TITLE
Installing Perl on an older system

### ISSUE THREAD

**Issue by vikramsg** [spack/spack#6950]
I am trying to build various libraries on an older RHEL system. The problem is I can't even get Perl to build. 

I do 

```
spack build perl
```
and I get

```
./findhdr: line 14: /usr/local/bin/awk: Permission denied
<stdarg.h> NOT found
./findhdr: line 14: /usr/local/bin/awk: Permission denied
<varargs.h> NOT found, but that's ok (I hope).
*** WHOA THERE!!! ***
Your C compiler "cc" doesn't seem to support stdarg or varargs!
 I'm giving up; maybe you can try again with a different compiler?
```
This is on  RHEL, 2.6.32-696.el6.x86_64 with gcc 4.4.7.

So, it seems awk is a problem. But its only /usr/local/bin/awk that is a problem. I tried to do the following in compilers.yaml

```
environment:
  set:
     awk : /usr/bin/awk
```

which doesn't fix the issue since the problem is in the Configure stage. So how do I tell it to use this path for awk during the configure stage.

**Comment by hartzell** [comment]
Your proximate problem seems to be:

1. that you have `/usr/local/bin` earlier on your `PATH` than `/usr/bin`; and
2. you have a `/usr/local/bin/awk` there that you can't execute.

What *is* `/usr/local/bin/awk`?  Why can't you execute it?  If its permissions are wonky, can you fix them so that you can execute it?  If not, can you remove it?

Alternatively, can you remove `/usr/local/bin` from your `PATH`, or at least put it after `/usr/bin`?

**Comment by vikramsg** [comment]
Thanks. Putting `/usr/local/bin` before `/usr/bin` did the trick. 

I could see that there was something wrong with `/usr/local/bin/awk` but I could not do anything about it since I did not have the privileges.
