### ISSUE TITLE
Finish CDash report generation for `spack install`

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#7114]
We have the beginnings of CDash report generation spread over several PRs, but we haven't merged a complete implementation of it to the mainline.  Finish this.  There is currently JUnit logging, and we'd like this to build on the support that's already in place there.

Just as the JUnit logging support creates a `testsuite` with a `testcase` per build, we'd like the CDash support to have a `BuildName` per package install attempt (including recursive ones).  The idea is to have a dashboard for each Spack release (that we're still testing) and another dashboard for continuous builds off of `develop`.

Different types of Spack packages have different sets of build phases.  e.g., `Package` only supports an `install()` method, but `AutotoolsPackage` supports `configure`, `build`, and `install`.  Ideally, there could be columns in the CDash interface for each of these, but we may need to combine some.

The phases of Spack builds that are probably important to show in CDash are:
1. [x] Concretize
    * Happens before the build begins.  If there are concretization errors or Spack errors, we'd like that reported to CDash.  Not currently sure where to put this in CDash format, or whether CDash has a good way to report errors that happen with the build tool itself.
2. [ ] Fetch
    * Fetching the package archive, source repository, and resources.  This could be shoehorned into the `Update` column.
3. [x] Configure or cmake
    * maps nicely to CDash configure phase
4. [x] Build
    * Spack's build and install functions map nicely to CDash's build phase
5. [ ] Install
    * If build and install can be separated somehow, that would be nice, but it is not clear to me where this should go in a CDash build (is there some kind of deploy column?)
6. [ ] Test (if `--run-tests` is supplied)
    * better test support is planned, but not yet implemented, so `--run-tests` happens as part of `do_install()`

If someone runs `spack install trilinos` or `spack install xsdk`, then this should concretize the `trilinos` spec, catch any errors, and if things are clean it should kick off builds for `trilinos` and all of its dependencies, generating reports (unique builds) for each of the dependencies.  This is pretty much how the JUnit testing works, the CDash reporting should just be more thorough.

- [x] The `spack install` command  should be updated to allow a user to easily specify a site and dashboard to which results should be uploaded, or to save XML results in a directory for later upload to CDash.

- [x] You can build on #2917, but the XML format should be generated with more readable/maintainable templates like #6977 and not with `ETree`.

- [x] In configure/install/test phases, the log parsing introduced in #5561 should be used to add specific error entries to the CDash format.

- [ ] Metadata for compiler, OS, variants, and other information from the Spec should be reported as key-value pairs in CDash's new KVP `json` format.  This will allow us to search through Spack builds for releases.

Related issues:
* #2445 First attempt at CDash logging
* #2917 Second attempt (builds on the first attempt)
* #6977 Most recent rework of report logging 
    * improves JUnit output and moves things out of `install` command)

**Comment by alalazo** [comment]
In #6977 @tgamblin said:

> I think that eventually, do_install needs to be refactored to clean this up properly. Monkey-patching package is kind of nasty, and I think Package should really be providing hooks that this uses.

Right now JUnit applies a decorator to `do_install` to collect the information it needs. I fully agree that we should be providing hooks for extensions of this kind, rather than decorate a method on the fly - in particular if we plan to have more than one output format. 

I was looking into `pluggy` (https://pluggy.readthedocs.io/en/latest/) and it seems it might fit our needs + we already vendor it, as it is the plugin system of `pytest`. If people here think it's a good way to go, I can give it a try at adding hooks for the phases above. That could be a good starting point to implement CDash report generation. Let me know if I should start with this or if you have other plans :grimacing: 

@tgamblin @nazavode @mathstuf

**Comment by tgamblin** [comment]
@zackgalbreath: can you update this so that it's clear what's done?

**Comment by JavierCVilla** [comment]
@tgamblin @zackgalbreath Hi guys, sorry for the late answer, I have been playing around with #9357 and I feel a bit confused. Unless I have skipped something, I see that reports are only produced when the build [fails](https://github.com/spack/spack/blob/e5a68327608d6a5e6c0709237517238e0de96c27/lib/spack/spack/cmd/install.py#L216), however I would expect to have reports to be sent to CDash also for successful cases, as it happens with `ctest`. Otherwise, from a CDash dashboard it is difficult to know if a build just failed to upload the reports or simply succeeded. 

What are your insights on this?

**Comment by zackgalbreath** [comment]
> What are your insights on this?

Two things.

1) The line of code that you linked to is only for reporting concretization errors.  Configure/build errors get reported automatically by [decorating do_install](https://github.com/spack/spack/blob/e5a68327608d6a5e6c0709237517238e0de96c27/lib/spack/spack/report.py#L221).

2) You're right, we don't currently report anything to CDash when no errors occur.  Thanks for catching this!  I'll submit a PR to fix this shortly.

**Comment by zackgalbreath** [comment]
> I'll submit a PR to fix this shortly.

#9564

**Comment by tgamblin** [comment]
Fixed by #9564.
