### ISSUE TITLE
Improve Spack's detection of compiler run paths

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#7115]
Spack compiler detection does a pretty good job of finding compiler executables, but there are still configuration issues with certain vendor compilers.  Specifically, users have to add `extra_rpaths` to their compiler entries in `compilers.yaml`, especially for vendor compilers and newer `gcc`/`clang` where the `libstdc++` version is not the same as the system.

Spack should be able to autodetect the necessary compiler runtime paths so that it can add correct `RPATHs` to executables.  This task will add this feature.

- [x] Improve compiler detection so that each compiler can tell Spack how to detect its runtime paths.  Basic functionality can be implemented generically in the `Compiler` class and specialized when needed. (#7153)

- [x] Update the Spack build (`build_environment.py`) so that RPATHs for compiler runtime paths are added automatically via Spack's compiler wrappers. (#7411)

- [x] show that intel compilers no longer need manually configured `extra_rpaths`

**Comment by healther** [comment]
When the compiler detection is changed anyways it might be a good idea to make `spack` pick up all compilers it itself has build. Currently I have to do either a `spack load gcc && spack compiler add` or a `spack compiler add $(spack location -i gcc)`.

[disclaimer: This is from memory and what we are doing in our build pipeline, it might be that this is already fixed or was discussed and deemed not helpful]

**Comment by mathstuf** [comment]
CMake's logic for parsing this information from compilers lives in `Modules/CMakeParseImplicitLinkInfo.cmake` and the calls to the `CMAKE_PARSE_IMPLICIT_LINK_INFO` function.

**Comment by mathstuf** [comment]
So CMake does the following in order to extract the information:

  - create a CMake project which creates an executable using the verbose flag for the compiler;
  - when building that project, scan the output for the link line (using a regex);
  - parse out the command line output to find directories added as `-L`, `[-/]LIBPATH`, `-Y` (Solaris?).

What's the best way to have Spack do this? Do we want to compile a simple `int main(int, char**) { return 0; }` executable to prod the compiler into dumping out this info and then parse it out too?

**Comment by mathstuf** [comment]
For those interested, there is now #7153.
