### ISSUE TITLE
Set up a public source mirror

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#7121]
Spack currently has support for binary packaging, but we don't have a public mirror for source or binaries.  Implement a public mirror and keep it current with sources (binaries are handled in #7116).

- [x] stand up an S3 instance that Spack can use to house sources and binaries for builds
- [ ] In Spack's default settings (`etc/spack/defaults`), set this S3 instance as a fallback if package sites go down 
- [ ] New source tarballs to Spack's mirror *after* they are merged to `develop`
    * require merge before add so that not just any PR adds to the mirror

**Comment by mathstuf** [comment]
It might be better to have Spack *prefer* this location rather than falling back to it.

  - Upstreams might prefer having Spack pull its sources from its own bandwidth rather than "spreading the love";
  - Restricted sites can whitelist a single external location for downloads and not have network errors trigger its use.

**Comment by mathstuf** [comment]
This could be done as a buildbot builder which only runs on integration branch updates. We'd need some way to download all sources referenced in all packages. Files would be stored locally (acting as a local cache to not redo work) and then could be `rsync`'d to the final destination on S3 or wherever. It'd be best if the buildbot master held the keys rather than the builder and it did something like the solution on [this SO question](https://serverfault.com/questions/384467/copying-huge-files-between-two-remote-machines-efficiently#384481).

**Comment by mathstuf** [comment]
Cc: @opadron

**Comment by bryonbean** [comment]
@opadron and I met, discussed this issue/ticket and determined the following:

- Omar: He is going to speak with Aashish to determine what role(s) should be set on IAM credentials for me that I'll use to the mirrors with S3. Waiting on this to get started.
- Bryon: Start to investigate the Gitlab integration services that will facilitate mirror uploading 
- Use the next meeting with @tgamblin to further flesh out remaining questions.

**Comment by bryonbean** [comment]
Created WIP PR #8664

**Comment by becker33** [comment]
Moving this to v0.15.1 so that we can monitor it in develop before adding it to a release.
