### ISSUE TITLE
Using Spack in containerized environments cleanup examples

### ISSUE THREAD

**Issue by prckent** [spack/spack#7186]
This is a documentation feature request: To facilitate optimal use in containerized environments, it would be helpful to have an example of using spack with (say) a docker ubuntu image, including recommendations of how to maximally clean up after package installs to minimize space usage. This is implicit in the current documentation, but a specific section with examples would establish best practices.

**Comment by Sinan81** [comment]
I would be interested to work on this although my experience with spack & python is limited. @prckent Can you point to the relevant parts of the documentation so that i can take a look at it. I have a rough idea about what to do but also I am wondering if you have any suggestions as to how to proceed with it.

**Comment by prckent** [comment]
Unfortunately I am not a spack person, hence my request. Hopefully someone else can chime in.

**Comment by alalazo** [comment]
@becker33 I think this can be closed, since we have `spack containerize` that by default:
1. Uses multi-stage builds
2. Calls `spack gc` in the build stage
3. Strips the binary files

And we have documentation [here](https://spack.readthedocs.io/en/latest/containers.html)

**Comment by prckent** [comment]
Indeed this has been addressed by the containerize functionality. Thanks.
