### ISSUE TITLE
How to load more than 1 package with one command

### ISSUE THREAD

**Issue by adamryczkowski** [spack/spack#7289]
I want to achieve something like `spack load *%gcc@7.3.0`. 

I understand, that this particular syntax wouldn't work since asterisks are interpreted by the shell. 

I tried to do something like `spack find | grep 'gcc@7.3.0' | xargs spack load {}`, but I couldn't make `spack find` output a simple plain list. 

In theory I could do the same with the `modules` shell command that `spack bootstrap` have installed during the bootstrap, but the piping of the `modules` is surprisingly complex. I went so far to get 

``` 
(module -t avail)2>&1 | grep 'gcc-7.3.0-' | xargs module load {}
```
but the `xargs` doesn't see the `module` command. Do you have any ideas?

**Comment by citibeth** [comment]
See work and discussion on Spack Environments.
Also, `spack module loads` generates a series of `module load` commands that are compatible with each other.

**Comment by alalazo** [comment]
Did you try using the `module save` feature from `lmod`? You could load manually all the modules you want in your environment once, and then give that set a mnemonic name:
```console
$ module save gcc-7.3.0-environment
```
Next time you need that set of modules you just need to:
```console
$ module restore gcc-7.3.0-environment
```

**Comment by citibeth** [comment]
On Fri, Apr 20, 2018 at 5:16 AM, Massimiliano Culpo <
notifications@github.com> wrote:

> Did you try using the module save feature from lmod?
>

No, because:

1. Our supercomputer uses *environment-modules*, a decision not in my
control.
2. I have been quite happy with *environment-modules*, and have failed to
see any advantage of *lmod* (for my purposes).  I do know that *lmod* is
harder to build, although that might have been solved by Spack.
3. The procedure given above is dependent on your global environment, i.e.
what other modules you might happen to have loaded.  Properly genertating a
module for a Spack environment, without extra stuff creeping in, would be
fiddly.

**Comment by alalazo** [comment]
Apologies for the confusion @citibeth. My comment above was supposed to be an advice to @adamryczkowski and show him how to load in a single command all the modules he cares about. Since he uses `spack load` he's in control of whether installing or not `lmod`. Didn't want to convince you to use a tool you don't want to use.

**Comment by alalazo** [comment]
@adamryczkowski I am going to close this issue. Doing things like:
```console
spack load %gcc@7.3.0
```
might be highly unsafe - what if you installed `mpich%gcc@7.3.0` and `openmpi%gcc@7.3.0`? As environments will be *added soon* :tm: I think that would be the better way to go for this kind or requests.
