### ISSUE TITLE
Spack’s fish shell support 

### ISSUE THREAD

**Issue by armarkos** [spack/spack#7311]
Hello,

Do you have fish version of setup-env.sh/setup-env.csh? 
It will be extremely convenient to have it.

**Comment by adamjstewart** [comment]
We don't currently but PRs are always welcome! I don't know much about fish. Is it closer to sh or to csh? Would it be possible to modify one of these files to be more generic so that it works for both? #4048 is an attempt to make the sh version more generic so it will work for shells other than bash and zsh, so that may be a good starting place.

**Comment by adamjstewart** [comment]
Looks like I answered my own question:

> fish is considered an "exotic shell", in that its syntax derives from neither the Bourne shell (ksh, bash, zsh) nor the C shell (csh, tcsh).

https://en.wikipedia.org/wiki/Friendly_interactive_shell

so we would likely need a new file entirely.

**Comment by JBlaschke** [comment]
I've just now created a pull request #9279 adding this feature. I can write some unit tests later (if someone provides me with test cases, as I am relatively new to spack).

**Comment by JBlaschke** [comment]
Advertising this here also, in case someone's following this issue. I've found some time to make progress on #9279 and would appreciate feedback. Thanks.
