### ISSUE TITLE
Proposal: Add upgrade-in-place functionality

### ISSUE THREAD

**Issue by becker33** [spack/spack#7409]
We've received some requests for an upgrade-in-place capability in Spack.

My current thoughts on the policy side:

- We want to maintain the unique mapping from specs to prefixes
- We want to be able to deprecate software with security flaws without breaking packages that depend on it.

On the technical side, to accomplish the above:

- We cannot install a new spec over the existing install
- We can remove the old installation and create a symbolic link from the old installation to a new one.
-  We can note in the install database that the old installation was deprecated and symlink'ed into the new installation.
- Once the new compiler is implemented, we can prevent the concretizer from concretizing against the old spec.

Proposal:

I will create a `spack upgrade` or `spack deprecate` command that takes two specs, the spec to deprecate and the spec to replace it with. It will implement the removal of the old binaries and the creation of the symlink from the old prefix to the new. This will also make the database changes necessary, but will not implement the changes to the concretizer as the current concretizer implementation cannot handle that logic.

Comments on either policy or technical specs are welcome. I will leave this up at least a few days before beginning implementation to give people an opportunity to comment.

**Comment by adamjstewart** [comment]
Let me tell you a story about why I hate Homebrew. Last semester I was taking a course that required me to install OCaml. They distributed binaries that only worked with the latest version of OCaml, so I installed it with Homebrew. However, halfway through the semester, a newer version of OCaml was released. I accidentally upgraded Homebrew, and spent an entire day figuring out how to downgrade the OCaml package. I searched the interwebs for suggestions, and found all kinds of deprecated commands to do what I want, but none of them worked. I found the Git commit that added the new version and reverted it, but when I ran `brew install ocaml` Homebrew decided to update itself before installing the latest version of OCaml. I eventually had to manually hack the file to prevent Homebrew from updating itself. I can't believe Homebrew doesn't allow you to choose which version of a package you install. What a poor design.

I tell you this story partly as a cautionary tale on how to implement `spack upgrade` but also because I'm fed up with Homebrew. I would LOVE to be able to use Spack for everything that Homebrew used to give me. The only problem is that Spack is currently far too complicated. I see `spack upgrade` as a step in the right direction. I think if we want Spack to become a Homebrew killer it needs some basic functionality:

1. A `spack upgrade` or `spack update` command that would install the latest version of everything I already have installed (with no arguments) or the latest version of the package I request (with a package name as an argument). This should work just like Homebrew or Anaconda does.
2. A way to symlink all installation directories to `/usr/local/`. I know we have `spack view`, and I haven't played around with it, but I think that command requires you to run it after every single installation.

Basically, here's the setup I'm imagining. We would have a section of the docs that suggests two "modes" of running Spack: cluster mode and user mode. Cluster mode works the way Spack currently does. User mode would work just like Homebrew or Anaconda. All installations would still take place within the Spack hierarchy. The only difference would be a `mode` setting in `config.yaml` that tells Spack to operate in `user` mode, and a `symlink` setting that defaults to `/usr/local/` where everything is automatically symlinked to.

Here's an example of what I want to do. Let's say I want to install `ocaml`. As a new Spack user, I would clone Spack, add those two lines to `config.yaml` to tell Spack how I want it to work, and run `spack install ocaml`. This would install the OCaml package and symlink it into `/usr/local` automatically. Later, a newer version comes out. I run `spack install ocaml` and nothing happens because OCaml is already installed (this work would come with the new concretizer). If I actually wanted a newer version, I would have to run `spack upgrade ocaml` or `spack install ocaml@<version>`. This would install the new version and change the symlink in `/usr/local/` to point to this new version, but it wouldn't uninstall the old version. We would also want an option for `spack clean` to uninstall out-of-date packages that have been replaced by newer installations.

If you have any questions on how this functionality should work, the answer will almost always be "just like Homebrew or Conda does". They are both very user friendly and do exactly what you want (assuming you aren't trying to manage an entire cluster). 

I seriously think Spack could become a Homebrew killer with the addition of this basic functionality. Spack can already do things no other package manager can do, and yet it can't do the simplest of things that most users want.

**Comment by healther** [comment]
I like the idea of being able to replace homebrew with spack. And I suspect most of what you want regarding the symlinking into `/usr/local` is already in `spack view`, albeit I'm not sure what would happen if you do a `spack view add /usr/local <myawesomepackage>`. 

But basically what `spack view` is doing is symlinking everything below `/package/prefix/` to the target folder. The addition of these paths to the environment is "left as an easy exercise for the user":tm:. The main limitations currently are:
 - everything that is done in `setup_environment`-kind of functions is simply lost. 
 - what happens with files that exist in multiple prefixes (typically some manpages and some python scripts, that so far are semantically identical)

I suspect what we really would want is to be able to define (in a user-friendly and understandable manner) (1) "I want the following packages to be in my current environment" (and also (2) "now I don't want THIS package anymore"), (3) "I want to activate THAT environment" and (4) "I want that environment to be updated".

Up to a point we have (1) with views (I'm not sure how spack environments are doing), in theory there is also (2) implemented in `spack view`, but in practice we always make new views, so I wouldn't want to vouch for that ;). (3) would need to either symlink the view into something like `/usr/local` or add all:tm: appropriate paths to the environment AND also replicate the sum of all `setup_environment`-kind of functions for packages that are part of the environment. (4) would basically only need to differentiate between what the user explicitly asked for in (1) and what spack added to accommodate the request and rerun (1).


I'm much less certain regarding in-place-upgrading. So far the main design philosophy of spack has been: I do this series of command on any of my systems I'm working on and I can be reasonably certain I get the same software out. From a personal point of view I'm not certain whether this is necessarily the correct approach, but when you do symlinking of some versions into other versions than you essentially break spack's promise of "a hash is a hash, including all dependencies". Maybe we should be smarter in what we consider a unique version of a piece of software. But at the end of the day the main point of using hashes in the first place is that you can't necessarily trust software developers that they don't change implementations in bugfixes.
Though maybe I'm just not getting the use case of doing the in-place update rather than a rebuild
