### ISSUE TITLE
openfoam-com finds wrong flex

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7439]
Installing openfoam-com with Spack fails if an old flex version is in the system path:
```
error: declaration is incompatible with "void yySTLFlexLexer::switch_streams(std::istream *, std::ostream *)" (declared at line 129 of "/usr/include/FlexLexer.h")
```
However, spack reports that the installation completed successfully. That's not the case.

I am not familiar with the build system of OpenFOAM. @olesenm is there a possibility to make the build system finding the Spack version of Flex?

**Comment by olesenm** [comment]
This isn't something that I'd worried about before, but I can see where it would be an issue, especially since some systems are likely to have an old flex etc. Could you please add as an issue under develop.openfoam.com? This would be easier for me to track there.
For completeness, I should also mention that the OpenFOAM will currently not deal well (ie no provision) with libz that is not from the system.

**Comment by michaelkuhn** [comment]
Can you please check whether #10956 fixes the problem for you?
