### ISSUE TITLE
Use short hashes for patches

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#7694]
When you run `spack spec` on a package with patches, it displays full length patch hashes.

### Before
```console
$ spack spec gcc
...
gcc@8.2.0%clang@9.0.0-apple~binutils languages=c,c++,fortran patches=ecc5ac43951b34cbc5db15f585b4e704c42e2e487f9ed4c24fadef3f3857930b ~piclibs~strip arch=darwin-highsierra-x86_64 
    ^gmp@6.1.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
        ^autoconf@2.69%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^m4@1.4.18%clang@9.0.0-apple patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=darwin-highsierra-x86_64 
...
```
These patch hashes aren't particularly useful, as you can't specify which patches to use on the command line anyway. I propose the following changes.

### After

By default, no hashes are shown:
```console
$ spack spec gcc
...
gcc@8.2.0%clang@9.0.0-apple~binutils languages=c,c++,fortran ~piclibs~strip arch=darwin-highsierra-x86_64 
    ^gmp@6.1.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
        ^autoconf@2.69%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^m4@1.4.18%clang@9.0.0-apple +sigsegv arch=darwin-highsierra-x86_64 
...
```
When `--long` is supplied, short hash prefixes are displayed:
```console
$ spack spec --long gcc
...
mbr7sk2  gcc@8.2.0%clang@9.0.0-apple~binutils languages=c,c++,fortran patches=ecc5ac4 ~piclibs~strip arch=darwin-highsierra-x86_64 
vvoefua      ^gmp@6.1.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
74niupl          ^autoconf@2.69%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
c5q6jjk              ^m4@1.4.18%clang@9.0.0-apple patches=3877ab5,c0a408f +sigsegv arch=darwin-highsierra-x86_64 
```
When `--very-long` is chosen, the full hashes are shown:
```console
$ spack spec --very-long gcc
...
mbr7sk2tsbqktrjnuq75kdi6vq7obegy  gcc@8.2.0%clang@9.0.0-apple~binutils languages=c,c++,fortran patches=ecc5ac43951b34cbc5db15f585b4e704c42e2e487f9ed4c24fadef3f3857930b ~piclibs~strip arch=darwin-highsierra-x86_64 
vvoefuai3hzh7eughdxbihgqsnpvizsn      ^gmp@6.1.2%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
74niuplengavsakhoomvp3lzw7epwosc          ^autoconf@2.69%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
c5q6jjkr7uwa3si5rh7y56uf4jvzwg7r              ^m4@1.4.18%clang@9.0.0-apple patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=darwin-highsierra-x86_64 
...
```
EDIT: edited to provide clarity as to what I'm looking for

@scottwittenburg

**Comment by tgamblin** [comment]
@adamjstewart: I like it, but this fix would be a bit involved at the moment.  You want to look at `Spec.tree()` and `Spec.format()` in `spec.py`.  I think the solution would be to add some some more long options to `format()`.

Honestly, we should just switch to *only* having long options for `format()`, as the short options are pretty much illegible.  And we should simplify the long options to look more like python format strings (or to just use python format strings).

Anyway, the tricky (but nice) part is that patches are just multi-valued variants that appear on the spec if the package is patched.  This accomplishes what we want (adding a patch changes the spec hash), but it also means that they're not really treated specially compared to other specs.  We already have a `${HASH:len}` format that shortens spec hashes; making a similar option for shortening variants that are "shortenable" seems like it would make sense.

The `Variant` classes in `variant.py` would also nee to grow.  Currently we print them by just calling `str()` on them.  They need some type of `format()` function that can take more options than `__str__`, and the new format string would use that instead of `str()` like we do now.

Does that seem doable to you?  I don't know when I might have time to implement this.

**Comment by adamjstewart** [comment]
I think I took a stab at this one time and discovered just how difficult it was. If I'm ever really bored I might try again, but if not I don't mind waiting. This is a pretty minor annoyance.

**Comment by haampie** [comment]
I think we can just close this for now as #29015 is merged, unless @adamjstewart wants more control over the length of patch hashes, then feel free to reopen
