### ISSUE TITLE
Better Out-of-the-box CMake Support

### ISSUE THREAD

**Issue by AndrewGaspar** [spack/spack#7904]
This is a bit of a vague feature request, but hoping it may at least start some good discussion.

My typical CMake workflow in a project is to have multiple build directories with different compilers, build types, configurations, etc. I might move between them depending on what I'm testing. Each of these directories may want to depend on a different version of a spackage. e.g. The intel build directory should depend on a matching intel compiled version of the spackage, similarly with gcc, clang, etc.

You can do this today by using a combination of `spack load` and `find_package` when configuring each compiler. However, it requires the user to have already installed the package and know how to correctly load it. The process of registering compilers, crafting the correct spack spec, and going through the process of installing dependencies is kind of complex for people not familiar with spack, and creates a bit of a learning curve for people new to a project that prefers to fill its dependencies from spack.

It would be convenient if there was a CMake module for Spack that made adding dependencies from Spack very easy. I'm imagining something like this in a CMakeLists.txt:

```cmake
find_package(Spack REQUIRED)

find_spackage(Kokkos +cuda REQUIRED)

include_directories(${Kokkos_SPACK_INCLUDE_DIR})
link_directories(${Kokkos_SPACK_LINK_DIR})
```

`find_spackage` would, during CMake configuration, produce a compiler spec from the currently loaded `CMAKE_C_COMPILER`, `CMAKE_CXX_COMPILER`, etc., if one does not already exist, install Kokkos according to the spec (including any options specified in find_spackage) if it is not already installed, produce some variables like `${<package_name>_SPACK_INCLUDE_DIR}`, and save those variables to the CMake cache.

This would make it much easier for people building the project for the first time - the only dependency they're required to install independently is spack. Once they've done that, their CMake configuration will take care of the rest of the work, and they don't have to understand spack too intimately. More-so, it makes adding new dependencies to a CMake project almost completely painless, kind of like [Cargo](https://crates.io/) or [npm](https://www.npmjs.com/).

Any thoughts?

**Comment by pramodk** [comment]
For the first part of your question:  have you tried spack setup?

**Comment by jrood-nrel** [comment]
Sorry I'm probably not understanding this, but in my opinion this looks complicated, or at least it's confusing me. The main thing I see, is it would be trying to automate Spack within the project's CMake code to fulfill dependencies so the user doesn't have to use Spack themselves. To use dependencies from Spack in CMake, assuming they work well with `find_package`, I have been using `spack location -i`, or all my modules are set with a `package_ROOT_DIR` variable I can reference as well, because all I feel like I need is the location of things during the CMake configure. Interesting idea though if I could better understand the advantage, but I use Spack a lot so maybe I expect to use it myself.

**Comment by AndrewGaspar** [comment]
> For the first part of your question: have you tried spack setup?

```
$ spack setup hdf5@1.10.1
==> Error: Support for AutotoolsPackage derived packages not yet implemented
 $ spack setup kokkos@2.5.00
==> Error: Support for Package derived packages not yet implemented
```

I'm not completely clear what the expected behavior is, though.

**Comment by citibeth** [comment]
@jrood-nrel The advantage of Spack Setup is that it does what you want in a fast, convenient and reliable way.  And after you've run Spack once, you don't have to run Spack again to build or install your projects.

Spack Setup creates a bunch of `xyz-config.py` files; which are basically scripts that call CMake, pointing CMake to the correct version of Spack. You get one `xyz-config.py` file for each CMake-based package you want to manually build.  Once your project's dependencies have been installed and your `xyz-config.py` files have been generated, the user never has to run Spack.  You only have to re-run Spack if your set of dependencies changes.  (I didn't run Spack for over a year for this reason).


The current incarnation of Spack Setup is in Beta testing, I'd be happy to help you out with it: https://github.com/spack/spack/pull/7846

`spack location -i` is non-deterministic, and could cause "surprises" if you're trying to find dependencies with it.

PS: @AndrewGaspar `spack setup` worked at the time it was merged, but was later broken.  It is now being resurrected and updated.  If you merge from #7846 your can then do:
```
$spack install --setup hdf5 hdf5@1.10.1
```
This will do two things: (1) install dependencies for `hdf5`, and (2) generate a file called `hdf5-config.py`.  You then use `hdf5-config.py` as follows:
```
$ git clone hdf5... (or whatever)
$ cd hdf5
$ mkdir build
$ cd build
$ .../hdf5-config.py   # Runs CMake
$ make
$ make install
```
Once you say `make install`, your version of `hdf5` is now installed, as if Spack had just done it the regular way.

@AndrewGaspar Spack Setup only works for CMake-based packages, because those are the only kind of develop.  It could be made to work for Autotools, but nobody has done that yet.

If you find any problems with Spack Setup, please post to #7846

**Comment by citibeth** [comment]
It's an interesting idea.  A few thoughts:

1. It would have to run with respect to a particular Spack Environment, which would likely specify versions and variants for some of the packages involved.  Just asking Spack for a package without those annotations is often not enough.

2. The `CMakeLists.txt` file you generate now requires Spack.  How would people build this software with other auto-builders?

3. Supposing another project B uses your project?  How would you write the build and Spack package for B?

**Comment by AndrewGaspar** [comment]
@jrood-nrel 
> assuming they work well with `find_package`

Actually this is a big pain point in-and-of-itself: a lot of packages haven't encoded this information into core CMake, so you have to either write your own FindFoo script or find an existing one online. Spack already knows how to load components, including the headers and libs, so it would be great if CMake could tap into that existing knowledge base.

As for using `spack location -i`, I think my workflow is typically the same, though by way of loading the module via `spack load` and then configuring. And this is really easy and obvious to me. But then I tried to walk somebody else through getting the dependencies for the project installed, and it was kind of a painful process.

I had to tell them:
1. Install HDF5 using `spack install hdf5 +fortran`
"Oh, I'm getting error messages about hdf5.mod not being compatible with my compiler"
2. Oh yeah, you need to make sure you install HDF5 with a compiler version matching your CMake build compiler. Load the compiler you plan on using and run `spack compiler find`. Take a note of your compiler spec and then run `spack install hdf5 %<compiler-spec>`
3. Ok, now before you configure CMake, make sure you load the correct hdf5 installation `spack load hdf5 %<compiler-spec>`

By that point they were ready to go back to tarballs and building it in tree. The goal of this proposal would be to hide some of these complexities from the user - they can move between compilers and everything should just work, without the user having to understand the intricacies of managing multiple builds of their dependencies.

**Comment by AndrewGaspar** [comment]
@citibeth 

> It would have to run with respect to a particular Spack Environment
Excuse my ignorance, but what's a "Spack Environment"? Is this a new feature?

> The CMakeLists.txt file you generate now requires Spack. How would people build this software with other auto-builders?
I'm not sure I quit understand. Do you mean if you want to fill the dependency through some other way than Spack? I think a more robust CMake file would have something like:

```cmake
find_package(Foo)
if (NOT FOO_FOUND)
    // Foo was not available, falling back to Spack
    find_spackage(Foo REQUIRED)
endif()
```

But for cases where you're OK depending on Spack, you could just go directly to Spack.

> Supposing another project B uses your project? How would you write the build and Spack package for B?

I think if you were planning on putting your project into Spack, you would have to make the use of this hypothetical Spack CMAKE package optional. Then you would fill your dependencies in the "usual" method, like above, and fill out your spack spec with your formal dependencies. Then project B could safely rely on your project like any other spackage.

**Comment by drbenmorgan** [comment]
I'm always wary of functionality like this as it implies, as @citibeth noted, a coupling of the low level build system (CMake here, but could be a Makefile) for a project to the higher level package manager (Spack here, but could be yum/apt). That can make it harder for clients of the project as they may not use the package manager, which is now a dependency of the project. If that dependency can be made optional, this is better, though having package manager dependent calls in build scripts still "smells" a bit to me. 

See also [much the same discussion for the Conan package manager](https://github.com/conan-io/conan/issues/2463), particularly [this comment](https://github.com/conan-io/conan/issues/2463#issuecomment-365382554).

**Comment by citibeth** [comment]
> > It would have to run with respect to a particular Spack Environment
> Excuse my ignorance, but what's a "Spack Environment"? Is this a new feature?

Yes, see #7843.  Basically... in constructing a software stack I've found it is essential to keep a `packages.yaml` file for that stack that lists the variants and versions of packages needed for that stack.  The goal is to allow for "clean" install commands; i.e. one should never have to put variants or `^` modifiers on the command line if `packages.yaml` is set up correctly for a project.  I was saying that in the case of CMake, you probably want something similar, especially for the version numbers.  You can't have  `CMakeLists.txt` specifying the versions of its dependencies because from the local perspective of CMake on a single project (as opposed to the whole DAG), you just don't have the required information to know that stuff.

> But for cases where you're OK depending on Spack, you could just go directly to Spack.

AFAIK, the suggestion in this thread would save only one thing: having to write the dependencies in the Spack package and the CMake file twice, and having to write a bunch of pointless `find_xyz` functions in CMake.  If you KNOW that your software will be built with Spack, then you should not HAVE to hand-build a CMake file that is either redundant or disabled with the Spack package.

So... the idea would be to have Spack provide information direclty to the CMake build in CMake format.  I think this would be quite feasiable, especially in the context of a Spack Environment:

1. New Spack package type, `CMakeSpackage`.  When used with Spack Setup, this would generate a CMake-format file to be imported directly into CMake.

2. You write your Spackage-format CMake build to include the Spack-generated `.cmake` file.  It would be found based on the location of the Spack Environment, given eitner on the command line or in an env var.

**Comment by AndrewGaspar** [comment]
After investigating `spack install --setup`, I think it resolves the use case I filed this for.

**Comment by dzhang-b** [comment]
`spack setup` command is broken for even cmake project now.
