### ISSUE TITLE
Virtual Dependency Meta-Issue

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7970]
The purpose of this Issue is to collect together previous issues that relate to virtual dependencies, with brief annotations as to the nature of the relationship.

#4595 (open)
> Limitations introduced:
> build-only dependencies cannot have virtual dependencies
Many packages have `python` as a build dependency.  This fact, combined with Python as a virtual dep (#7966), combined with #4595, could break a lot of Python things.  Even now, the concretizer is not able to handle DAGs where `python@2` is a build dependency and `python@3` is part of the DAG somewhere else.  #2548 (of which #4595 is a sequal) would fix that, apparently.

#7950 (Virtual Deps: packages.yaml versions not respected)

#7901 (Ghost blas provider reported by spack)

#6300 (Variants on Virtual Packages: mpi+cuda)
#1712 (variants in virtual packages are not passed to providers)

#3515 (On the interaction between DB and repositories)
@alalazo said: "For the record I think we should really... Change the mechanism used to detect if a spec is virtual or not"

Python as a virtual dependency python virtual-dependencies
#7966 opened 5 hours ago by mkuron 

Change default elf provider on macOS  defaults macOS virtual-dependencies
#7939 opened 4 days ago by adamjstewart • Approved

Set default provider for every virtual package  defaults tests virtual-dependencies
#7784 opened 15 days ago by adamjstewart • Approved  

Make libelf the default elf provider again.  WIP bug concretization virtual-dependencies
#3737 opened on Apr 6, 2017 by tgamblin • Approved  

Bug with spack find/uninstall and virtual deps bug concretization specs virtual-dependencies
#2015 opened on Oct 13, 2016 by adamjstewart

**Comment by dev-zero** [comment]
Maybe as an input from the experience the Gentoo meta-distribution made:

Initially they chose the same way as Spack to exhibit virtual packages: allowing inside a package spec to specify for which virtual the package provides an implementation. Unfortunately it was found to be not flexible enough, mostly due to tracking USE flags (very similar to `variants` in Spack) through virtuals. The system was eventually changed to use dummy packages as virtuals instead. See for example: https://gitweb.gentoo.org/repo/gentoo.git/tree/virtual/blas/blas-3.7.ebuild
The `OR` dependency is likely not something Spack should support, but one could think of using variants on the virtual dummy packages to select the respective implementation instead.

**Comment by citibeth** [comment]
I agree, virtual dependencies seem to be the source of unending small
headaches.

>

**Comment by dev-zero** [comment]
Thinking a bit more about it, I'm wondering what would actually break if the current virtual dependencies would be replaced by real packages, assuming that the virtuals would have an explicit `provider` variant used to select the provider to be used.

The "TODO" list I came up with so far is:

* the virtual packages have to forward requests for `libs`, `prefix` properties to the currently resolved implementation/provider
* forwarding of variants to providers have to be done manually and explicitly (but given the spectrum of providers I'd consider this a good thing)
* adding a new provider also requires touching the virtual package (no problem for builtin packages, a bit more difficult for site/local packages - could be facilitated by allowing to inherit from the builtin package class)
* current `[providers]` configuration should be mapped to a variant on the respective virtual package (ex. `blas` would have a variant `provider=<openblas,mkl,libsci,...>`, the list of `providers` in the `package.yaml` would limit the providers the resolver (concretizer?) could choose from)
* reverse dependency checking: I assume that currently the provider is recorded instead of the virtual dependency

**Comment by citibeth** [comment]
The best way to move these ideas forward is to put them on the agenda for
the Spack Telcon, and discuss them there.  Doing anything will require
buy-in from @tgamblin.

**Comment by dev-zero** [comment]
@alalazo care to elaborate? FYI Spack is in many ways very similar to the Gentoo Linux Metadistribution (look for the Gentoo Prefix Project)), and experience there has shown that the implicit kind of virtuals are difficult to implement and have subsequently been removed again

**Comment by adamjstewart** [comment]
Closing this issue as it is essentially equivalent to:
https://github.com/spack/spack/issues?q=is%3Aissue+is%3Aopen+label%3Avirtual-dependencies
