### ISSUE TITLE
==> Error: name 'Buildsystem' is not defined

### ISSUE THREAD

**Issue by ax3l** [spack/spack#8248]
Since about the weekend my spack install seems to be broken. Probably something with the init, maybe caused by #7774?

Even cloning the repo from scratch and removing my local configs keeps the error.

### Expected Result

Usage as before

### Actual Result

Build system (parent class) of packages is not found.

### Steps to reproduce the issue

```bash
$ spack install hdf5
==> Error: name 'AutotoolsPackage' is not defined
$ spack install py-pybind11 ^python@3
==> Error: Invalid Version range: 3.4:3
$ spack install cuda
==> Error: name 'Package' is not defined
```

### Information on your system

Spack `develop`: 3712ac1f663a0c06765daced44f6a4e2f986c9f4

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

$ uname -a
Linux ax3l 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```

**Comment by alalazo** [comment]
The only error I can reproduce is:
```console
$ spack install py-pybind11 ^python@3
==> Error: Invalid Version range: 3.4:3
```
If I remember well, this is a known issue with versions (can't find it right now, maybe @adamjstewart remembers which issue it is), where `@3` doesn't mean `@3.X` for some `X`, but is interpreted as literally version 3. The misleading error message refers to a constraint in `py-pytest` on the python version which requires `python@3.4:`.

**Comment by ax3l** [comment]
Interesting. How did I mess up my environment?
Did I miss something by (re)moving `$HOME/.spack` and cloning spack fresh again?

**Comment by adamjstewart** [comment]
@ax3l I believe this was caused by #8090, not #7774. See https://github.com/spack/spack/pull/8090#issuecomment-390373010 for my initial bug report and https://github.com/spack/spack/pull/8090#issuecomment-390415253 for the fix.

I believe this bug only affects Python 3 users, but correct me if you're using Python 2. The problem is that Python creates `.pyc` caches after importing files and doesn't update them unless the file itself changed. Since `__init__.py` changed and not the packages, it still tries to import from `spack` and can't find the base classes it needs.

We're talking about adding a `spack clean` flag to clean this up.

**Comment by ax3l** [comment]
Yep, I am a python 3 user :)
