### ISSUE TITLE
Secure domain names/certificates/keys

### ISSUE THREAD

**Issue by opadron** [spack/spack#8626]
From #8362:

> While we do have deployed infrastructure, we still need a few items to deploy production-ready infrastructure. At the very least, we will need a domain name for the gitlab instance, a domain name for the cdash instance, certificates for the two, and while we're at it, it would be a good opportunity to secure gpg keys for package signing. ...

This issue will track our progress towards securing the following assets:

- [x] Domain name for Spack's gitlab instance (gitlab.spack.io?)
- [x] Domain name for Spack's cdash instance (cdash.spack.io?)
- [x] Web certificate for Spack's gitlab instance.
- [x] Web certificate for Spack's cdash instance.
- [ ] GPG Keys for package signing. (not necessary right now, but might want to have it ready for when we need it)

**Comment by tgamblin** [comment]
@opadron: The first 4 of these are pretty much done (see below). Can you make a separate issue for the GPG item and assign that one to me?

I like the domain names you picked, so let's go with those.

Ok, here's a summary of what I did:

1. I switched [spack.io](https://spack.io) to use [LetsEncrypt](https://letsencrypt.org/) certs. You get free wildcards with this, so we can use `gitlab.spack.io`, `cdash.spack.io`, etc.
2. I sent you an email with a link to where the keys/certs/creds are for all of this.  That contains details on how I set up LetsEncrypt and `certbot`.  We should get the non-private part of that up here in the Spack organization eventually, but for now, we'll manage it outside the org.
3. I containerized the `spack.io` site (it's not very big).  The repo is at [spack/spack.io](https://github.com/spack/spack.io).
4. I set up Travis on the `spack.io` repository to upload the built image to [Docker Hub](https://hub.docker.com/r/spack/spack.io/) as `spack/spack.io` every time a build is successful.

I think all that is left for you is:
- [ ] Get the `spack.io` site hosted (using the container above) in EKS.  That should be pretty simple -- it's just `nginx` running on port 80, hosting static content.  
- [ ] I'm assuming you'll set up your own secure `nginx` proxy in front of that so that you can manage all the services at `spack.io`.  Once you have that set up with SSL (see LetsEncrypt stuff above), let me know, and I can point the `spack.io` domain to your IP and shut down the current VM.

From there, you should be able to set up the other services, and we can worry about moving the actual `route53` DNS service later.

Sound good?

**Comment by opadron** [comment]
Sounds good to me!  Here's some updates on my end:

 - I have confirmed that Gitlab CI/CD for github is, in fact, a premium-only feature. (https://about.gitlab.com/features/github/)

 - It had occurred to me that upon merge to develop, we would want to build up-to-date versions of our docker images, and only *then* run the package-building pipelines, so that we can use the same version of spack when building packages.

 - One alternative that I've been liking the more I think of it would be to just create special-purpose versions of each docker image that delay the clone and install of spack until runtime.  We should be able to run such images on k8 with minimal changes and they would clone and install whatever is the latest on develop.  If we go this route, we could keep the official image builds on travis, making that part of the process much simpler.

 - Speaking of which, I like what you did for spack.io, and I'd like to replicate that for the official spack image builds.  However, we'll need sudo, and docker services (like you have it on spack.io), and you would probably need to setup the secrets on your end.  One alternative here would be to move the docker work to a dedicated repo with its own `.travis.yml`.  Doing this would simplify the setup, but we'd probably want to add something in the `.travis.yml` of spack proper so that the docker builds are triggered on merge to `develop`.

This was a bit of a brain dump, so let me know if I could clarify anything.

**Comment by tgamblin** [comment]
> One alternative that I've been liking the more I think of it would be to just create special-purpose versions of each docker image that delay the clone and install of spack until runtime. We should be able to run such images on k8 with minimal changes and they would clone and install whatever is the latest on develop. If we go this route, we could keep the official image builds on travis, making that part of the process much simpler.

@opadron: I like this alternative -- I think it's the right thing to do, and GitLab CI should check out the latest version of Spack as part of starting the runner for the PR, right?  So in that case we would only need to make images based on the reference version of each OS, with the right compilers installed.  We could build, e.g., centos7-clang, centos7-gcc, ubuntu-clang, and ubuntu-gcc to start with.  Or, alternately, we could just have Gitlab CI install the right compilers (like we do with travis in the main Spack CI).  That may make changes easier. since you have to specify the container when you start the running, but you can change the `apt` or `yum` commands on GitHub.  Also if you install the compilers in GitLab CI, you can make the runners use reference OS images from docker hub, so we don't need to host anything.

**Comment by opadron** [comment]
Yup, that's pretty much exactly what I was thinking.  Glad we're on the same page!

**Comment by tgamblin** [comment]
Looks like this can be done as soon as #8789 is done.

**Comment by opadron** [comment]
Closing since #8789 is all done, and no other tasks remain on this issue.
