### ISSUE TITLE
How to use the package installed with spack

### ISSUE THREAD

**Issue by zet809** [spack/spack#8641]
Sorry, no where to register to spackpm.slack.com. So, have to ask question here.
Will you pls check the steps to access the slack channel above? Not work for me at all.

My question is:

```
# spack find python
==> 1 installed packages.
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
python@2.7.15
[root@c910f04x28v04 ~]# python -V
Python 2.7.5                               
```
I have installed python 2.7.15 in my system, how can I use it? No document I can find that mention the using the installed packages. Thx for your time!

**Comment by davydden** [comment]
> no where to register to spackpm.slack.com

see `Sign up here to get an invitation mailed to you.` on Github homepage https://github.com/spack/spack

**Comment by healther** [comment]
you need to load your package into your environment. There are a couple of ways to do that but the most straightforward way is:
```
spack load -r python
```

The problem here is that `spack load` happily selects all installed specs that match the partial spec it is given. I.e. in your example if you would have multiple python installations it would load all of them and wouldn't even guarantee you an order. So it is important to give `spack load` a sufficiently unique spec.

The `-r` is needed such that `python` will be able to find its dependencies (see eg #8639 for details)

**Comment by zet809** [comment]
Thx, @healther , will take a try.

**Comment by adamjstewart** [comment]
There are many ways to load packages into your environment. I agree that the documentation needs to be more clear about this. Adding a `documentation` tag.

If you have modules installed, you can add `share/spack/<modules or lmod>/...` to your `MODULEPATH` and run `module load` like you would on most supercomputing clusters. You can also use `spack load` to take advantage of Spack's spec syntax, although this requires sourcing the startup script. You can also use `spack view` to create a symlinked `/usr/local` directory, much like Homebrew would provide.

**Comment by zet809** [comment]
Hi, @adamjstewart , thanks very much for your suggests.
