### ISSUE TITLE
gcc@8.1.0 +binutils does not install correctly

### ISSUE THREAD

**Issue by amklinv** [spack/spack#8852]
@McClunatic and I are unable to install gcc 8.1.0 with the binutils variant enabled.

### Expected Result

I expected gcc@8.1.0 to install correctly.

### Actual Result

I get an error about CONSTEXPR.  Build log is attached.  Please let me know if any other information would be helpful.
```
/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/vec.h:531:3: error: ‘CONSTEXPR’ does not name a type
```
[spack-build.env.txt](https://github.com/spack/spack/files/2247504/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/2247512/spack-build.out.txt)

### Steps to reproduce the issue

```console
$ spack install gcc@8.1.0+binutils%gcc@4.8.5
```

### Information on your system

Centos7, x86_64

**Comment by scheibelp** [comment]
https://stackoverflow.com/questions/24845127/error-constexpr-does-not-name-a-type-m-arduino-ide suggests that "constexpr" is a c++11 feature. I assume that's not the default for gcc 4.8.5, and the failing compilation in `spack-build.out` sets `-std=gnu++98`:

```
/home/klinvex/spack/lib/spack/env/gcc/g++ -std=gnu++98 -c   -g -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -DGENERATOR_FILE -fno-PIE -I. -Ibuild -I/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc -I/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/build -I/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/../include  -I/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/../libcpp/include  \
	-o build/genmddeps.o /home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/genmddeps.c
In file included from /home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/genmddeps.c:23:0:
/home/klinvex/spack/var/spack/stage/gcc-8.1.0-4jyrud5wgzrae5oiu7pzynhhzmcrvc7g/gcc-8.1.0/gcc/vec.h:531:3: error: ‘CONSTEXPR’ does not name a type
   CONSTEXPR operator vec<T, A, L> () { return vec<T, A, L>(); }
   ^
```

As a sanity check: did you set the `-std` somewhere (e.g. in `compilers.yaml`)?

Rerunning with `-d` like `spack -d install...` will produce a `spack-cc-...in/out` file that records the actual compiler command that is run (after Spack adds options), which has more detail than what is in `spack-build.out`. Since the `-std` argument is mentioned there though that is likely a problem. `config.log` may also be helpful here to figure out why `std=gnu++98` was chosen if you didn't set that.

**Comment by goxberry** [comment]
@scheibelp [gcc requires a C++98-compliant compiler](https://gcc.gnu.org/install/prerequisites.html), which could be why `-std=c++98` is set.

**Comment by amklinv** [comment]
So do I need to install this with a newer compiler?

**Comment by scheibelp** [comment]
The link from https://github.com/spack/spack/issues/8852#issuecomment-409412731 suggests that `gcc 4.8` is sufficient (and I can't find any examples of people having issues with building gcc 8 with gcc 4.8.5). 

So I'm not really clear on what the issue is. A couple extra thoughts:

The error is occurring during `all-stage1`

> make[2]: *** [all-stage1-gcc] Error 2

And the Spack `gcc` package is setting specific stage1 flags when `+binutils` is enabled, so if you have the ability I'm curious if it builds with `~binutils`.

**Comment by amklinv** [comment]
Seems to be building with ~binutils

[spack-build.env.txt](https://github.com/spack/spack/files/2247711/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/2247712/spack-build.out.txt)

**Comment by adamjstewart** [comment]
Just to chime in, I've never gotten `gcc+binutils` to build for *any* version of GCC. That's why we changed the default to False. If you search through closed issues there are about a dozen related to `gcc+binutils`.

**Comment by scheibelp** [comment]
Is `~binutils` sufficient for you?

https://github.com/spack/spack/issues/6080 suggests that it may be failing because `libstdc++-static` needs to be installed, so if you have the ability to try that out I'd be curious if that works here (in that case this would be a duplicate of #6080)

**Comment by amklinv** [comment]
I removed the libstdc++-static flag, and the install seems to be getting further.  Feel free to close the issue; I'll reopen it if the install fails.

**Comment by amklinv** [comment]
...it failed.

**Comment by amklinv** [comment]
That seems to resolve the issue.  Thanks for the help!

**Comment by hartzell** [comment]
Is the change that @scheibelp describes something that should be PR'ed?

**Comment by scheibelp** [comment]
Good point @hartzell, I'll do that.
