### ISSUE TITLE
Guess core compilers for lmod, if not present

### ISSUE THREAD

**Issue by alalazo** [spack/spack#8916]
As a user I want core compilers for Lmod to be guessed by Spack (if they are not present in `modules.yaml`) so that I don't have to manually set-up things the first time I generate Lmod module files.

### Description
The proposal here is to guess which compilers are installed on the system and write automatically:
```yaml
lmod:
   core_compilers:
     - ...
```
if it is not already present. I think doing something like that makes sense as, from the feedback I receive, people are initially confused by the concept of "core compilers" and often don't know what they should put in there. The check done to guess core compilers could be something very simple, like checking if the path where registered compilers live match any pattern that Spack considers a "system" path.

If people think it's a good idea I'll put this into the `Modules improvement` project and start the implementation.

@svenevs @SteVwonder

**Comment by hartzell** [comment]
Seems like it could be useful.

I have a standard `modules.yaml` file that I carry around with me (actually embedded in [my `spack-install` script](https://gist.github.com/hartzell/d7d067e59695575c47e1c86b898b37fc)) and I'm constantly touching up the list of core compilers.

If I were to drop a file in that had a blank/missing `core_compilers` section but let me specify the remaining bits, would you be able to fill them in?

**Comment by SteVwonder** [comment]
:+1: I totally agree that Spack should automatically default to some reasonable `core_compilers`.  Seems really helpful.

> The check done to guess core compilers could be something very simple, like checking if the path where registered compilers live match any pattern that Spack considers a "system" path.

What exactly do you mean by "system" paths?  Is it simply anything that isn't built by Spack?  Are hand-built compilers installed in a user's home directory included?  At first glance, I think just Spack-built compilers should be excluded.

How to handle the case of a shared home directory mounted on many types of machines (different OS, different architectures, and thus different system compilers). Implemented naively, this would work well for the first machine that spack is run on, but would cause problems for the subsequent uses on the other types of machines.  Maybe whenever `spack compiler find` is run, the `core_compilers` list could be extended?

**Comment by adamjstewart** [comment]
I would treat "system" compilers as anything installed in `/`, `/usr/`, or `/usr/local/`. That's how we define "system" in `lib/spack/spack/util/environment.py`.

**Comment by svenevs** [comment]
I agree with Adam, keep the what is / isn't "system" consistent unless there is a compelling reason not to.

Will this automated thing be for `$SPACK_ROOT/etc` or for user level configs like compilers? If the latter I object, because won't that override my etc/ configs?

If no conflict, then sure it sounds nice. Myself I won't rely on it, when I setup a new spack I always configure all of my yaml before installing anything like shown above.

So as long as it won't interfere with / override my etc/ settings I'm happy. Though if users can't figure out how to setup their core complier, they probably won't benefit from such a feature. Things like cmake will still be installed for all compilers unless they install it with core first and blacklist it right?

**Comment by alalazo** [comment]
@hartzell 
> If I were to drop a file in that had a blank/missing core_compilers section but let me specify the remaining bits, would you be able to fill them in?

That's the idea, once this feature is implemented.

@SteVwonder @adamjstewart @svenevs 

> What exactly do you mean by "system" paths?

In pseudo-code (meaning expect typos) what I would do is something like:
```python
import os.path
import spack.util.environment as senv

directory = os.path.dirname(compiler_abs_path)
is_a_system_compiler = directory in senv.system_dirs
```
Said otherwise, if the directory where the compiler resides is a system directory according to Spack the compiler is considered a system compiler for the purposes explained in the description above.

**Comment by alalazo** [comment]
> Maybe whenever spack compiler find is run, the core_compilers list could be extended?

I don't think `spack compiler` needs to know that `modules.yaml` exist. The automation imo should happen lazily (whenever you need the list of core compilers to generate a module and you don't have it, compute it) rather than eagerly (whenever I add a new compiler I'll check if it can be added to the list of core compilers for `lmod`).

> Will this automated thing be for $SPACK_ROOT/etc or for user level configs like compilers? If the latter I object, because won't that override my etc/ configs?

I'll probably end up modifying `$SPACK_ROOT/etc/module.yaml`, and only in the case the `core_compilers` entry is not already present. That shouldn't be a big deal for users: without the `core_compilers` entry module generation will error out anyhow.

> Things like cmake will still be installed for all compilers unless they install it with core first and blacklist it right?

Correct. What I'll do here won't change the current status in this respect.

**Comment by svenevs** [comment]
Ok this all sounds good to me!

> without the `core_compliers` entry module generation will error anyhow

Playing devil's advocate, maybe an easier solution to implement / maintain is to change the erroring out behavior to a deferred warning but still generate the modules it can. So ideally at the end of module generation (since it can have potentially a lot of output) would be to simply "WARNING: LMod modules successfully generated, however no core complier listed. This is unlikely to be the module hierarchy you desire." (ANSI yellow ?)

Or something similar, maybe with a link to docs or something.

I have no preference either way, but the deferred warning might be a lot easier to do.
