### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by certik** [spack/spack#9323]
Spack should work on Windows.

### Rationale

Right now, I am able to use Spack on Linux and Mac and HPC, but some of our users/customers use Windows, and so we can't use Spack for that. If Spack is to become *the* package manager, it has to support Windows, as it is a very important platform.

### Description

It should support MSVC as one of the compilers and in general compile packages natively on Windows using any compilers that the user selects (MSVC, mingw, ...).

**Comment by davydden** [comment]
If its Windows 10, you should be able to use Linux Bash Shell.

**Comment by certik** [comment]
@davydden we need to compile using MSVC, so Spack must learn support for that, and then packages like Python needs to be ported to work.

**Comment by KineticTheory** [comment]
While CMake _plus_ Visual Studio Community Edition _plus_  msys2 gfortran provides an environment where spack could (in theory) work properly, there are other known issues:

* spack's use of symlinks, see #1515
* spack uses Linux specific python calls/modules that do not have matching implementations on native Windows (i.e.: not WLS or MSYS/MinGW or Cygwin).
* Most packages registered with spack do not have build systems that function under native Windows. Significant patching of source code will be required.

Other thoughts:

* spack works well under [WLS (Windows 10 bash)](https://docs.microsoft.com/en-us/windows/wsl/install-win10), [Cygwin](https://www.cygwin.com/) and [MSYS2/MinGW](http://www.msys2.org/).  This might be enough for some people.
* non-linking dependencies can be met with MSYS2 binaries installed via pacman.
* [MS-MPI ](https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi) seems stable and functional.

**Comment by certik** [comment]
@tgamblin, just a reminder, that this is the last big missing feature of Spack, that prevents me to use it more, as I need to support Windows with my open source software.

**Comment by jrobcary** [comment]
Some thoughts and questions on Windows:

First, we have not moved to spack due to lack of Windows support.  Instead we use an in-house system that lacks many features that spack has, but it works well enough that we can rely on it for nightly testing.

The main issue is native builds (as emphasized by @certik).  Spack working under WSL or Cygwin or MSYS does not solve this (though it might be part of a solution).

Build systems are not an issue for us.  We sometimes port or help port packages to CMake.  E.g., for python, we use https://github.com/python-cmake-buildsystem/python-cmake-buildsystem (actually our fork of that), most of that is done for our build chains.

Elimination of direct reliance on links seems big.  Elimination of reliance on environment-modules might be necessary.  

Would there be interest in a subgroup to discuss this?  (Or should this just be done through issues like this?)

**Comment by KiruyaMomochi** [comment]
I have tried spack on Windows, and found various problems.
After some change I can finally load simple CMake projects like `fmt`.

Here are all the fixes, patches, hacks and thoughts:

## Environment

- Microsoft Windows: 10.0.25182
- Visual Studio: 2022 Version 17.4.0 Preview 1.0
- Python: 3.10.5
- Spack: 0.19.0.dev0 
- CMake: 3.24.0 
- Ninja: 1.11.0

## Bootstrapping with Clingo

### Modify concertizer configuration

In order to use Clingo for bootstrapping, modify [config.yaml](https://spack.readthedocs.io/en/latest/config_yaml.html) file to add the following option:

```yaml
config:
  concretizer: clingo
```

### Fix build issue

Windows doesn't have `ssize_t`, and using `#undef _DEBUG` in VS2022 leads to ` _invalid_parameter` failures, therefore we need to patch Clingo code before building it. The code need to be patched can be found in [my clone of clingo](https://github.com/KiruyaMomochi/clingo/pull/1).

### Install or build dependencies

When spack doesn't find clingo, it will try to build it. However, GNU bison is built using autotools, which doesn't work on Windows. For such package we can use ports like https://github.com/lexxmark/winflexbison instead. There is already a PR for this: [Windows: Support for Clingo and dependencies](https://github.com/spack/spack/pull/30690), which ports various dependencies. 

But I haven't gave it a try. Instead, I installed them from chocolatey, then added bison, re2c, CMake and Ninja as external package in `~/.spack/bootstrap/config/packages.yaml`.

### Add Clingo's DLL to python search path

When importing `clingo`, it tries to locate library `libclingo.so`/`clingo.dll`. On Linux, absolute location Clingo DLL is recorded in `clingo.cpython-xxx.so` file by RPATH, which is written during installation. On Windows, there is no RPATH, so `import clingo` fails due to `clingo.dll` not found. 

Before Python 3.8, adding path of `clingo.dll` to PATH environment variable should work. But since 3.8 the [only search path for load-time dependencies](https://github.com/python/cpython/issues/87339) are:
- the loaded extension module's directory
- the application directory (e.g. that of `python.exe`)
- the user DLL search directories that get added by 
  `SetDllDirectory()` and `AddDllDirectory()`, such as with 
  `os.add_dll_directory()`
- `%SystemRoot%\System32`

Therefore, to make `clingo.dll` available, we need to append Clingo DLL's path by `os.add_dll_directory()`. We can also create symbolic link to this file under Clingo's module directory. 
Not too related but also see [Dynamic-Link Library Search Order - Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order)

## Handling DLL names on Windows

DLLs on Linux commonly has the prefix `lib` and end with `.so`, but it's not the case here. On Windows, despite from ending with `.dll`, DLLs may have or not have `lib` prefix (mostly not). 

There are multiple places we need to fix, including

https://github.com/spack/spack/blob/eb1c9c158330be898381980d0100d66066637a25/lib/spack/llnl/util/filesystem.py#L2050-L2060

https://github.com/spack/spack/blob/eb1c9c158330be898381980d0100d66066637a25/lib/spack/spack/build_environment.py#L111-L112

https://github.com/spack/spack/blob/eb1c9c158330be898381980d0100d66066637a25/lib/spack/spack/spec.py#L999-L1001

## Path of executables may contain spaces

When path of executable contains space, `spack.util.executable.which` gives a `Exectuable` object, whose `exe` attribute is splitted by space:

```python
exe = which_string('git')
print(exe) # 'C:\\Program Files\\Git\\cmd\\git.exe'
Exectuable(exe).exe # ['C:\\Program', 'Files\\Git\\cmd\\git.exe']
```

The solution is simple, since we use `shlex.split` to split the path, we `shelx.quote` it before creating `Exectuable` object.

https://github.com/spack/spack/blob/eb1c9c158330be898381980d0100d66066637a25/lib/spack/spack/util/executable.py#L25-L28

### `python.dll` on Windows

During bootstrapping clingo, spack tries to find `python.dll` in `_libs_default_handler` and then fails.
I have to create a copy from `python3.dll` under the same directory as `python3.exe`.

## No position independent code (PIC)

Some packages has a `pic` variant, which is used to build position independent code (PIC). Enabling such a variant will add `compiler.cxx_pic_flag` to the compiler flags. Current `msvc.py` doesn't override this, so the default value `-fPIC` is used:
https://github.com/spack/spack/blob/eb1c9c158330be898381980d0100d66066637a25/lib/spack/spack/compiler.py#L494-L504

But as all DLL code is relocatable in Windows, such a flag does not make sense, and MSVC also can't understand `-fPIC`. We should either override this flag with an empty string, or fail the build.

> Side story: `fmt` package relies on `/EHsc` flags provided by CMake's default `DCMAKE_C_FLAGS` and `DCMAKE_CXX_FLAGS`. After `+pic` sets them. Default flags are overwritten and unexpectedly fails the build. I'm considering if this is actually a bug in `fmt`... 

## Git FS monitor breaks cache creating

If someone has enabled [Git filesystem monitor](https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/), there will be a long-running process that watches the filesystem for changes. Then rename the repository will fail. Spack's `cache_local` feature need to rename folder name, `spack-src`, to the package name, so it fails. This is tracked in another issue https://github.com/spack/spack/issues/32404. 

## Ninja should not be a run dependency

`CMake` build system lists `ninja` as a dependency on Windows, causing the built package depends on `Ninja` when loading. Then, loading the package fails because `make_deps` doesn't exists when `modifications_from_dependencies`: 

https://github.com/spack/spack/blob/ceda5fb46ccae8b2942d962c58a9011a56742e6e/lib/spack/spack/user_environment.py#L88-L97

This can be fixed by remove `ninja` from run dependency like https://github.com/spack/spack/pull/32391. But maybe we should also make `set_module_variables_for_package` happens before `modifications_from_dependencies`?

## Further problem

### Shell integration

Current `setup-env.ps1` is simple, as it can't handle commands like `spack load`. I haven't extended it yet, but after adding `--pwsh` to commands like `load` and `install`, I think it's time to consider refactoring it to something like `--shell <sh>`.

### How to support `autotools` package?

It's possible to "support" packages using automake/autoconf by porting them to CMake, but that will be a lot of work.
When searching for alternative ways, I found [vcpkg](https://vcpkg.io) supports it by [using msys2](https://github.com/microsoft/vcpkg/blob/083e31d80b16df070d9aac4d8cfb9fd30a593171/scripts/cmake/vcpkg_build_make.cmake#L40). Maybe that will work for us too?

### Prefix and `bin`

Not all packages have their executables in `bin` folder under install prefix.
If some package assumes that, it will be hard for us to config for external.

**Comment by adamjstewart** [comment]
^ @scheibelp @johnwparent @loulawrence @BetsyMcPhail 

P.S. We should create a GitHub "team" for all Spack + Windows developers.

**Comment by tgamblin** [comment]
@scheibelp @johnwparent There is still work to do, but I think we can close this long-standing issue in light of windows CI finally being stable. What do you think? @certik? @adamjstewart?

**Comment by johnwparent** [comment]
@tgamblin Makes sense to me, "Windows Support" is in, what's left are individual features and IMO that fulfills the spirit of this issue.

**Comment by certik** [comment]
I think it's fixed! Thank you so much @tgamblin and team for getting it done!
