### ISSUE TITLE
Julia package needs updated dependencies

### ISSUE THREAD

**Issue by briedel** [spack/spack#9581]
See: https://github.com/JuliaLang/julia#required-build-tools-and-external-libraries

**Comment by rgmiller** [comment]
There are new versions of Julia available.  As long as someone is messing with package.py, it'd probably be a good idea to add them.

**Comment by alalazo** [comment]
@eschnett For your information

**Comment by eschnett** [comment]
I am no longer using Julia via Spack. Julia's installer is quite self-reliant (and doesn't require any system packages, as it brings its own), and Julia's package manager has much improved and doesn't benefit from Spack (unlike e.g. Python). These days, I would recommend installing Julia directly instead of via Spack.

I think this package should either be removed, or should be much simplified to simply download and install Julia. Making the Julia build use Spack's packages is probably more trouble than it's worth since this would require ensuring that the patches that Julia applies e.g. to OpenBLAS are also available in Spack, and that the expected configuration options are used.
